// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_standbySCREEN_screen_init();
    ui_totalpowerSCREEN_screen_init();
    ui_prot1SCREEN_screen_init();
    ui_port1SCREEN12_screen_init();
    ui_prot2SCREEN_screen_init();
    ui_prot3SCREEN_screen_init();
    ui_prot4SCREEN_screen_init();
    ui_port2SCREEN22_screen_init();
    ui_port3SCREEN32_screen_init();
    ui_port4SCREEN42_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_standbySCREEN);
}

void ui_destroy(void)
{
    ui_standbySCREEN_screen_destroy();
    ui_totalpowerSCREEN_screen_destroy();
    ui_prot1SCREEN_screen_destroy();
    ui_port1SCREEN12_screen_destroy();
    ui_prot2SCREEN_screen_destroy();
    ui_prot3SCREEN_screen_destroy();
    ui_prot4SCREEN_screen_destroy();
    ui_port2SCREEN22_screen_destroy();
    ui_port3SCREEN32_screen_destroy();
    ui_port4SCREEN42_screen_destroy();
}

void ui_relocalize(void)
{
    ui_standbySCREEN_screen_relocalize();
    ui_totalpowerSCREEN_screen_relocalize();
    ui_prot1SCREEN_screen_relocalize();
    ui_port1SCREEN12_screen_relocalize();
    ui_prot2SCREEN_screen_relocalize();
    ui_prot3SCREEN_screen_relocalize();
    ui_prot4SCREEN_screen_relocalize();
    ui_port2SCREEN22_screen_relocalize();
    ui_port3SCREEN32_screen_relocalize();
    ui_port4SCREEN42_screen_relocalize();
}
