// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_standbySCREEN.h"
#include "ui_totalpowerSCREEN.h"
#include "ui_prot1SCREEN.h"
#include "ui_port1SCREEN12.h"
#include "ui_prot2SCREEN.h"
#include "ui_prot3SCREEN.h"
#include "ui_prot4SCREEN.h"
#include "ui_port2SCREEN22.h"
#include "ui_port3SCREEN32.h"
#include "ui_port4SCREEN42.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_52731097);    // assets/微信图片_20250707122227_副本.png
LV_IMG_DECLARE(ui_img_411710101);    // assets/微信图片_20250707140948_副本.png
LV_IMG_DECLARE(ui_img_334752297);    // assets/竹子透明_副本.png
LV_IMG_DECLARE(ui_img_888914300);    // assets/竹子_副本.png
LV_IMG_DECLARE(ui_img_919862230);    // assets/port_副本.png
LV_IMG_DECLARE(ui_img_934861631);    // assets/xieyi_副本.png

// FONTS
LV_FONT_DECLARE(ui_font_daoli24zhong);
LV_FONT_DECLARE(ui_font_daoli26zhong);
LV_FONT_DECLARE(ui_font_DaoLit36zhong);
LV_FONT_DECLARE(ui_font_DaoLit36zhong3);
LV_FONT_DECLARE(ui_font_DaoLiti30);
LV_FONT_DECLARE(ui_font_DaoLiti36);
LV_FONT_DECLARE(ui_font_DaoLiti72);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
