// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"
#include "ui2_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui2____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui2_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui2_standbySCREEN_screen_init();
    ui2_totalpowerSCREEN_screen_init();
    ui2_port1SCREEN_screen_init();
    ui2_port2SCREEN_screen_init();
    ui2_port3SCREEN_screen_init();
    ui2_port4SCREEN_screen_init();
    ui2____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui2_standbySCREEN);
}

void ui2_destroy(void)
{
    ui2_standbySCREEN_screen_destroy();
    ui2_totalpowerSCREEN_screen_destroy();
    ui2_port1SCREEN_screen_destroy();
    ui2_port2SCREEN_screen_destroy();
    ui2_port3SCREEN_screen_destroy();
    ui2_port4SCREEN_screen_destroy();
}

void ui2_relocalize(void)
{
    ui2_standbySCREEN_screen_relocalize();
    ui2_totalpowerSCREEN_screen_relocalize();
    ui2_port1SCREEN_screen_relocalize();
    ui2_port2SCREEN_screen_relocalize();
    ui2_port3SCREEN_screen_relocalize();
    ui2_port4SCREEN_screen_relocalize();
}
