// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI2_H
#define _SQUARELINE_PROJECT_UI2_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui2_helpers.h"
#include "ui2_events.h"

///////////////////// SCREENS ////////////////////

#include "ui2_standbySCREEN.h"
#include "ui2_totalpowerSCREEN.h"
#include "ui2_port1SCREEN.h"
#include "ui2_port2SCREEN.h"
#include "ui2_port3SCREEN.h"
#include "ui2_port4SCREEN.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui2____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui2_img_1985331572);    // assets/微信图片_20250711110242_副本.png

// FONTS
LV_FONT_DECLARE(ui2_font_ShuHei14);
LV_FONT_DECLARE(ui2_font_ShuHei26);
LV_FONT_DECLARE(ui2_font_ShuHei30);
LV_FONT_DECLARE(ui2_font_ShuHei36);
LV_FONT_DECLARE(ui2_font_ShuHei72);

// UI2 INIT
void ui2_init(void);
void ui2_destroy(void);
void ui2_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
