// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui2_PORT2SCREEN_H
#define ui2_PORT2SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui2_port2SCREEN
extern void ui2_port2SCREEN_screen_init(void);
extern void ui2_port2SCREEN_screen_destroy(void);
extern void ui2_port2SCREEN_screen_relocalize(void);
extern void ui2_event_port2SCREEN(lv_event_t * e);
extern lv_obj_t * ui2_port2SCREEN;
extern lv_obj_t * ui2_Container34;
extern lv_obj_t * ui2_Panel32;
extern lv_obj_t * ui2_Label45;
extern lv_obj_t * ui2_Container35;
extern lv_obj_t * ui2_Panel33;
extern lv_obj_t * ui2_Panel34;
extern lv_obj_t * ui2_Label49;
extern lv_obj_t * ui2_port2voltage1;
extern lv_obj_t * ui2_Container36;
extern lv_obj_t * ui2_Panel35;
extern lv_obj_t * ui2_Panel36;
extern lv_obj_t * ui2_Label51;
extern lv_obj_t * ui2_port2current1;
extern lv_obj_t * ui2_Container37;
extern lv_obj_t * ui2_Panel37;
extern lv_obj_t * ui2_Panel38;
extern lv_obj_t * ui2_Label53;
extern lv_obj_t * ui2_port2powerlabel1;
extern lv_obj_t * ui2_Container38;
extern lv_obj_t * ui2_Panel39;
extern lv_obj_t * ui2_Label65;
extern lv_obj_t * ui2_Container39;
extern lv_obj_t * ui2_port2powerlabel;
extern lv_obj_t * ui2_Container40;
extern lv_obj_t * ui2_port2state;
extern lv_obj_t * ui2_Container41;
extern lv_obj_t * ui2_Panel40;
extern lv_obj_t * ui2_Label68;
extern lv_obj_t * ui2_Container42;
extern lv_obj_t * ui2_Label69;
extern lv_obj_t * ui2_port2protocol;
extern lv_obj_t * ui2_Container43;
extern lv_obj_t * ui2_Label71;
extern lv_obj_t * ui2_port2revision;
extern lv_obj_t * ui2_Container44;
extern lv_obj_t * ui2_Label73;
extern lv_obj_t * ui2_port2protocolpower;
extern lv_obj_t * ui2_Container45;
extern lv_obj_t * ui2_Container46;
extern lv_obj_t * ui2_Panel41;
extern lv_obj_t * ui2_Label75;
extern lv_obj_t * ui2_Container47;
extern lv_obj_t * ui2_Label76;
extern lv_obj_t * ui2_port2manufactuervid;
extern lv_obj_t * ui2_Container48;
extern lv_obj_t * ui2_Label78;
extern lv_obj_t * ui2_port2cablevid;
extern lv_obj_t * ui2_Container49;
extern lv_obj_t * ui2_Label80;
extern lv_obj_t * ui2_port2maxvbusvoltage;
extern lv_obj_t * ui2_Container50;
extern lv_obj_t * ui2_Label82;
extern lv_obj_t * ui2_port2maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

