// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"

lv_obj_t * ui2_port3SCREEN = NULL;
lv_obj_t * ui2_Container51 = NULL;
lv_obj_t * ui2_Panel42 = NULL;
lv_obj_t * ui2_Label84 = NULL;
lv_obj_t * ui2_Container52 = NULL;
lv_obj_t * ui2_Panel43 = NULL;
lv_obj_t * ui2_Panel44 = NULL;
lv_obj_t * ui2_Label85 = NULL;
lv_obj_t * ui2_port3voltage1 = NULL;
lv_obj_t * ui2_Container53 = NULL;
lv_obj_t * ui2_Panel45 = NULL;
lv_obj_t * ui2_Panel46 = NULL;
lv_obj_t * ui2_Label87 = NULL;
lv_obj_t * ui2_port3current1 = NULL;
lv_obj_t * ui2_Container54 = NULL;
lv_obj_t * ui2_Panel47 = NULL;
lv_obj_t * ui2_Panel48 = NULL;
lv_obj_t * ui2_Label89 = NULL;
lv_obj_t * ui2_port3powerlabel1 = NULL;
lv_obj_t * ui2_Container55 = NULL;
lv_obj_t * ui2_Panel49 = NULL;
lv_obj_t * ui2_Label91 = NULL;
lv_obj_t * ui2_Container56 = NULL;
lv_obj_t * ui2_port3powerlabel = NULL;
lv_obj_t * ui2_Container57 = NULL;
lv_obj_t * ui2_port3state = NULL;
lv_obj_t * ui2_Container58 = NULL;
lv_obj_t * ui2_Panel50 = NULL;
lv_obj_t * ui2_Label94 = NULL;
lv_obj_t * ui2_Container59 = NULL;
lv_obj_t * ui2_Label95 = NULL;
lv_obj_t * ui2_port3protocol = NULL;
lv_obj_t * ui2_Container60 = NULL;
lv_obj_t * ui2_Label97 = NULL;
lv_obj_t * ui2_port3revision = NULL;
lv_obj_t * ui2_Container61 = NULL;
lv_obj_t * ui2_Label99 = NULL;
lv_obj_t * ui2_port3protocolpower = NULL;
lv_obj_t * ui2_Container62 = NULL;
lv_obj_t * ui2_Container63 = NULL;
lv_obj_t * ui2_Panel51 = NULL;
lv_obj_t * ui2_Label101 = NULL;
lv_obj_t * ui2_Container64 = NULL;
lv_obj_t * ui2_Label102 = NULL;
lv_obj_t * ui2_port3manufactuervid = NULL;
lv_obj_t * ui2_Container65 = NULL;
lv_obj_t * ui2_Label104 = NULL;
lv_obj_t * ui2_port3cablevid = NULL;
lv_obj_t * ui2_Container66 = NULL;
lv_obj_t * ui2_Label106 = NULL;
lv_obj_t * ui2_port3maxvbusvoltage = NULL;
lv_obj_t * ui2_Container67 = NULL;
lv_obj_t * ui2_Label108 = NULL;
lv_obj_t * ui2_port3maxvbuscurrent = NULL;
// event funtions
void ui2_event_port3SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_totalpowerSCREEN, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui2_totalpowerSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port2SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui2_port2SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port4SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui2_port4SCREEN_screen_init);
    }
}

// build funtions

void ui2_port3SCREEN_screen_init(void)
{
    ui2_port3SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_port3SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container51 = lv_obj_create(ui2_port3SCREEN);
    lv_obj_remove_style_all(ui2_Container51);
    lv_obj_set_width(ui2_Container51, lv_pct(100));
    lv_obj_set_height(ui2_Container51, lv_pct(100));
    lv_obj_set_align(ui2_Container51, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container51, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container51, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container51, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel42 = lv_obj_create(ui2_Container51);
    lv_obj_set_width(ui2_Panel42, 368);
    lv_obj_set_height(ui2_Panel42, 49);
    lv_obj_set_align(ui2_Panel42, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel42, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel42, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel42, lv_color_hex(0x733CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label84 = lv_label_create(ui2_Panel42);
    lv_obj_set_width(ui2_Label84, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label84, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label84, -34);
    lv_obj_set_y(ui2_Label84, -201);
    lv_obj_set_align(ui2_Label84, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label84, "C3 PORT");
    lv_obj_set_style_text_color(ui2_Label84, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label84, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label84, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container52 = lv_obj_create(ui2_Container51);
    lv_obj_remove_style_all(ui2_Container52);
    lv_obj_set_width(ui2_Container52, 246);
    lv_obj_set_height(ui2_Container52, 168);
    lv_obj_set_x(ui2_Container52, -36);
    lv_obj_set_y(ui2_Container52, -72);
    lv_obj_set_align(ui2_Container52, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container52, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container52, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container52, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel43 = lv_obj_create(ui2_Container52);
    lv_obj_set_width(ui2_Panel43, 240);
    lv_obj_set_height(ui2_Panel43, 50);
    lv_obj_set_x(ui2_Panel43, -24);
    lv_obj_set_y(ui2_Panel43, -115);
    lv_obj_set_align(ui2_Panel43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel43, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel43, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel44 = lv_obj_create(ui2_Panel43);
    lv_obj_set_width(ui2_Panel44, 40);
    lv_obj_set_height(ui2_Panel44, 40);
    lv_obj_set_x(ui2_Panel44, -127);
    lv_obj_set_y(ui2_Panel44, -131);
    lv_obj_set_align(ui2_Panel44, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel44, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel44, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel44, lv_color_hex(0x733CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel44, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label85 = lv_label_create(ui2_Panel44);
    lv_obj_set_width(ui2_Label85, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label85, -70);
    lv_obj_set_y(ui2_Label85, -94);
    lv_obj_set_align(ui2_Label85, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label85, "U");
    lv_obj_set_style_text_color(ui2_Label85, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label85, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label85, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3voltage1 = lv_label_create(ui2_Panel43);
    lv_obj_set_width(ui2_port3voltage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3voltage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3voltage1, -7);
    lv_obj_set_y(ui2_port3voltage1, -131);
    lv_obj_set_align(ui2_port3voltage1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3voltage1, "27.842V");
    lv_obj_set_style_text_color(ui2_port3voltage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port3voltage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port3voltage1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container53 = lv_obj_create(ui2_Container52);
    lv_obj_remove_style_all(ui2_Container53);
    lv_obj_set_width(ui2_Container53, 243);
    lv_obj_set_height(ui2_Container53, 3);
    lv_obj_set_align(ui2_Container53, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container53, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel45 = lv_obj_create(ui2_Container52);
    lv_obj_set_width(ui2_Panel45, 240);
    lv_obj_set_height(ui2_Panel45, 50);
    lv_obj_set_x(ui2_Panel45, -19);
    lv_obj_set_y(ui2_Panel45, -57);
    lv_obj_set_align(ui2_Panel45, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel45, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel45, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel46 = lv_obj_create(ui2_Panel45);
    lv_obj_set_width(ui2_Panel46, 40);
    lv_obj_set_height(ui2_Panel46, 40);
    lv_obj_set_x(ui2_Panel46, -131);
    lv_obj_set_y(ui2_Panel46, -78);
    lv_obj_set_align(ui2_Panel46, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel46, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel46, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel46, lv_color_hex(0x733CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel46, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label87 = lv_label_create(ui2_Panel46);
    lv_obj_set_width(ui2_Label87, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label87, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label87, -82);
    lv_obj_set_y(ui2_Label87, -38);
    lv_obj_set_align(ui2_Label87, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label87, "I");
    lv_obj_set_style_text_color(ui2_Label87, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label87, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label87, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3current1 = lv_label_create(ui2_Panel45);
    lv_obj_set_width(ui2_port3current1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3current1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3current1, -16);
    lv_obj_set_y(ui2_port3current1, -78);
    lv_obj_set_align(ui2_port3current1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3current1, "3.564A");
    lv_obj_set_style_text_color(ui2_port3current1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port3current1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port3current1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container54 = lv_obj_create(ui2_Container52);
    lv_obj_remove_style_all(ui2_Container54);
    lv_obj_set_width(ui2_Container54, 243);
    lv_obj_set_height(ui2_Container54, 3);
    lv_obj_set_align(ui2_Container54, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container54, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel47 = lv_obj_create(ui2_Container52);
    lv_obj_set_width(ui2_Panel47, 240);
    lv_obj_set_height(ui2_Panel47, 50);
    lv_obj_set_x(ui2_Panel47, -16);
    lv_obj_set_y(ui2_Panel47, 2);
    lv_obj_set_align(ui2_Panel47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel47, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel47, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel48 = lv_obj_create(ui2_Panel47);
    lv_obj_set_width(ui2_Panel48, 40);
    lv_obj_set_height(ui2_Panel48, 40);
    lv_obj_set_x(ui2_Panel48, -131);
    lv_obj_set_y(ui2_Panel48, -25);
    lv_obj_set_align(ui2_Panel48, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel48, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel48, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel48, lv_color_hex(0x733CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel48, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label89 = lv_label_create(ui2_Panel48);
    lv_obj_set_width(ui2_Label89, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label89, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label89, -67);
    lv_obj_set_y(ui2_Label89, 26);
    lv_obj_set_align(ui2_Label89, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label89, "P");
    lv_obj_set_style_text_color(ui2_Label89, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label89, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label89, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3powerlabel1 = lv_label_create(ui2_Panel47);
    lv_obj_set_width(ui2_port3powerlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3powerlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3powerlabel1, -15);
    lv_obj_set_y(ui2_port3powerlabel1, -28);
    lv_obj_set_align(ui2_port3powerlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3powerlabel1, "30.658W");
    lv_obj_set_style_text_color(ui2_port3powerlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port3powerlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port3powerlabel1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container55 = lv_obj_create(ui2_Container51);
    lv_obj_remove_style_all(ui2_Container55);
    lv_obj_set_height(ui2_Container55, 155);
    lv_obj_set_width(ui2_Container55, lv_pct(32));
    lv_obj_set_x(ui2_Container55, 119);
    lv_obj_set_y(ui2_Container55, -26);
    lv_obj_set_align(ui2_Container55, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container55, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container55, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container55, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container55, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container55, lv_color_hex(0x07595D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container55, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel49 = lv_obj_create(ui2_Container55);
    lv_obj_set_width(ui2_Panel49, lv_pct(100));
    lv_obj_set_height(ui2_Panel49, lv_pct(24));
    lv_obj_set_x(ui2_Panel49, 121);
    lv_obj_set_y(ui2_Panel49, -77);
    lv_obj_set_align(ui2_Panel49, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel49, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel49, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel49, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel49, lv_color_hex(0x095C62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel49, lv_color_hex(0x07585A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label91 = lv_label_create(ui2_Panel49);
    lv_obj_set_width(ui2_Label91, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label91, "STATE");
    lv_obj_set_style_text_font(ui2_Label91, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container56 = lv_obj_create(ui2_Container55);
    lv_obj_remove_style_all(ui2_Container56);
    lv_obj_set_width(ui2_Container56, 100);
    lv_obj_set_height(ui2_Container56, 18);
    lv_obj_set_align(ui2_Container56, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container56, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port3powerlabel = lv_label_create(ui2_Container55);
    lv_obj_set_width(ui2_port3powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3powerlabel, 122);
    lv_obj_set_y(ui2_port3powerlabel, -61);
    lv_obj_set_align(ui2_port3powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3powerlabel, "已开启");
    lv_obj_set_style_text_font(ui2_port3powerlabel, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container57 = lv_obj_create(ui2_Container55);
    lv_obj_remove_style_all(ui2_Container57);
    lv_obj_set_width(ui2_Container57, 100);
    lv_obj_set_height(ui2_Container57, 16);
    lv_obj_set_align(ui2_Container57, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container57, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port3state = lv_label_create(ui2_Container55);
    lv_obj_set_width(ui2_port3state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3state, 120);
    lv_obj_set_y(ui2_port3state, -8);
    lv_obj_set_align(ui2_port3state, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3state, "已连接");
    lv_obj_set_style_text_font(ui2_port3state, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container58 = lv_obj_create(ui2_Container51);
    lv_obj_remove_style_all(ui2_Container58);
    lv_obj_set_width(ui2_Container58, 180);
    lv_obj_set_height(ui2_Container58, 151);
    lv_obj_set_x(ui2_Container58, 93);
    lv_obj_set_y(ui2_Container58, 102);
    lv_obj_set_align(ui2_Container58, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container58, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container58, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container58, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container58, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container58, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container58, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel50 = lv_obj_create(ui2_Container58);
    lv_obj_set_width(ui2_Panel50, lv_pct(100));
    lv_obj_set_height(ui2_Panel50, lv_pct(24));
    lv_obj_set_x(ui2_Panel50, 64);
    lv_obj_set_y(ui2_Panel50, 58);
    lv_obj_set_align(ui2_Panel50, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel50, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel50, lv_color_hex(0xBA7408), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel50, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label94 = lv_label_create(ui2_Panel50);
    lv_obj_set_width(ui2_Label94, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label94, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label94, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label94, "PROTOCOL");
    lv_obj_set_style_text_font(ui2_Label94, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container59 = lv_obj_create(ui2_Container58);
    lv_obj_remove_style_all(ui2_Container59);
    lv_obj_set_width(ui2_Container59, lv_pct(70));
    lv_obj_set_height(ui2_Container59, lv_pct(25));
    lv_obj_set_x(ui2_Container59, -3);
    lv_obj_set_y(ui2_Container59, 56);
    lv_obj_set_align(ui2_Container59, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container59, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container59, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container59, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label95 = lv_label_create(ui2_Container59);
    lv_obj_set_width(ui2_Label95, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label95, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label95, -142);
    lv_obj_set_y(ui2_Label95, 94);
    lv_obj_set_align(ui2_Label95, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label95, "协议：");
    lv_obj_set_style_text_font(ui2_Label95, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3protocol = lv_label_create(ui2_Container59);
    lv_obj_set_width(ui2_port3protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3protocol, -94);
    lv_obj_set_y(ui2_port3protocol, 91);
    lv_obj_set_align(ui2_port3protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3protocol, "PD");
    lv_obj_set_style_text_font(ui2_port3protocol, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container60 = lv_obj_create(ui2_Container58);
    lv_obj_remove_style_all(ui2_Container60);
    lv_obj_set_width(ui2_Container60, lv_pct(70));
    lv_obj_set_height(ui2_Container60, lv_pct(22));
    lv_obj_set_x(ui2_Container60, -3);
    lv_obj_set_y(ui2_Container60, 56);
    lv_obj_set_align(ui2_Container60, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container60, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container60, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container60, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label97 = lv_label_create(ui2_Container60);
    lv_obj_set_width(ui2_Label97, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label97, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label97, -141);
    lv_obj_set_y(ui2_Label97, 120);
    lv_obj_set_align(ui2_Label97, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label97, "版本：");
    lv_obj_set_style_text_font(ui2_Label97, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3revision = lv_label_create(ui2_Container60);
    lv_obj_set_width(ui2_port3revision, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3revision, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3revision, -93);
    lv_obj_set_y(ui2_port3revision, 120);
    lv_obj_set_align(ui2_port3revision, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3revision, "3.0");
    lv_obj_set_style_text_font(ui2_port3revision, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container61 = lv_obj_create(ui2_Container58);
    lv_obj_remove_style_all(ui2_Container61);
    lv_obj_set_width(ui2_Container61, lv_pct(70));
    lv_obj_set_height(ui2_Container61, lv_pct(22));
    lv_obj_set_x(ui2_Container61, -3);
    lv_obj_set_y(ui2_Container61, 56);
    lv_obj_set_align(ui2_Container61, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container61, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container61, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container61, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label99 = lv_label_create(ui2_Container61);
    lv_obj_set_width(ui2_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label99, -141);
    lv_obj_set_y(ui2_Label99, 147);
    lv_obj_set_align(ui2_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label99, "功率：");
    lv_obj_set_style_text_font(ui2_Label99, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3protocolpower = lv_label_create(ui2_Container61);
    lv_obj_set_width(ui2_port3protocolpower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3protocolpower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3protocolpower, -86);
    lv_obj_set_y(ui2_port3protocolpower, 145);
    lv_obj_set_align(ui2_port3protocolpower, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3protocolpower, "100W");
    lv_obj_set_style_text_font(ui2_port3protocolpower, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container62 = lv_obj_create(ui2_Container51);
    lv_obj_remove_style_all(ui2_Container62);
    lv_obj_set_width(ui2_Container62, 5);
    lv_obj_set_height(ui2_Container62, 136);
    lv_obj_set_align(ui2_Container62, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container62, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container63 = lv_obj_create(ui2_Container51);
    lv_obj_remove_style_all(ui2_Container63);
    lv_obj_set_width(ui2_Container63, 180);
    lv_obj_set_height(ui2_Container63, 151);
    lv_obj_set_x(ui2_Container63, -89);
    lv_obj_set_y(ui2_Container63, 102);
    lv_obj_set_align(ui2_Container63, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container63, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container63, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container63, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container63, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container63, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container63, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel51 = lv_obj_create(ui2_Container63);
    lv_obj_set_width(ui2_Panel51, lv_pct(100));
    lv_obj_set_height(ui2_Panel51, lv_pct(24));
    lv_obj_set_x(ui2_Panel51, -78);
    lv_obj_set_y(ui2_Panel51, 72);
    lv_obj_set_align(ui2_Panel51, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel51, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel51, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel51, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel51, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel51, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label101 = lv_label_create(ui2_Panel51);
    lv_obj_set_width(ui2_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label101, -116);
    lv_obj_set_y(ui2_Label101, 71);
    lv_obj_set_align(ui2_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label101, "WIRE ROD");
    lv_obj_set_style_text_font(ui2_Label101, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container64 = lv_obj_create(ui2_Container63);
    lv_obj_remove_style_all(ui2_Container64);
    lv_obj_set_width(ui2_Container64, lv_pct(75));
    lv_obj_set_height(ui2_Container64, lv_pct(20));
    lv_obj_set_x(ui2_Container64, 82);
    lv_obj_set_y(ui2_Container64, 89);
    lv_obj_set_align(ui2_Container64, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container64, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container64, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container64, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label102 = lv_label_create(ui2_Container64);
    lv_obj_set_width(ui2_Label102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label102, 50);
    lv_obj_set_y(ui2_Label102, 92);
    lv_obj_set_align(ui2_Label102, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label102, "制造商：");
    lv_obj_set_style_text_font(ui2_Label102, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3manufactuervid = lv_label_create(ui2_Container64);
    lv_obj_set_width(ui2_port3manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3manufactuervid, 110);
    lv_obj_set_y(ui2_port3manufactuervid, 89);
    lv_obj_set_align(ui2_port3manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3manufactuervid, "小米");
    lv_obj_set_style_text_font(ui2_port3manufactuervid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container65 = lv_obj_create(ui2_Container63);
    lv_obj_remove_style_all(ui2_Container65);
    lv_obj_set_width(ui2_Container65, lv_pct(75));
    lv_obj_set_height(ui2_Container65, lv_pct(17));
    lv_obj_set_x(ui2_Container65, 82);
    lv_obj_set_y(ui2_Container65, 89);
    lv_obj_set_align(ui2_Container65, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container65, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container65, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container65, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label104 = lv_label_create(ui2_Container65);
    lv_obj_set_width(ui2_Label104, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label104, 50);
    lv_obj_set_y(ui2_Label104, 92);
    lv_obj_set_align(ui2_Label104, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label104, "线缆厂商：");
    lv_obj_set_style_text_font(ui2_Label104, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3cablevid = lv_label_create(ui2_Container65);
    lv_obj_set_width(ui2_port3cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3cablevid, 110);
    lv_obj_set_y(ui2_port3cablevid, 89);
    lv_obj_set_align(ui2_port3cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3cablevid, "酷态科");
    lv_obj_set_style_text_font(ui2_port3cablevid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container66 = lv_obj_create(ui2_Container63);
    lv_obj_remove_style_all(ui2_Container66);
    lv_obj_set_width(ui2_Container66, lv_pct(75));
    lv_obj_set_height(ui2_Container66, lv_pct(17));
    lv_obj_set_x(ui2_Container66, 82);
    lv_obj_set_y(ui2_Container66, 89);
    lv_obj_set_align(ui2_Container66, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container66, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container66, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container66, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label106 = lv_label_create(ui2_Container66);
    lv_obj_set_width(ui2_Label106, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label106, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label106, 50);
    lv_obj_set_y(ui2_Label106, 92);
    lv_obj_set_align(ui2_Label106, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label106, "最大电压：");
    lv_obj_set_style_text_font(ui2_Label106, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3maxvbusvoltage = lv_label_create(ui2_Container66);
    lv_obj_set_width(ui2_port3maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3maxvbusvoltage, 110);
    lv_obj_set_y(ui2_port3maxvbusvoltage, 89);
    lv_obj_set_align(ui2_port3maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3maxvbusvoltage, "20V");
    lv_obj_set_style_text_font(ui2_port3maxvbusvoltage, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container67 = lv_obj_create(ui2_Container63);
    lv_obj_remove_style_all(ui2_Container67);
    lv_obj_set_width(ui2_Container67, lv_pct(75));
    lv_obj_set_height(ui2_Container67, lv_pct(17));
    lv_obj_set_x(ui2_Container67, 82);
    lv_obj_set_y(ui2_Container67, 89);
    lv_obj_set_align(ui2_Container67, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container67, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container67, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container67, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label108 = lv_label_create(ui2_Container67);
    lv_obj_set_width(ui2_Label108, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label108, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label108, 50);
    lv_obj_set_y(ui2_Label108, 92);
    lv_obj_set_align(ui2_Label108, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label108, "最大电流：");
    lv_obj_set_style_text_font(ui2_Label108, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3maxvbuscurrent = lv_label_create(ui2_Container67);
    lv_obj_set_width(ui2_port3maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3maxvbuscurrent, 110);
    lv_obj_set_y(ui2_port3maxvbuscurrent, 89);
    lv_obj_set_align(ui2_port3maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3maxvbuscurrent, "5A");
    lv_obj_set_style_text_font(ui2_port3maxvbuscurrent, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui2_port3SCREEN, ui2_event_port3SCREEN, LV_EVENT_ALL, NULL);

}

void ui2_port3SCREEN_screen_destroy(void)
{
    if(ui2_port3SCREEN) lv_obj_del(ui2_port3SCREEN);

    // NULL screen variables
    ui2_port3SCREEN = NULL;
    ui2_Container51 = NULL;
    ui2_Panel42 = NULL;
    ui2_Label84 = NULL;
    ui2_Container52 = NULL;
    ui2_Panel43 = NULL;
    ui2_Panel44 = NULL;
    ui2_Label85 = NULL;
    ui2_port3voltage1 = NULL;
    ui2_Container53 = NULL;
    ui2_Panel45 = NULL;
    ui2_Panel46 = NULL;
    ui2_Label87 = NULL;
    ui2_port3current1 = NULL;
    ui2_Container54 = NULL;
    ui2_Panel47 = NULL;
    ui2_Panel48 = NULL;
    ui2_Label89 = NULL;
    ui2_port3powerlabel1 = NULL;
    ui2_Container55 = NULL;
    ui2_Panel49 = NULL;
    ui2_Label91 = NULL;
    ui2_Container56 = NULL;
    ui2_port3powerlabel = NULL;
    ui2_Container57 = NULL;
    ui2_port3state = NULL;
    ui2_Container58 = NULL;
    ui2_Panel50 = NULL;
    ui2_Label94 = NULL;
    ui2_Container59 = NULL;
    ui2_Label95 = NULL;
    ui2_port3protocol = NULL;
    ui2_Container60 = NULL;
    ui2_Label97 = NULL;
    ui2_port3revision = NULL;
    ui2_Container61 = NULL;
    ui2_Label99 = NULL;
    ui2_port3protocolpower = NULL;
    ui2_Container62 = NULL;
    ui2_Container63 = NULL;
    ui2_Panel51 = NULL;
    ui2_Label101 = NULL;
    ui2_Container64 = NULL;
    ui2_Label102 = NULL;
    ui2_port3manufactuervid = NULL;
    ui2_Container65 = NULL;
    ui2_Label104 = NULL;
    ui2_port3cablevid = NULL;
    ui2_Container66 = NULL;
    ui2_Label106 = NULL;
    ui2_port3maxvbusvoltage = NULL;
    ui2_Container67 = NULL;
    ui2_Label108 = NULL;
    ui2_port3maxvbuscurrent = NULL;

}

void ui2_port3SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
