// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"

lv_obj_t * ui2_standbySCREEN = NULL;
lv_obj_t * ui2_Container2 = NULL;
lv_obj_t * ui2_Container3 = NULL;
lv_obj_t * ui2_Container85 = NULL;
lv_obj_t * ui2_timeLabel = NULL;
lv_obj_t * ui2_Container4 = NULL;
lv_obj_t * ui2_dataLabel = NULL;
lv_obj_t * ui2_Container5 = NULL;
lv_obj_t * ui2_temperatureLabel = NULL;
lv_obj_t * ui2_Label10 = NULL;
lv_obj_t * ui2_weatherLabel = NULL;
lv_obj_t * ui2_Container6 = NULL;
lv_obj_t * ui2_weekLabel = NULL;
lv_obj_t * ui2_Container7 = NULL;
lv_obj_t * ui2_Panel9 = NULL;
// event funtions
void ui2_event_standbySCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui2_totalpowerSCREEN_screen_init);
    }
}

// build funtions

void ui2_standbySCREEN_screen_init(void)
{
    ui2_standbySCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_standbySCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container2 = lv_obj_create(ui2_standbySCREEN);
    lv_obj_remove_style_all(ui2_Container2);
    lv_obj_set_width(ui2_Container2, lv_pct(100));
    lv_obj_set_height(ui2_Container2, lv_pct(100));
    lv_obj_set_align(ui2_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui2_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui2_Container2, &ui2_img_1985331572, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container3 = lv_obj_create(ui2_Container2);
    lv_obj_remove_style_all(ui2_Container3);
    lv_obj_set_width(ui2_Container3, lv_pct(100));
    lv_obj_set_height(ui2_Container3, lv_pct(6));
    lv_obj_set_x(ui2_Container3, -90);
    lv_obj_set_y(ui2_Container3, -106);
    lv_obj_set_align(ui2_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container85 = lv_obj_create(ui2_Container2);
    lv_obj_remove_style_all(ui2_Container85);
    lv_obj_set_width(ui2_Container85, lv_pct(100));
    lv_obj_set_height(ui2_Container85, 67);
    lv_obj_set_align(ui2_Container85, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container85, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container85, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container85, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_timeLabel = lv_label_create(ui2_Container85);
    lv_obj_set_width(ui2_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_timeLabel, -2);
    lv_obj_set_y(ui2_timeLabel, -129);
    lv_obj_set_align(ui2_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_timeLabel, "12:12:59");
    lv_obj_set_style_text_color(ui2_timeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_timeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_timeLabel, &ui2_font_ShuHei72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container4 = lv_obj_create(ui2_Container2);
    lv_obj_remove_style_all(ui2_Container4);
    lv_obj_set_width(ui2_Container4, 368);
    lv_obj_set_height(ui2_Container4, 52);
    lv_obj_set_x(ui2_Container4, -93);
    lv_obj_set_y(ui2_Container4, -7);
    lv_obj_set_align(ui2_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_dataLabel = lv_label_create(ui2_Container4);
    lv_obj_set_width(ui2_dataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_dataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_dataLabel, -105);
    lv_obj_set_y(ui2_dataLabel, -76);
    lv_obj_set_align(ui2_dataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_dataLabel, "07-11");
    lv_obj_set_style_text_color(ui2_dataLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_dataLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_dataLabel, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container5 = lv_obj_create(ui2_Container4);
    lv_obj_remove_style_all(ui2_Container5);
    lv_obj_set_width(ui2_Container5, 23);
    lv_obj_set_height(ui2_Container5, 23);
    lv_obj_set_x(ui2_Container5, -169);
    lv_obj_set_y(ui2_Container5, -65);
    lv_obj_set_align(ui2_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_temperatureLabel = lv_label_create(ui2_Container4);
    lv_obj_set_width(ui2_temperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_temperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_temperatureLabel, -24);
    lv_obj_set_y(ui2_temperatureLabel, -71);
    lv_obj_set_align(ui2_temperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_temperatureLabel, "32度");
    lv_obj_set_style_text_color(ui2_temperatureLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_temperatureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_temperatureLabel, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label10 = lv_label_create(ui2_Container4);
    lv_obj_set_width(ui2_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label10, 13);
    lv_obj_set_y(ui2_Label10, -69);
    lv_obj_set_align(ui2_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label10, "·");
    lv_obj_set_style_text_font(ui2_Label10, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_weatherLabel = lv_label_create(ui2_Container4);
    lv_obj_set_width(ui2_weatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_weatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_weatherLabel, 46);
    lv_obj_set_y(ui2_weatherLabel, -71);
    lv_obj_set_align(ui2_weatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_weatherLabel, "小雨");
    lv_obj_set_style_text_font(ui2_weatherLabel, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container6 = lv_obj_create(ui2_Container4);
    lv_obj_remove_style_all(ui2_Container6);
    lv_obj_set_width(ui2_Container6, 23);
    lv_obj_set_height(ui2_Container6, 23);
    lv_obj_set_x(ui2_Container6, -20);
    lv_obj_set_y(ui2_Container6, -14);
    lv_obj_set_align(ui2_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_weekLabel = lv_label_create(ui2_Container4);
    lv_obj_set_width(ui2_weekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_weekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_weekLabel, 125);
    lv_obj_set_y(ui2_weekLabel, -76);
    lv_obj_set_align(ui2_weekLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_weekLabel, "星期日");
    lv_obj_set_style_text_font(ui2_weekLabel, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container7 = lv_obj_create(ui2_Container2);
    lv_obj_remove_style_all(ui2_Container7);
    lv_obj_set_width(ui2_Container7, 292);
    lv_obj_set_height(ui2_Container7, 265);
    lv_obj_set_x(ui2_Container7, 1);
    lv_obj_set_y(ui2_Container7, 9);
    lv_obj_set_align(ui2_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel9 = lv_obj_create(ui2_Container2);
    lv_obj_set_width(ui2_Panel9, 168);
    lv_obj_set_height(ui2_Panel9, 8);
    lv_obj_set_x(ui2_Panel9, -8);
    lv_obj_set_y(ui2_Panel9, 162);
    lv_obj_set_align(ui2_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel9, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui2_standbySCREEN, ui2_event_standbySCREEN, LV_EVENT_ALL, NULL);

}

void ui2_standbySCREEN_screen_destroy(void)
{
    if(ui2_standbySCREEN) lv_obj_del(ui2_standbySCREEN);

    // NULL screen variables
    ui2_standbySCREEN = NULL;
    ui2_Container2 = NULL;
    ui2_Container3 = NULL;
    ui2_timeLabel = NULL;
    ui2_Container4 = NULL;
    ui2_dataLabel = NULL;
    ui2_Container5 = NULL;
    ui2_temperatureLabel = NULL;
    ui2_Label10 = NULL;
    ui2_weatherLabel = NULL;
    ui2_Container6 = NULL;
    ui2_weekLabel = NULL;
    ui2_Container7 = NULL;
    ui2_Panel9 = NULL;

}

void ui2_standbySCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
