// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui2_PORT3SCREEN_H
#define ui2_PORT3SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui2_port3SCREEN
extern void ui2_port3SCREEN_screen_init(void);
extern void ui2_port3SCREEN_screen_destroy(void);
extern void ui2_port3SCREEN_screen_relocalize(void);
extern void ui2_event_port3SCREEN(lv_event_t * e);
extern lv_obj_t * ui2_port3SCREEN;
extern lv_obj_t * ui2_Container51;
extern lv_obj_t * ui2_Panel42;
extern lv_obj_t * ui2_Label84;
extern lv_obj_t * ui2_Container52;
extern lv_obj_t * ui2_Panel43;
extern lv_obj_t * ui2_Panel44;
extern lv_obj_t * ui2_Label85;
extern lv_obj_t * ui2_port3voltage1;
extern lv_obj_t * ui2_Container53;
extern lv_obj_t * ui2_Panel45;
extern lv_obj_t * ui2_Panel46;
extern lv_obj_t * ui2_Label87;
extern lv_obj_t * ui2_port3current1;
extern lv_obj_t * ui2_Container54;
extern lv_obj_t * ui2_Panel47;
extern lv_obj_t * ui2_Panel48;
extern lv_obj_t * ui2_Label89;
extern lv_obj_t * ui2_port3powerlabel1;
extern lv_obj_t * ui2_Container55;
extern lv_obj_t * ui2_Panel49;
extern lv_obj_t * ui2_Label91;
extern lv_obj_t * ui2_Container56;
extern lv_obj_t * ui2_port3powerlabel;
extern lv_obj_t * ui2_Container57;
extern lv_obj_t * ui2_port3state;
extern lv_obj_t * ui2_Container58;
extern lv_obj_t * ui2_Panel50;
extern lv_obj_t * ui2_Label94;
extern lv_obj_t * ui2_Container59;
extern lv_obj_t * ui2_Label95;
extern lv_obj_t * ui2_port3protocol;
extern lv_obj_t * ui2_Container60;
extern lv_obj_t * ui2_Label97;
extern lv_obj_t * ui2_port3revision;
extern lv_obj_t * ui2_Container61;
extern lv_obj_t * ui2_Label99;
extern lv_obj_t * ui2_port3protocolpower;
extern lv_obj_t * ui2_Container62;
extern lv_obj_t * ui2_Container63;
extern lv_obj_t * ui2_Panel51;
extern lv_obj_t * ui2_Label101;
extern lv_obj_t * ui2_Container64;
extern lv_obj_t * ui2_Label102;
extern lv_obj_t * ui2_port3manufactuervid;
extern lv_obj_t * ui2_Container65;
extern lv_obj_t * ui2_Label104;
extern lv_obj_t * ui2_port3cablevid;
extern lv_obj_t * ui2_Container66;
extern lv_obj_t * ui2_Label106;
extern lv_obj_t * ui2_port3maxvbusvoltage;
extern lv_obj_t * ui2_Container67;
extern lv_obj_t * ui2_Label108;
extern lv_obj_t * ui2_port3maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

