// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"

lv_obj_t * ui2_port1SCREEN = NULL;
lv_obj_t * ui2_Container16 = NULL;
lv_obj_t * ui2_Panel22 = NULL;
lv_obj_t * ui2_Label32 = NULL;
lv_obj_t * ui2_Container19 = NULL;
lv_obj_t * ui2_Panel26 = NULL;
lv_obj_t * ui2_Panel23 = NULL;
lv_obj_t * ui2_Label33 = NULL;
lv_obj_t * ui2_port1current2 = NULL;
lv_obj_t * ui2_Container24 = NULL;
lv_obj_t * ui2_Panel27 = NULL;
lv_obj_t * ui2_Panel24 = NULL;
lv_obj_t * ui2_Label34 = NULL;
lv_obj_t * ui2_port1current1 = NULL;
lv_obj_t * ui2_Container22 = NULL;
lv_obj_t * ui2_Panel28 = NULL;
lv_obj_t * ui2_Panel25 = NULL;
lv_obj_t * ui2_Label35 = NULL;
lv_obj_t * ui2_port1powerlabel = NULL;
lv_obj_t * ui2_Container21 = NULL;
lv_obj_t * ui2_Panel31 = NULL;
lv_obj_t * ui2_Label41 = NULL;
lv_obj_t * ui2_Container32 = NULL;
lv_obj_t * ui2_port1active = NULL;
lv_obj_t * ui2_Container33 = NULL;
lv_obj_t * ui2_port1state = NULL;
lv_obj_t * ui2_Container18 = NULL;
lv_obj_t * ui2_Panel29 = NULL;
lv_obj_t * ui2_Label39 = NULL;
lv_obj_t * ui2_Container25 = NULL;
lv_obj_t * ui2_Label46 = NULL;
lv_obj_t * ui2_port1protocol = NULL;
lv_obj_t * ui2_Container26 = NULL;
lv_obj_t * ui2_Label47 = NULL;
lv_obj_t * ui2_port1revision = NULL;
lv_obj_t * ui2_Container27 = NULL;
lv_obj_t * ui2_Label48 = NULL;
lv_obj_t * ui2_port1protocolpower = NULL;
lv_obj_t * ui2_Container23 = NULL;
lv_obj_t * ui2_Container20 = NULL;
lv_obj_t * ui2_Panel30 = NULL;
lv_obj_t * ui2_Label40 = NULL;
lv_obj_t * ui2_Container28 = NULL;
lv_obj_t * ui2_Label44 = NULL;
lv_obj_t * ui2_port1manufactuervid = NULL;
lv_obj_t * ui2_Container29 = NULL;
lv_obj_t * ui2_Label58 = NULL;
lv_obj_t * ui2_port1cablevid = NULL;
lv_obj_t * ui2_Container30 = NULL;
lv_obj_t * ui2_Label60 = NULL;
lv_obj_t * ui2_port1maxvbusvoltage = NULL;
lv_obj_t * ui2_Container31 = NULL;
lv_obj_t * ui2_Label62 = NULL;
lv_obj_t * ui2_port1maxvbuscurrent = NULL;
// event funtions
void ui2_event_port1SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_totalpowerSCREEN, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui2_totalpowerSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port2SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui2_port2SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui2_totalpowerSCREEN_screen_init);
    }
}

// build funtions

void ui2_port1SCREEN_screen_init(void)
{
    ui2_port1SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_port1SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container16 = lv_obj_create(ui2_port1SCREEN);
    lv_obj_remove_style_all(ui2_Container16);
    lv_obj_set_width(ui2_Container16, lv_pct(100));
    lv_obj_set_height(ui2_Container16, lv_pct(100));
    lv_obj_set_align(ui2_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container16, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container16, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel22 = lv_obj_create(ui2_Container16);
    lv_obj_set_width(ui2_Panel22, 368);
    lv_obj_set_height(ui2_Panel22, 49);
    lv_obj_set_align(ui2_Panel22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel22, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel22, lv_color_hex(0xEEAE08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label32 = lv_label_create(ui2_Panel22);
    lv_obj_set_width(ui2_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label32, -34);
    lv_obj_set_y(ui2_Label32, -201);
    lv_obj_set_align(ui2_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label32, "C1 PORT");
    lv_obj_set_style_text_color(ui2_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label32, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container19 = lv_obj_create(ui2_Container16);
    lv_obj_remove_style_all(ui2_Container19);
    lv_obj_set_width(ui2_Container19, 246);
    lv_obj_set_height(ui2_Container19, 168);
    lv_obj_set_x(ui2_Container19, -36);
    lv_obj_set_y(ui2_Container19, -72);
    lv_obj_set_align(ui2_Container19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container19, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel26 = lv_obj_create(ui2_Container19);
    lv_obj_set_width(ui2_Panel26, 240);
    lv_obj_set_height(ui2_Panel26, 50);
    lv_obj_set_x(ui2_Panel26, -24);
    lv_obj_set_y(ui2_Panel26, -115);
    lv_obj_set_align(ui2_Panel26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel26, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel23 = lv_obj_create(ui2_Panel26);
    lv_obj_set_width(ui2_Panel23, 40);
    lv_obj_set_height(ui2_Panel23, 40);
    lv_obj_set_x(ui2_Panel23, -127);
    lv_obj_set_y(ui2_Panel23, -131);
    lv_obj_set_align(ui2_Panel23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel23, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel23, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel23, lv_color_hex(0xEEAE08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel23, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label33 = lv_label_create(ui2_Panel23);
    lv_obj_set_width(ui2_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label33, -70);
    lv_obj_set_y(ui2_Label33, -94);
    lv_obj_set_align(ui2_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label33, "U");
    lv_obj_set_style_text_color(ui2_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label33, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1current2 = lv_label_create(ui2_Panel26);
    lv_obj_set_width(ui2_port1current2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1current2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1current2, -7);
    lv_obj_set_y(ui2_port1current2, -131);
    lv_obj_set_align(ui2_port1current2, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1current2, "27.842V");
    lv_obj_set_style_text_color(ui2_port1current2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port1current2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port1current2, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container24 = lv_obj_create(ui2_Container19);
    lv_obj_remove_style_all(ui2_Container24);
    lv_obj_set_width(ui2_Container24, 243);
    lv_obj_set_height(ui2_Container24, 3);
    lv_obj_set_align(ui2_Container24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel27 = lv_obj_create(ui2_Container19);
    lv_obj_set_width(ui2_Panel27, 240);
    lv_obj_set_height(ui2_Panel27, 50);
    lv_obj_set_x(ui2_Panel27, -19);
    lv_obj_set_y(ui2_Panel27, -57);
    lv_obj_set_align(ui2_Panel27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel27, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel24 = lv_obj_create(ui2_Panel27);
    lv_obj_set_width(ui2_Panel24, 40);
    lv_obj_set_height(ui2_Panel24, 40);
    lv_obj_set_x(ui2_Panel24, -131);
    lv_obj_set_y(ui2_Panel24, -78);
    lv_obj_set_align(ui2_Panel24, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel24, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel24, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel24, lv_color_hex(0xEEAE08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel24, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label34 = lv_label_create(ui2_Panel24);
    lv_obj_set_width(ui2_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label34, -82);
    lv_obj_set_y(ui2_Label34, -38);
    lv_obj_set_align(ui2_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label34, "I");
    lv_obj_set_style_text_color(ui2_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label34, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1current1 = lv_label_create(ui2_Panel27);
    lv_obj_set_width(ui2_port1current1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1current1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1current1, -16);
    lv_obj_set_y(ui2_port1current1, -78);
    lv_obj_set_align(ui2_port1current1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1current1, "3.564A");
    lv_obj_set_style_text_color(ui2_port1current1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port1current1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port1current1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container22 = lv_obj_create(ui2_Container19);
    lv_obj_remove_style_all(ui2_Container22);
    lv_obj_set_width(ui2_Container22, 243);
    lv_obj_set_height(ui2_Container22, 3);
    lv_obj_set_align(ui2_Container22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel28 = lv_obj_create(ui2_Container19);
    lv_obj_set_width(ui2_Panel28, 240);
    lv_obj_set_height(ui2_Panel28, 50);
    lv_obj_set_x(ui2_Panel28, -16);
    lv_obj_set_y(ui2_Panel28, 2);
    lv_obj_set_align(ui2_Panel28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel28, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel25 = lv_obj_create(ui2_Panel28);
    lv_obj_set_width(ui2_Panel25, 40);
    lv_obj_set_height(ui2_Panel25, 40);
    lv_obj_set_x(ui2_Panel25, -131);
    lv_obj_set_y(ui2_Panel25, -25);
    lv_obj_set_align(ui2_Panel25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel25, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel25, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel25, lv_color_hex(0xEEAE08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel25, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label35 = lv_label_create(ui2_Panel25);
    lv_obj_set_width(ui2_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label35, -67);
    lv_obj_set_y(ui2_Label35, 26);
    lv_obj_set_align(ui2_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label35, "P");
    lv_obj_set_style_text_color(ui2_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label35, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1powerlabel = lv_label_create(ui2_Panel28);
    lv_obj_set_width(ui2_port1powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1powerlabel, -15);
    lv_obj_set_y(ui2_port1powerlabel, -28);
    lv_obj_set_align(ui2_port1powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1powerlabel, "30.658W");
    lv_obj_set_style_text_color(ui2_port1powerlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port1powerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port1powerlabel, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container21 = lv_obj_create(ui2_Container16);
    lv_obj_remove_style_all(ui2_Container21);
    lv_obj_set_height(ui2_Container21, 155);
    lv_obj_set_width(ui2_Container21, lv_pct(32));
    lv_obj_set_x(ui2_Container21, 119);
    lv_obj_set_y(ui2_Container21, -26);
    lv_obj_set_align(ui2_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container21, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container21, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container21, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container21, lv_color_hex(0x07595D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container21, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel31 = lv_obj_create(ui2_Container21);
    lv_obj_set_width(ui2_Panel31, lv_pct(100));
    lv_obj_set_height(ui2_Panel31, lv_pct(24));
    lv_obj_set_x(ui2_Panel31, 121);
    lv_obj_set_y(ui2_Panel31, -77);
    lv_obj_set_align(ui2_Panel31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel31, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel31, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel31, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel31, lv_color_hex(0x095C62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel31, lv_color_hex(0x07585A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label41 = lv_label_create(ui2_Panel31);
    lv_obj_set_width(ui2_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label41, "STATE");
    lv_obj_set_style_text_font(ui2_Label41, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container32 = lv_obj_create(ui2_Container21);
    lv_obj_remove_style_all(ui2_Container32);
    lv_obj_set_width(ui2_Container32, 100);
    lv_obj_set_height(ui2_Container32, 18);
    lv_obj_set_align(ui2_Container32, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port1active = lv_label_create(ui2_Container21);
    lv_obj_set_width(ui2_port1active, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1active, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1active, 122);
    lv_obj_set_y(ui2_port1active, -61);
    lv_obj_set_align(ui2_port1active, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1active, "已开启");
    lv_obj_set_style_text_font(ui2_port1active, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container33 = lv_obj_create(ui2_Container21);
    lv_obj_remove_style_all(ui2_Container33);
    lv_obj_set_width(ui2_Container33, 100);
    lv_obj_set_height(ui2_Container33, 16);
    lv_obj_set_align(ui2_Container33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port1state = lv_label_create(ui2_Container21);
    lv_obj_set_width(ui2_port1state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1state, 120);
    lv_obj_set_y(ui2_port1state, -8);
    lv_obj_set_align(ui2_port1state, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1state, "已连接");
    lv_obj_set_style_text_font(ui2_port1state, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container18 = lv_obj_create(ui2_Container16);
    lv_obj_remove_style_all(ui2_Container18);
    lv_obj_set_width(ui2_Container18, 180);
    lv_obj_set_height(ui2_Container18, 151);
    lv_obj_set_x(ui2_Container18, 93);
    lv_obj_set_y(ui2_Container18, 102);
    lv_obj_set_align(ui2_Container18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container18, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container18, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container18, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container18, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container18, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel29 = lv_obj_create(ui2_Container18);
    lv_obj_set_width(ui2_Panel29, lv_pct(100));
    lv_obj_set_height(ui2_Panel29, lv_pct(24));
    lv_obj_set_x(ui2_Panel29, 64);
    lv_obj_set_y(ui2_Panel29, 58);
    lv_obj_set_align(ui2_Panel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel29, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel29, lv_color_hex(0xBA7408), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel29, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label39 = lv_label_create(ui2_Panel29);
    lv_obj_set_width(ui2_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label39, "PROTOCOL");
    lv_obj_set_style_text_font(ui2_Label39, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container25 = lv_obj_create(ui2_Container18);
    lv_obj_remove_style_all(ui2_Container25);
    lv_obj_set_width(ui2_Container25, lv_pct(70));
    lv_obj_set_height(ui2_Container25, lv_pct(25));
    lv_obj_set_x(ui2_Container25, -3);
    lv_obj_set_y(ui2_Container25, 56);
    lv_obj_set_align(ui2_Container25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container25, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container25, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label46 = lv_label_create(ui2_Container25);
    lv_obj_set_width(ui2_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label46, -142);
    lv_obj_set_y(ui2_Label46, 94);
    lv_obj_set_align(ui2_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label46, "协议：");
    lv_obj_set_style_text_font(ui2_Label46, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1protocol = lv_label_create(ui2_Container25);
    lv_obj_set_width(ui2_port1protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1protocol, -94);
    lv_obj_set_y(ui2_port1protocol, 91);
    lv_obj_set_align(ui2_port1protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1protocol, "PD");
    lv_obj_set_style_text_font(ui2_port1protocol, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container26 = lv_obj_create(ui2_Container18);
    lv_obj_remove_style_all(ui2_Container26);
    lv_obj_set_width(ui2_Container26, lv_pct(70));
    lv_obj_set_height(ui2_Container26, lv_pct(22));
    lv_obj_set_x(ui2_Container26, -3);
    lv_obj_set_y(ui2_Container26, 56);
    lv_obj_set_align(ui2_Container26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container26, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label47 = lv_label_create(ui2_Container26);
    lv_obj_set_width(ui2_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label47, -141);
    lv_obj_set_y(ui2_Label47, 120);
    lv_obj_set_align(ui2_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label47, "版本：");
    lv_obj_set_style_text_font(ui2_Label47, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1revision = lv_label_create(ui2_Container26);
    lv_obj_set_width(ui2_port1revision, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1revision, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1revision, -93);
    lv_obj_set_y(ui2_port1revision, 120);
    lv_obj_set_align(ui2_port1revision, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1revision, "3.0");
    lv_obj_set_style_text_font(ui2_port1revision, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container27 = lv_obj_create(ui2_Container18);
    lv_obj_remove_style_all(ui2_Container27);
    lv_obj_set_width(ui2_Container27, lv_pct(70));
    lv_obj_set_height(ui2_Container27, lv_pct(22));
    lv_obj_set_x(ui2_Container27, -3);
    lv_obj_set_y(ui2_Container27, 56);
    lv_obj_set_align(ui2_Container27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container27, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label48 = lv_label_create(ui2_Container27);
    lv_obj_set_width(ui2_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label48, -141);
    lv_obj_set_y(ui2_Label48, 147);
    lv_obj_set_align(ui2_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label48, "功率：");
    lv_obj_set_style_text_font(ui2_Label48, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1protocolpower = lv_label_create(ui2_Container27);
    lv_obj_set_width(ui2_port1protocolpower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1protocolpower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1protocolpower, -86);
    lv_obj_set_y(ui2_port1protocolpower, 145);
    lv_obj_set_align(ui2_port1protocolpower, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1protocolpower, "100W");
    lv_obj_set_style_text_font(ui2_port1protocolpower, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container23 = lv_obj_create(ui2_Container16);
    lv_obj_remove_style_all(ui2_Container23);
    lv_obj_set_width(ui2_Container23, 5);
    lv_obj_set_height(ui2_Container23, 136);
    lv_obj_set_align(ui2_Container23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container20 = lv_obj_create(ui2_Container16);
    lv_obj_remove_style_all(ui2_Container20);
    lv_obj_set_width(ui2_Container20, 180);
    lv_obj_set_height(ui2_Container20, 151);
    lv_obj_set_x(ui2_Container20, -89);
    lv_obj_set_y(ui2_Container20, 102);
    lv_obj_set_align(ui2_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container20, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container20, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container20, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container20, lv_color_hex(0xF12B8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container20, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel30 = lv_obj_create(ui2_Container20);
    lv_obj_set_width(ui2_Panel30, lv_pct(100));
    lv_obj_set_height(ui2_Panel30, lv_pct(24));
    lv_obj_set_x(ui2_Panel30, -78);
    lv_obj_set_y(ui2_Panel30, 72);
    lv_obj_set_align(ui2_Panel30, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel30, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel30, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel30, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel30, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel30, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label40 = lv_label_create(ui2_Panel30);
    lv_obj_set_width(ui2_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label40, -116);
    lv_obj_set_y(ui2_Label40, 71);
    lv_obj_set_align(ui2_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label40, "WIRE ROD");
    lv_obj_set_style_text_font(ui2_Label40, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container28 = lv_obj_create(ui2_Container20);
    lv_obj_remove_style_all(ui2_Container28);
    lv_obj_set_width(ui2_Container28, lv_pct(75));
    lv_obj_set_height(ui2_Container28, lv_pct(20));
    lv_obj_set_x(ui2_Container28, 82);
    lv_obj_set_y(ui2_Container28, 89);
    lv_obj_set_align(ui2_Container28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container28, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label44 = lv_label_create(ui2_Container28);
    lv_obj_set_width(ui2_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label44, 50);
    lv_obj_set_y(ui2_Label44, 92);
    lv_obj_set_align(ui2_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label44, "制造商：");
    lv_obj_set_style_text_font(ui2_Label44, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1manufactuervid = lv_label_create(ui2_Container28);
    lv_obj_set_width(ui2_port1manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1manufactuervid, 110);
    lv_obj_set_y(ui2_port1manufactuervid, 89);
    lv_obj_set_align(ui2_port1manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1manufactuervid, "小米");
    lv_obj_set_style_text_font(ui2_port1manufactuervid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container29 = lv_obj_create(ui2_Container20);
    lv_obj_remove_style_all(ui2_Container29);
    lv_obj_set_width(ui2_Container29, lv_pct(75));
    lv_obj_set_height(ui2_Container29, lv_pct(17));
    lv_obj_set_x(ui2_Container29, 82);
    lv_obj_set_y(ui2_Container29, 89);
    lv_obj_set_align(ui2_Container29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container29, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container29, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label58 = lv_label_create(ui2_Container29);
    lv_obj_set_width(ui2_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label58, 50);
    lv_obj_set_y(ui2_Label58, 92);
    lv_obj_set_align(ui2_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label58, "线缆厂商：");
    lv_obj_set_style_text_font(ui2_Label58, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1cablevid = lv_label_create(ui2_Container29);
    lv_obj_set_width(ui2_port1cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1cablevid, 110);
    lv_obj_set_y(ui2_port1cablevid, 89);
    lv_obj_set_align(ui2_port1cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1cablevid, "酷态科");
    lv_obj_set_style_text_font(ui2_port1cablevid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container30 = lv_obj_create(ui2_Container20);
    lv_obj_remove_style_all(ui2_Container30);
    lv_obj_set_width(ui2_Container30, lv_pct(75));
    lv_obj_set_height(ui2_Container30, lv_pct(17));
    lv_obj_set_x(ui2_Container30, 82);
    lv_obj_set_y(ui2_Container30, 89);
    lv_obj_set_align(ui2_Container30, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container30, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container30, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label60 = lv_label_create(ui2_Container30);
    lv_obj_set_width(ui2_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label60, 50);
    lv_obj_set_y(ui2_Label60, 92);
    lv_obj_set_align(ui2_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label60, "最大电压：");
    lv_obj_set_style_text_font(ui2_Label60, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1maxvbusvoltage = lv_label_create(ui2_Container30);
    lv_obj_set_width(ui2_port1maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1maxvbusvoltage, 110);
    lv_obj_set_y(ui2_port1maxvbusvoltage, 89);
    lv_obj_set_align(ui2_port1maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1maxvbusvoltage, "20V");
    lv_obj_set_style_text_font(ui2_port1maxvbusvoltage, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container31 = lv_obj_create(ui2_Container20);
    lv_obj_remove_style_all(ui2_Container31);
    lv_obj_set_width(ui2_Container31, lv_pct(75));
    lv_obj_set_height(ui2_Container31, lv_pct(17));
    lv_obj_set_x(ui2_Container31, 82);
    lv_obj_set_y(ui2_Container31, 89);
    lv_obj_set_align(ui2_Container31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container31, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container31, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label62 = lv_label_create(ui2_Container31);
    lv_obj_set_width(ui2_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label62, 50);
    lv_obj_set_y(ui2_Label62, 92);
    lv_obj_set_align(ui2_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label62, "最大电流：");
    lv_obj_set_style_text_font(ui2_Label62, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1maxvbuscurrent = lv_label_create(ui2_Container31);
    lv_obj_set_width(ui2_port1maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1maxvbuscurrent, 110);
    lv_obj_set_y(ui2_port1maxvbuscurrent, 89);
    lv_obj_set_align(ui2_port1maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1maxvbuscurrent, "5A");
    lv_obj_set_style_text_font(ui2_port1maxvbuscurrent, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui2_port1SCREEN, ui2_event_port1SCREEN, LV_EVENT_ALL, NULL);

}

void ui2_port1SCREEN_screen_destroy(void)
{
    if(ui2_port1SCREEN) lv_obj_del(ui2_port1SCREEN);

    // NULL screen variables
    ui2_port1SCREEN = NULL;
    ui2_Container16 = NULL;
    ui2_Panel22 = NULL;
    ui2_Label32 = NULL;
    ui2_Container19 = NULL;
    ui2_Panel26 = NULL;
    ui2_Panel23 = NULL;
    ui2_Label33 = NULL;
    ui2_port1current2 = NULL;
    ui2_Container24 = NULL;
    ui2_Panel27 = NULL;
    ui2_Panel24 = NULL;
    ui2_Label34 = NULL;
    ui2_port1current1 = NULL;
    ui2_Container22 = NULL;
    ui2_Panel28 = NULL;
    ui2_Panel25 = NULL;
    ui2_Label35 = NULL;
    ui2_port1powerlabel = NULL;
    ui2_Container21 = NULL;
    ui2_Panel31 = NULL;
    ui2_Label41 = NULL;
    ui2_Container32 = NULL;
    ui2_port1active = NULL;
    ui2_Container33 = NULL;
    ui2_port1state = NULL;
    ui2_Container18 = NULL;
    ui2_Panel29 = NULL;
    ui2_Label39 = NULL;
    ui2_Container25 = NULL;
    ui2_Label46 = NULL;
    ui2_port1protocol = NULL;
    ui2_Container26 = NULL;
    ui2_Label47 = NULL;
    ui2_port1revision = NULL;
    ui2_Container27 = NULL;
    ui2_Label48 = NULL;
    ui2_port1protocolpower = NULL;
    ui2_Container23 = NULL;
    ui2_Container20 = NULL;
    ui2_Panel30 = NULL;
    ui2_Label40 = NULL;
    ui2_Container28 = NULL;
    ui2_Label44 = NULL;
    ui2_port1manufactuervid = NULL;
    ui2_Container29 = NULL;
    ui2_Label58 = NULL;
    ui2_port1cablevid = NULL;
    ui2_Container30 = NULL;
    ui2_Label60 = NULL;
    ui2_port1maxvbusvoltage = NULL;
    ui2_Container31 = NULL;
    ui2_Label62 = NULL;
    ui2_port1maxvbuscurrent = NULL;

}

void ui2_port1SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
