// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui2_PORT4SCREEN_H
#define ui2_PORT4SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui2_port4SCREEN
extern void ui2_port4SCREEN_screen_init(void);
extern void ui2_port4SCREEN_screen_destroy(void);
extern void ui2_port4SCREEN_screen_relocalize(void);
extern void ui2_event_port4SCREEN(lv_event_t * e);
extern lv_obj_t * ui2_port4SCREEN;
extern lv_obj_t * ui2_Container68;
extern lv_obj_t * ui2_Panel52;
extern lv_obj_t * ui2_Label110;
extern lv_obj_t * ui2_Container69;
extern lv_obj_t * ui2_Panel53;
extern lv_obj_t * ui2_Panel54;
extern lv_obj_t * ui2_Label111;
extern lv_obj_t * ui2_port4voltage1;
extern lv_obj_t * ui2_Container70;
extern lv_obj_t * ui2_Panel55;
extern lv_obj_t * ui2_Panel56;
extern lv_obj_t * ui2_Label113;
extern lv_obj_t * ui2_port4current1;
extern lv_obj_t * ui2_Container71;
extern lv_obj_t * ui2_Panel57;
extern lv_obj_t * ui2_Panel58;
extern lv_obj_t * ui2_Label115;
extern lv_obj_t * ui2_port4powerlabel1;
extern lv_obj_t * ui2_Container72;
extern lv_obj_t * ui2_Panel59;
extern lv_obj_t * ui2_Label117;
extern lv_obj_t * ui2_Container73;
extern lv_obj_t * ui2_port4powerlabel;
extern lv_obj_t * ui2_Container74;
extern lv_obj_t * ui2_port4state;
extern lv_obj_t * ui2_Container75;
extern lv_obj_t * ui2_Panel60;
extern lv_obj_t * ui2_Label120;
extern lv_obj_t * ui2_Container76;
extern lv_obj_t * ui2_Label121;
extern lv_obj_t * ui2_port4protocol;
extern lv_obj_t * ui2_Container77;
extern lv_obj_t * ui2_Label123;
extern lv_obj_t * ui2_port4revision;
extern lv_obj_t * ui2_Container78;
extern lv_obj_t * ui2_Label125;
extern lv_obj_t * ui2_port4protocolpower;
extern lv_obj_t * ui2_Container79;
extern lv_obj_t * ui2_Container80;
extern lv_obj_t * ui2_Panel61;
extern lv_obj_t * ui2_Label127;
extern lv_obj_t * ui2_Container81;
extern lv_obj_t * ui2_Label128;
extern lv_obj_t * ui2_port4manufactuervid;
extern lv_obj_t * ui2_Container82;
extern lv_obj_t * ui2_Label130;
extern lv_obj_t * ui2_port4cablevid;
extern lv_obj_t * ui2_Container83;
extern lv_obj_t * ui2_Label132;
extern lv_obj_t * ui2_port4maxvbusvoltage;
extern lv_obj_t * ui2_Container84;
extern lv_obj_t * ui2_Label134;
extern lv_obj_t * ui2_port4maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

