// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"

lv_obj_t * ui2_port2SCREEN = NULL;
lv_obj_t * ui2_Container34 = NULL;
lv_obj_t * ui2_Panel32 = NULL;
lv_obj_t * ui2_Label45 = NULL;
lv_obj_t * ui2_Container35 = NULL;
lv_obj_t * ui2_Panel33 = NULL;
lv_obj_t * ui2_Panel34 = NULL;
lv_obj_t * ui2_Label49 = NULL;
lv_obj_t * ui2_port2voltage1 = NULL;
lv_obj_t * ui2_Container36 = NULL;
lv_obj_t * ui2_Panel35 = NULL;
lv_obj_t * ui2_Panel36 = NULL;
lv_obj_t * ui2_Label51 = NULL;
lv_obj_t * ui2_port2current1 = NULL;
lv_obj_t * ui2_Container37 = NULL;
lv_obj_t * ui2_Panel37 = NULL;
lv_obj_t * ui2_Panel38 = NULL;
lv_obj_t * ui2_Label53 = NULL;
lv_obj_t * ui2_port2powerlabel1 = NULL;
lv_obj_t * ui2_Container38 = NULL;
lv_obj_t * ui2_Panel39 = NULL;
lv_obj_t * ui2_Label65 = NULL;
lv_obj_t * ui2_Container39 = NULL;
lv_obj_t * ui2_port2powerlabel = NULL;
lv_obj_t * ui2_Container40 = NULL;
lv_obj_t * ui2_port2state = NULL;
lv_obj_t * ui2_Container41 = NULL;
lv_obj_t * ui2_Panel40 = NULL;
lv_obj_t * ui2_Label68 = NULL;
lv_obj_t * ui2_Container42 = NULL;
lv_obj_t * ui2_Label69 = NULL;
lv_obj_t * ui2_port2protocol = NULL;
lv_obj_t * ui2_Container43 = NULL;
lv_obj_t * ui2_Label71 = NULL;
lv_obj_t * ui2_port2revision = NULL;
lv_obj_t * ui2_Container44 = NULL;
lv_obj_t * ui2_Label73 = NULL;
lv_obj_t * ui2_port2protocolpower = NULL;
lv_obj_t * ui2_Container45 = NULL;
lv_obj_t * ui2_Container46 = NULL;
lv_obj_t * ui2_Panel41 = NULL;
lv_obj_t * ui2_Label75 = NULL;
lv_obj_t * ui2_Container47 = NULL;
lv_obj_t * ui2_Label76 = NULL;
lv_obj_t * ui2_port2manufactuervid = NULL;
lv_obj_t * ui2_Container48 = NULL;
lv_obj_t * ui2_Label78 = NULL;
lv_obj_t * ui2_port2cablevid = NULL;
lv_obj_t * ui2_Container49 = NULL;
lv_obj_t * ui2_Label80 = NULL;
lv_obj_t * ui2_port2maxvbusvoltage = NULL;
lv_obj_t * ui2_Container50 = NULL;
lv_obj_t * ui2_Label82 = NULL;
lv_obj_t * ui2_port2maxvbuscurrent = NULL;
// event funtions
void ui2_event_port2SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_totalpowerSCREEN, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui2_totalpowerSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port1SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui2_port1SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port3SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui2_port3SCREEN_screen_init);
    }
}

// build funtions

void ui2_port2SCREEN_screen_init(void)
{
    ui2_port2SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_port2SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container34 = lv_obj_create(ui2_port2SCREEN);
    lv_obj_remove_style_all(ui2_Container34);
    lv_obj_set_width(ui2_Container34, lv_pct(100));
    lv_obj_set_height(ui2_Container34, lv_pct(100));
    lv_obj_set_align(ui2_Container34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container34, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container34, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel32 = lv_obj_create(ui2_Container34);
    lv_obj_set_width(ui2_Panel32, 368);
    lv_obj_set_height(ui2_Panel32, 49);
    lv_obj_set_align(ui2_Panel32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel32, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel32, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel32, lv_color_hex(0xEE1420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label45 = lv_label_create(ui2_Panel32);
    lv_obj_set_width(ui2_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label45, -34);
    lv_obj_set_y(ui2_Label45, -201);
    lv_obj_set_align(ui2_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label45, "C2 PORT");
    lv_obj_set_style_text_color(ui2_Label45, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label45, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container35 = lv_obj_create(ui2_Container34);
    lv_obj_remove_style_all(ui2_Container35);
    lv_obj_set_width(ui2_Container35, 246);
    lv_obj_set_height(ui2_Container35, 168);
    lv_obj_set_x(ui2_Container35, -36);
    lv_obj_set_y(ui2_Container35, -72);
    lv_obj_set_align(ui2_Container35, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container35, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container35, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container35, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel33 = lv_obj_create(ui2_Container35);
    lv_obj_set_width(ui2_Panel33, 240);
    lv_obj_set_height(ui2_Panel33, 50);
    lv_obj_set_x(ui2_Panel33, -24);
    lv_obj_set_y(ui2_Panel33, -115);
    lv_obj_set_align(ui2_Panel33, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel33, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel33, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel34 = lv_obj_create(ui2_Panel33);
    lv_obj_set_width(ui2_Panel34, 40);
    lv_obj_set_height(ui2_Panel34, 40);
    lv_obj_set_x(ui2_Panel34, -127);
    lv_obj_set_y(ui2_Panel34, -131);
    lv_obj_set_align(ui2_Panel34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel34, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel34, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel34, lv_color_hex(0xEE1420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel34, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label49 = lv_label_create(ui2_Panel34);
    lv_obj_set_width(ui2_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label49, -70);
    lv_obj_set_y(ui2_Label49, -94);
    lv_obj_set_align(ui2_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label49, "U");
    lv_obj_set_style_text_color(ui2_Label49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label49, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2voltage1 = lv_label_create(ui2_Panel33);
    lv_obj_set_width(ui2_port2voltage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2voltage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2voltage1, -7);
    lv_obj_set_y(ui2_port2voltage1, -131);
    lv_obj_set_align(ui2_port2voltage1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2voltage1, "27.842V");
    lv_obj_set_style_text_color(ui2_port2voltage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port2voltage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port2voltage1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container36 = lv_obj_create(ui2_Container35);
    lv_obj_remove_style_all(ui2_Container36);
    lv_obj_set_width(ui2_Container36, 243);
    lv_obj_set_height(ui2_Container36, 3);
    lv_obj_set_align(ui2_Container36, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel35 = lv_obj_create(ui2_Container35);
    lv_obj_set_width(ui2_Panel35, 240);
    lv_obj_set_height(ui2_Panel35, 50);
    lv_obj_set_x(ui2_Panel35, -19);
    lv_obj_set_y(ui2_Panel35, -57);
    lv_obj_set_align(ui2_Panel35, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel35, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel35, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel36 = lv_obj_create(ui2_Panel35);
    lv_obj_set_width(ui2_Panel36, 40);
    lv_obj_set_height(ui2_Panel36, 40);
    lv_obj_set_x(ui2_Panel36, -131);
    lv_obj_set_y(ui2_Panel36, -78);
    lv_obj_set_align(ui2_Panel36, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel36, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel36, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel36, lv_color_hex(0xEE1420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel36, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label51 = lv_label_create(ui2_Panel36);
    lv_obj_set_width(ui2_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label51, -82);
    lv_obj_set_y(ui2_Label51, -38);
    lv_obj_set_align(ui2_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label51, "I");
    lv_obj_set_style_text_color(ui2_Label51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label51, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2current1 = lv_label_create(ui2_Panel35);
    lv_obj_set_width(ui2_port2current1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2current1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2current1, -16);
    lv_obj_set_y(ui2_port2current1, -78);
    lv_obj_set_align(ui2_port2current1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2current1, "3.564A");
    lv_obj_set_style_text_color(ui2_port2current1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port2current1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port2current1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container37 = lv_obj_create(ui2_Container35);
    lv_obj_remove_style_all(ui2_Container37);
    lv_obj_set_width(ui2_Container37, 243);
    lv_obj_set_height(ui2_Container37, 3);
    lv_obj_set_align(ui2_Container37, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel37 = lv_obj_create(ui2_Container35);
    lv_obj_set_width(ui2_Panel37, 240);
    lv_obj_set_height(ui2_Panel37, 50);
    lv_obj_set_x(ui2_Panel37, -16);
    lv_obj_set_y(ui2_Panel37, 2);
    lv_obj_set_align(ui2_Panel37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel37, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel37, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel38 = lv_obj_create(ui2_Panel37);
    lv_obj_set_width(ui2_Panel38, 40);
    lv_obj_set_height(ui2_Panel38, 40);
    lv_obj_set_x(ui2_Panel38, -131);
    lv_obj_set_y(ui2_Panel38, -25);
    lv_obj_set_align(ui2_Panel38, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel38, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel38, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel38, lv_color_hex(0xEE1420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel38, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label53 = lv_label_create(ui2_Panel38);
    lv_obj_set_width(ui2_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label53, -67);
    lv_obj_set_y(ui2_Label53, 26);
    lv_obj_set_align(ui2_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label53, "P");
    lv_obj_set_style_text_color(ui2_Label53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label53, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2powerlabel1 = lv_label_create(ui2_Panel37);
    lv_obj_set_width(ui2_port2powerlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2powerlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2powerlabel1, -15);
    lv_obj_set_y(ui2_port2powerlabel1, -28);
    lv_obj_set_align(ui2_port2powerlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2powerlabel1, "30.658W");
    lv_obj_set_style_text_color(ui2_port2powerlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port2powerlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port2powerlabel1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container38 = lv_obj_create(ui2_Container34);
    lv_obj_remove_style_all(ui2_Container38);
    lv_obj_set_height(ui2_Container38, 155);
    lv_obj_set_width(ui2_Container38, lv_pct(32));
    lv_obj_set_x(ui2_Container38, 119);
    lv_obj_set_y(ui2_Container38, -26);
    lv_obj_set_align(ui2_Container38, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container38, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container38, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container38, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container38, lv_color_hex(0x07595D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container38, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel39 = lv_obj_create(ui2_Container38);
    lv_obj_set_width(ui2_Panel39, lv_pct(100));
    lv_obj_set_height(ui2_Panel39, lv_pct(24));
    lv_obj_set_x(ui2_Panel39, 121);
    lv_obj_set_y(ui2_Panel39, -77);
    lv_obj_set_align(ui2_Panel39, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel39, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel39, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel39, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel39, lv_color_hex(0x095C62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel39, lv_color_hex(0x07585A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label65 = lv_label_create(ui2_Panel39);
    lv_obj_set_width(ui2_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label65, "STATE");
    lv_obj_set_style_text_font(ui2_Label65, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container39 = lv_obj_create(ui2_Container38);
    lv_obj_remove_style_all(ui2_Container39);
    lv_obj_set_width(ui2_Container39, 100);
    lv_obj_set_height(ui2_Container39, 18);
    lv_obj_set_align(ui2_Container39, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port2powerlabel = lv_label_create(ui2_Container38);
    lv_obj_set_width(ui2_port2powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2powerlabel, 122);
    lv_obj_set_y(ui2_port2powerlabel, -61);
    lv_obj_set_align(ui2_port2powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2powerlabel, "已开启");
    lv_obj_set_style_text_font(ui2_port2powerlabel, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container40 = lv_obj_create(ui2_Container38);
    lv_obj_remove_style_all(ui2_Container40);
    lv_obj_set_width(ui2_Container40, 100);
    lv_obj_set_height(ui2_Container40, 16);
    lv_obj_set_align(ui2_Container40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port2state = lv_label_create(ui2_Container38);
    lv_obj_set_width(ui2_port2state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2state, 120);
    lv_obj_set_y(ui2_port2state, -8);
    lv_obj_set_align(ui2_port2state, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2state, "已连接");
    lv_obj_set_style_text_font(ui2_port2state, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container41 = lv_obj_create(ui2_Container34);
    lv_obj_remove_style_all(ui2_Container41);
    lv_obj_set_width(ui2_Container41, 180);
    lv_obj_set_height(ui2_Container41, 151);
    lv_obj_set_x(ui2_Container41, 93);
    lv_obj_set_y(ui2_Container41, 102);
    lv_obj_set_align(ui2_Container41, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container41, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container41, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container41, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container41, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container41, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel40 = lv_obj_create(ui2_Container41);
    lv_obj_set_width(ui2_Panel40, lv_pct(100));
    lv_obj_set_height(ui2_Panel40, lv_pct(24));
    lv_obj_set_x(ui2_Panel40, 64);
    lv_obj_set_y(ui2_Panel40, 58);
    lv_obj_set_align(ui2_Panel40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel40, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel40, lv_color_hex(0xBA7408), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel40, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label68 = lv_label_create(ui2_Panel40);
    lv_obj_set_width(ui2_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label68, "PROTOCOL");
    lv_obj_set_style_text_font(ui2_Label68, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container42 = lv_obj_create(ui2_Container41);
    lv_obj_remove_style_all(ui2_Container42);
    lv_obj_set_width(ui2_Container42, lv_pct(70));
    lv_obj_set_height(ui2_Container42, lv_pct(25));
    lv_obj_set_x(ui2_Container42, -3);
    lv_obj_set_y(ui2_Container42, 56);
    lv_obj_set_align(ui2_Container42, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container42, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container42, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label69 = lv_label_create(ui2_Container42);
    lv_obj_set_width(ui2_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label69, -142);
    lv_obj_set_y(ui2_Label69, 94);
    lv_obj_set_align(ui2_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label69, "协议：");
    lv_obj_set_style_text_font(ui2_Label69, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2protocol = lv_label_create(ui2_Container42);
    lv_obj_set_width(ui2_port2protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2protocol, -94);
    lv_obj_set_y(ui2_port2protocol, 91);
    lv_obj_set_align(ui2_port2protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2protocol, "PD");
    lv_obj_set_style_text_font(ui2_port2protocol, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container43 = lv_obj_create(ui2_Container41);
    lv_obj_remove_style_all(ui2_Container43);
    lv_obj_set_width(ui2_Container43, lv_pct(70));
    lv_obj_set_height(ui2_Container43, lv_pct(22));
    lv_obj_set_x(ui2_Container43, -3);
    lv_obj_set_y(ui2_Container43, 56);
    lv_obj_set_align(ui2_Container43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container43, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container43, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label71 = lv_label_create(ui2_Container43);
    lv_obj_set_width(ui2_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label71, -141);
    lv_obj_set_y(ui2_Label71, 120);
    lv_obj_set_align(ui2_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label71, "版本：");
    lv_obj_set_style_text_font(ui2_Label71, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2revision = lv_label_create(ui2_Container43);
    lv_obj_set_width(ui2_port2revision, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2revision, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2revision, -93);
    lv_obj_set_y(ui2_port2revision, 120);
    lv_obj_set_align(ui2_port2revision, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2revision, "3.0");
    lv_obj_set_style_text_font(ui2_port2revision, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container44 = lv_obj_create(ui2_Container41);
    lv_obj_remove_style_all(ui2_Container44);
    lv_obj_set_width(ui2_Container44, lv_pct(70));
    lv_obj_set_height(ui2_Container44, lv_pct(22));
    lv_obj_set_x(ui2_Container44, -3);
    lv_obj_set_y(ui2_Container44, 56);
    lv_obj_set_align(ui2_Container44, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container44, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container44, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label73 = lv_label_create(ui2_Container44);
    lv_obj_set_width(ui2_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label73, -141);
    lv_obj_set_y(ui2_Label73, 147);
    lv_obj_set_align(ui2_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label73, "功率：");
    lv_obj_set_style_text_font(ui2_Label73, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2protocolpower = lv_label_create(ui2_Container44);
    lv_obj_set_width(ui2_port2protocolpower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2protocolpower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2protocolpower, -86);
    lv_obj_set_y(ui2_port2protocolpower, 145);
    lv_obj_set_align(ui2_port2protocolpower, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2protocolpower, "100W");
    lv_obj_set_style_text_font(ui2_port2protocolpower, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container45 = lv_obj_create(ui2_Container34);
    lv_obj_remove_style_all(ui2_Container45);
    lv_obj_set_width(ui2_Container45, 5);
    lv_obj_set_height(ui2_Container45, 136);
    lv_obj_set_align(ui2_Container45, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container45, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container46 = lv_obj_create(ui2_Container34);
    lv_obj_remove_style_all(ui2_Container46);
    lv_obj_set_width(ui2_Container46, 180);
    lv_obj_set_height(ui2_Container46, 151);
    lv_obj_set_x(ui2_Container46, -89);
    lv_obj_set_y(ui2_Container46, 102);
    lv_obj_set_align(ui2_Container46, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container46, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container46, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container46, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container46, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container46, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel41 = lv_obj_create(ui2_Container46);
    lv_obj_set_width(ui2_Panel41, lv_pct(100));
    lv_obj_set_height(ui2_Panel41, lv_pct(24));
    lv_obj_set_x(ui2_Panel41, -78);
    lv_obj_set_y(ui2_Panel41, 72);
    lv_obj_set_align(ui2_Panel41, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel41, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel41, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel41, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel41, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel41, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label75 = lv_label_create(ui2_Panel41);
    lv_obj_set_width(ui2_Label75, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label75, -116);
    lv_obj_set_y(ui2_Label75, 71);
    lv_obj_set_align(ui2_Label75, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label75, "WIRE ROD");
    lv_obj_set_style_text_font(ui2_Label75, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container47 = lv_obj_create(ui2_Container46);
    lv_obj_remove_style_all(ui2_Container47);
    lv_obj_set_width(ui2_Container47, lv_pct(75));
    lv_obj_set_height(ui2_Container47, lv_pct(20));
    lv_obj_set_x(ui2_Container47, 82);
    lv_obj_set_y(ui2_Container47, 89);
    lv_obj_set_align(ui2_Container47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container47, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container47, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container47, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label76 = lv_label_create(ui2_Container47);
    lv_obj_set_width(ui2_Label76, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label76, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label76, 50);
    lv_obj_set_y(ui2_Label76, 92);
    lv_obj_set_align(ui2_Label76, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label76, "制造商：");
    lv_obj_set_style_text_font(ui2_Label76, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2manufactuervid = lv_label_create(ui2_Container47);
    lv_obj_set_width(ui2_port2manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2manufactuervid, 110);
    lv_obj_set_y(ui2_port2manufactuervid, 89);
    lv_obj_set_align(ui2_port2manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2manufactuervid, "小米");
    lv_obj_set_style_text_font(ui2_port2manufactuervid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container48 = lv_obj_create(ui2_Container46);
    lv_obj_remove_style_all(ui2_Container48);
    lv_obj_set_width(ui2_Container48, lv_pct(75));
    lv_obj_set_height(ui2_Container48, lv_pct(17));
    lv_obj_set_x(ui2_Container48, 82);
    lv_obj_set_y(ui2_Container48, 89);
    lv_obj_set_align(ui2_Container48, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container48, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container48, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container48, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label78 = lv_label_create(ui2_Container48);
    lv_obj_set_width(ui2_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label78, 50);
    lv_obj_set_y(ui2_Label78, 92);
    lv_obj_set_align(ui2_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label78, "线缆厂商：");
    lv_obj_set_style_text_font(ui2_Label78, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2cablevid = lv_label_create(ui2_Container48);
    lv_obj_set_width(ui2_port2cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2cablevid, 110);
    lv_obj_set_y(ui2_port2cablevid, 89);
    lv_obj_set_align(ui2_port2cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2cablevid, "酷态科");
    lv_obj_set_style_text_font(ui2_port2cablevid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container49 = lv_obj_create(ui2_Container46);
    lv_obj_remove_style_all(ui2_Container49);
    lv_obj_set_width(ui2_Container49, lv_pct(75));
    lv_obj_set_height(ui2_Container49, lv_pct(17));
    lv_obj_set_x(ui2_Container49, 82);
    lv_obj_set_y(ui2_Container49, 89);
    lv_obj_set_align(ui2_Container49, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container49, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container49, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container49, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label80 = lv_label_create(ui2_Container49);
    lv_obj_set_width(ui2_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label80, 50);
    lv_obj_set_y(ui2_Label80, 92);
    lv_obj_set_align(ui2_Label80, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label80, "最大电压：");
    lv_obj_set_style_text_font(ui2_Label80, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2maxvbusvoltage = lv_label_create(ui2_Container49);
    lv_obj_set_width(ui2_port2maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2maxvbusvoltage, 110);
    lv_obj_set_y(ui2_port2maxvbusvoltage, 89);
    lv_obj_set_align(ui2_port2maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2maxvbusvoltage, "20V");
    lv_obj_set_style_text_font(ui2_port2maxvbusvoltage, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container50 = lv_obj_create(ui2_Container46);
    lv_obj_remove_style_all(ui2_Container50);
    lv_obj_set_width(ui2_Container50, lv_pct(75));
    lv_obj_set_height(ui2_Container50, lv_pct(17));
    lv_obj_set_x(ui2_Container50, 82);
    lv_obj_set_y(ui2_Container50, 89);
    lv_obj_set_align(ui2_Container50, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container50, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container50, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container50, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label82 = lv_label_create(ui2_Container50);
    lv_obj_set_width(ui2_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label82, 50);
    lv_obj_set_y(ui2_Label82, 92);
    lv_obj_set_align(ui2_Label82, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label82, "最大电流：");
    lv_obj_set_style_text_font(ui2_Label82, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2maxvbuscurrent = lv_label_create(ui2_Container50);
    lv_obj_set_width(ui2_port2maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2maxvbuscurrent, 110);
    lv_obj_set_y(ui2_port2maxvbuscurrent, 89);
    lv_obj_set_align(ui2_port2maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2maxvbuscurrent, "5A");
    lv_obj_set_style_text_font(ui2_port2maxvbuscurrent, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui2_port2SCREEN, ui2_event_port2SCREEN, LV_EVENT_ALL, NULL);

}

void ui2_port2SCREEN_screen_destroy(void)
{
    if(ui2_port2SCREEN) lv_obj_del(ui2_port2SCREEN);

    // NULL screen variables
    ui2_port2SCREEN = NULL;
    ui2_Container34 = NULL;
    ui2_Panel32 = NULL;
    ui2_Label45 = NULL;
    ui2_Container35 = NULL;
    ui2_Panel33 = NULL;
    ui2_Panel34 = NULL;
    ui2_Label49 = NULL;
    ui2_port2voltage1 = NULL;
    ui2_Container36 = NULL;
    ui2_Panel35 = NULL;
    ui2_Panel36 = NULL;
    ui2_Label51 = NULL;
    ui2_port2current1 = NULL;
    ui2_Container37 = NULL;
    ui2_Panel37 = NULL;
    ui2_Panel38 = NULL;
    ui2_Label53 = NULL;
    ui2_port2powerlabel1 = NULL;
    ui2_Container38 = NULL;
    ui2_Panel39 = NULL;
    ui2_Label65 = NULL;
    ui2_Container39 = NULL;
    ui2_port2powerlabel = NULL;
    ui2_Container40 = NULL;
    ui2_port2state = NULL;
    ui2_Container41 = NULL;
    ui2_Panel40 = NULL;
    ui2_Label68 = NULL;
    ui2_Container42 = NULL;
    ui2_Label69 = NULL;
    ui2_port2protocol = NULL;
    ui2_Container43 = NULL;
    ui2_Label71 = NULL;
    ui2_port2revision = NULL;
    ui2_Container44 = NULL;
    ui2_Label73 = NULL;
    ui2_port2protocolpower = NULL;
    ui2_Container45 = NULL;
    ui2_Container46 = NULL;
    ui2_Panel41 = NULL;
    ui2_Label75 = NULL;
    ui2_Container47 = NULL;
    ui2_Label76 = NULL;
    ui2_port2manufactuervid = NULL;
    ui2_Container48 = NULL;
    ui2_Label78 = NULL;
    ui2_port2cablevid = NULL;
    ui2_Container49 = NULL;
    ui2_Label80 = NULL;
    ui2_port2maxvbusvoltage = NULL;
    ui2_Container50 = NULL;
    ui2_Label82 = NULL;
    ui2_port2maxvbuscurrent = NULL;

}

void ui2_port2SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
