// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"

lv_obj_t * ui2_port4SCREEN = NULL;
lv_obj_t * ui2_Container68 = NULL;
lv_obj_t * ui2_Panel52 = NULL;
lv_obj_t * ui2_Label110 = NULL;
lv_obj_t * ui2_Container69 = NULL;
lv_obj_t * ui2_Panel53 = NULL;
lv_obj_t * ui2_Panel54 = NULL;
lv_obj_t * ui2_Label111 = NULL;
lv_obj_t * ui2_port4voltage1 = NULL;
lv_obj_t * ui2_Container70 = NULL;
lv_obj_t * ui2_Panel55 = NULL;
lv_obj_t * ui2_Panel56 = NULL;
lv_obj_t * ui2_Label113 = NULL;
lv_obj_t * ui2_port4current1 = NULL;
lv_obj_t * ui2_Container71 = NULL;
lv_obj_t * ui2_Panel57 = NULL;
lv_obj_t * ui2_Panel58 = NULL;
lv_obj_t * ui2_Label115 = NULL;
lv_obj_t * ui2_port4powerlabel1 = NULL;
lv_obj_t * ui2_Container72 = NULL;
lv_obj_t * ui2_Panel59 = NULL;
lv_obj_t * ui2_Label117 = NULL;
lv_obj_t * ui2_Container73 = NULL;
lv_obj_t * ui2_port4powerlabel = NULL;
lv_obj_t * ui2_Container74 = NULL;
lv_obj_t * ui2_port4state = NULL;
lv_obj_t * ui2_Container75 = NULL;
lv_obj_t * ui2_Panel60 = NULL;
lv_obj_t * ui2_Label120 = NULL;
lv_obj_t * ui2_Container76 = NULL;
lv_obj_t * ui2_Label121 = NULL;
lv_obj_t * ui2_port4protocol = NULL;
lv_obj_t * ui2_Container77 = NULL;
lv_obj_t * ui2_Label123 = NULL;
lv_obj_t * ui2_port4revision = NULL;
lv_obj_t * ui2_Container78 = NULL;
lv_obj_t * ui2_Label125 = NULL;
lv_obj_t * ui2_port4protocolpower = NULL;
lv_obj_t * ui2_Container79 = NULL;
lv_obj_t * ui2_Container80 = NULL;
lv_obj_t * ui2_Panel61 = NULL;
lv_obj_t * ui2_Label127 = NULL;
lv_obj_t * ui2_Container81 = NULL;
lv_obj_t * ui2_Label128 = NULL;
lv_obj_t * ui2_port4manufactuervid = NULL;
lv_obj_t * ui2_Container82 = NULL;
lv_obj_t * ui2_Label130 = NULL;
lv_obj_t * ui2_port4cablevid = NULL;
lv_obj_t * ui2_Container83 = NULL;
lv_obj_t * ui2_Label132 = NULL;
lv_obj_t * ui2_port4maxvbusvoltage = NULL;
lv_obj_t * ui2_Container84 = NULL;
lv_obj_t * ui2_Label134 = NULL;
lv_obj_t * ui2_port4maxvbuscurrent = NULL;
// event funtions
void ui2_event_port4SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_totalpowerSCREEN, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui2_totalpowerSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port3SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui2_port3SCREEN_screen_init);
    }
}

// build funtions

void ui2_port4SCREEN_screen_init(void)
{
    ui2_port4SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_port4SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container68 = lv_obj_create(ui2_port4SCREEN);
    lv_obj_remove_style_all(ui2_Container68);
    lv_obj_set_width(ui2_Container68, lv_pct(100));
    lv_obj_set_height(ui2_Container68, lv_pct(100));
    lv_obj_set_align(ui2_Container68, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container68, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container68, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container68, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel52 = lv_obj_create(ui2_Container68);
    lv_obj_set_width(ui2_Panel52, 368);
    lv_obj_set_height(ui2_Panel52, 49);
    lv_obj_set_align(ui2_Panel52, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel52, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel52, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel52, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel52, lv_color_hex(0x4A6508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label110 = lv_label_create(ui2_Panel52);
    lv_obj_set_width(ui2_Label110, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label110, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label110, -34);
    lv_obj_set_y(ui2_Label110, -201);
    lv_obj_set_align(ui2_Label110, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label110, "C4 PORT");
    lv_obj_set_style_text_color(ui2_Label110, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label110, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label110, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container69 = lv_obj_create(ui2_Container68);
    lv_obj_remove_style_all(ui2_Container69);
    lv_obj_set_width(ui2_Container69, 246);
    lv_obj_set_height(ui2_Container69, 168);
    lv_obj_set_x(ui2_Container69, -36);
    lv_obj_set_y(ui2_Container69, -72);
    lv_obj_set_align(ui2_Container69, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container69, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container69, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container69, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel53 = lv_obj_create(ui2_Container69);
    lv_obj_set_width(ui2_Panel53, 240);
    lv_obj_set_height(ui2_Panel53, 50);
    lv_obj_set_x(ui2_Panel53, -24);
    lv_obj_set_y(ui2_Panel53, -115);
    lv_obj_set_align(ui2_Panel53, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel53, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel53, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel53, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel54 = lv_obj_create(ui2_Panel53);
    lv_obj_set_width(ui2_Panel54, 40);
    lv_obj_set_height(ui2_Panel54, 40);
    lv_obj_set_x(ui2_Panel54, -127);
    lv_obj_set_y(ui2_Panel54, -131);
    lv_obj_set_align(ui2_Panel54, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel54, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel54, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel54, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel54, lv_color_hex(0x4A6508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel54, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label111 = lv_label_create(ui2_Panel54);
    lv_obj_set_width(ui2_Label111, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label111, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label111, -70);
    lv_obj_set_y(ui2_Label111, -94);
    lv_obj_set_align(ui2_Label111, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label111, "U");
    lv_obj_set_style_text_color(ui2_Label111, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label111, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label111, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4voltage1 = lv_label_create(ui2_Panel53);
    lv_obj_set_width(ui2_port4voltage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4voltage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4voltage1, -7);
    lv_obj_set_y(ui2_port4voltage1, -131);
    lv_obj_set_align(ui2_port4voltage1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4voltage1, "27.842V");
    lv_obj_set_style_text_color(ui2_port4voltage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port4voltage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port4voltage1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container70 = lv_obj_create(ui2_Container69);
    lv_obj_remove_style_all(ui2_Container70);
    lv_obj_set_width(ui2_Container70, 243);
    lv_obj_set_height(ui2_Container70, 3);
    lv_obj_set_align(ui2_Container70, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container70, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel55 = lv_obj_create(ui2_Container69);
    lv_obj_set_width(ui2_Panel55, 240);
    lv_obj_set_height(ui2_Panel55, 50);
    lv_obj_set_x(ui2_Panel55, -19);
    lv_obj_set_y(ui2_Panel55, -57);
    lv_obj_set_align(ui2_Panel55, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel55, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel55, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel55, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel56 = lv_obj_create(ui2_Panel55);
    lv_obj_set_width(ui2_Panel56, 40);
    lv_obj_set_height(ui2_Panel56, 40);
    lv_obj_set_x(ui2_Panel56, -131);
    lv_obj_set_y(ui2_Panel56, -78);
    lv_obj_set_align(ui2_Panel56, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel56, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel56, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel56, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel56, lv_color_hex(0x4A6508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel56, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label113 = lv_label_create(ui2_Panel56);
    lv_obj_set_width(ui2_Label113, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label113, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label113, -82);
    lv_obj_set_y(ui2_Label113, -38);
    lv_obj_set_align(ui2_Label113, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label113, "I");
    lv_obj_set_style_text_color(ui2_Label113, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label113, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label113, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4current1 = lv_label_create(ui2_Panel55);
    lv_obj_set_width(ui2_port4current1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4current1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4current1, -16);
    lv_obj_set_y(ui2_port4current1, -78);
    lv_obj_set_align(ui2_port4current1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4current1, "3.564A");
    lv_obj_set_style_text_color(ui2_port4current1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port4current1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port4current1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container71 = lv_obj_create(ui2_Container69);
    lv_obj_remove_style_all(ui2_Container71);
    lv_obj_set_width(ui2_Container71, 243);
    lv_obj_set_height(ui2_Container71, 3);
    lv_obj_set_align(ui2_Container71, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container71, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel57 = lv_obj_create(ui2_Container69);
    lv_obj_set_width(ui2_Panel57, 240);
    lv_obj_set_height(ui2_Panel57, 50);
    lv_obj_set_x(ui2_Panel57, -16);
    lv_obj_set_y(ui2_Panel57, 2);
    lv_obj_set_align(ui2_Panel57, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel57, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel57, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel57, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel58 = lv_obj_create(ui2_Panel57);
    lv_obj_set_width(ui2_Panel58, 40);
    lv_obj_set_height(ui2_Panel58, 40);
    lv_obj_set_x(ui2_Panel58, -131);
    lv_obj_set_y(ui2_Panel58, -25);
    lv_obj_set_align(ui2_Panel58, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel58, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel58, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel58, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui2_Panel58, lv_color_hex(0x4A6508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel58, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label115 = lv_label_create(ui2_Panel58);
    lv_obj_set_width(ui2_Label115, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label115, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label115, -67);
    lv_obj_set_y(ui2_Label115, 26);
    lv_obj_set_align(ui2_Label115, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label115, "P");
    lv_obj_set_style_text_color(ui2_Label115, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label115, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label115, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4powerlabel1 = lv_label_create(ui2_Panel57);
    lv_obj_set_width(ui2_port4powerlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4powerlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4powerlabel1, -15);
    lv_obj_set_y(ui2_port4powerlabel1, -28);
    lv_obj_set_align(ui2_port4powerlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4powerlabel1, "30.658W");
    lv_obj_set_style_text_color(ui2_port4powerlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port4powerlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port4powerlabel1, &ui2_font_ShuHei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container72 = lv_obj_create(ui2_Container68);
    lv_obj_remove_style_all(ui2_Container72);
    lv_obj_set_height(ui2_Container72, 155);
    lv_obj_set_width(ui2_Container72, lv_pct(32));
    lv_obj_set_x(ui2_Container72, 119);
    lv_obj_set_y(ui2_Container72, -26);
    lv_obj_set_align(ui2_Container72, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container72, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container72, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container72, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container72, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container72, lv_color_hex(0x07595D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container72, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container72, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel59 = lv_obj_create(ui2_Container72);
    lv_obj_set_width(ui2_Panel59, lv_pct(100));
    lv_obj_set_height(ui2_Panel59, lv_pct(24));
    lv_obj_set_x(ui2_Panel59, 121);
    lv_obj_set_y(ui2_Panel59, -77);
    lv_obj_set_align(ui2_Panel59, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel59, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel59, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel59, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel59, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel59, lv_color_hex(0x095C62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel59, lv_color_hex(0x07585A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label117 = lv_label_create(ui2_Panel59);
    lv_obj_set_width(ui2_Label117, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label117, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label117, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label117, "STATE");
    lv_obj_set_style_text_font(ui2_Label117, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container73 = lv_obj_create(ui2_Container72);
    lv_obj_remove_style_all(ui2_Container73);
    lv_obj_set_width(ui2_Container73, 100);
    lv_obj_set_height(ui2_Container73, 18);
    lv_obj_set_align(ui2_Container73, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container73, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port4powerlabel = lv_label_create(ui2_Container72);
    lv_obj_set_width(ui2_port4powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4powerlabel, 122);
    lv_obj_set_y(ui2_port4powerlabel, -61);
    lv_obj_set_align(ui2_port4powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4powerlabel, "已开启");
    lv_obj_set_style_text_font(ui2_port4powerlabel, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container74 = lv_obj_create(ui2_Container72);
    lv_obj_remove_style_all(ui2_Container74);
    lv_obj_set_width(ui2_Container74, 100);
    lv_obj_set_height(ui2_Container74, 16);
    lv_obj_set_align(ui2_Container74, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container74, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_port4state = lv_label_create(ui2_Container72);
    lv_obj_set_width(ui2_port4state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4state, 120);
    lv_obj_set_y(ui2_port4state, -8);
    lv_obj_set_align(ui2_port4state, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4state, "已连接");
    lv_obj_set_style_text_font(ui2_port4state, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container75 = lv_obj_create(ui2_Container68);
    lv_obj_remove_style_all(ui2_Container75);
    lv_obj_set_width(ui2_Container75, 180);
    lv_obj_set_height(ui2_Container75, 151);
    lv_obj_set_x(ui2_Container75, 93);
    lv_obj_set_y(ui2_Container75, 102);
    lv_obj_set_align(ui2_Container75, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container75, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container75, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container75, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container75, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container75, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container75, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container75, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel60 = lv_obj_create(ui2_Container75);
    lv_obj_set_width(ui2_Panel60, lv_pct(100));
    lv_obj_set_height(ui2_Panel60, lv_pct(24));
    lv_obj_set_x(ui2_Panel60, 64);
    lv_obj_set_y(ui2_Panel60, 58);
    lv_obj_set_align(ui2_Panel60, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel60, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel60, lv_color_hex(0xBA7408), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel60, lv_color_hex(0xBD7508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label120 = lv_label_create(ui2_Panel60);
    lv_obj_set_width(ui2_Label120, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label120, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui2_Label120, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label120, "PROTOCOL");
    lv_obj_set_style_text_font(ui2_Label120, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container76 = lv_obj_create(ui2_Container75);
    lv_obj_remove_style_all(ui2_Container76);
    lv_obj_set_width(ui2_Container76, lv_pct(70));
    lv_obj_set_height(ui2_Container76, lv_pct(25));
    lv_obj_set_x(ui2_Container76, -3);
    lv_obj_set_y(ui2_Container76, 56);
    lv_obj_set_align(ui2_Container76, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container76, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container76, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container76, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label121 = lv_label_create(ui2_Container76);
    lv_obj_set_width(ui2_Label121, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label121, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label121, -142);
    lv_obj_set_y(ui2_Label121, 94);
    lv_obj_set_align(ui2_Label121, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label121, "协议：");
    lv_obj_set_style_text_font(ui2_Label121, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4protocol = lv_label_create(ui2_Container76);
    lv_obj_set_width(ui2_port4protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4protocol, -94);
    lv_obj_set_y(ui2_port4protocol, 91);
    lv_obj_set_align(ui2_port4protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4protocol, "PD");
    lv_obj_set_style_text_font(ui2_port4protocol, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container77 = lv_obj_create(ui2_Container75);
    lv_obj_remove_style_all(ui2_Container77);
    lv_obj_set_width(ui2_Container77, lv_pct(70));
    lv_obj_set_height(ui2_Container77, lv_pct(22));
    lv_obj_set_x(ui2_Container77, -3);
    lv_obj_set_y(ui2_Container77, 56);
    lv_obj_set_align(ui2_Container77, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container77, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container77, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container77, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label123 = lv_label_create(ui2_Container77);
    lv_obj_set_width(ui2_Label123, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label123, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label123, -141);
    lv_obj_set_y(ui2_Label123, 120);
    lv_obj_set_align(ui2_Label123, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label123, "版本：");
    lv_obj_set_style_text_font(ui2_Label123, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4revision = lv_label_create(ui2_Container77);
    lv_obj_set_width(ui2_port4revision, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4revision, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4revision, -93);
    lv_obj_set_y(ui2_port4revision, 120);
    lv_obj_set_align(ui2_port4revision, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4revision, "3.0");
    lv_obj_set_style_text_font(ui2_port4revision, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container78 = lv_obj_create(ui2_Container75);
    lv_obj_remove_style_all(ui2_Container78);
    lv_obj_set_width(ui2_Container78, lv_pct(70));
    lv_obj_set_height(ui2_Container78, lv_pct(22));
    lv_obj_set_x(ui2_Container78, -3);
    lv_obj_set_y(ui2_Container78, 56);
    lv_obj_set_align(ui2_Container78, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container78, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container78, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container78, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label125 = lv_label_create(ui2_Container78);
    lv_obj_set_width(ui2_Label125, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label125, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label125, -141);
    lv_obj_set_y(ui2_Label125, 147);
    lv_obj_set_align(ui2_Label125, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label125, "功率：");
    lv_obj_set_style_text_font(ui2_Label125, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4protocolpower = lv_label_create(ui2_Container78);
    lv_obj_set_width(ui2_port4protocolpower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4protocolpower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4protocolpower, -86);
    lv_obj_set_y(ui2_port4protocolpower, 145);
    lv_obj_set_align(ui2_port4protocolpower, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4protocolpower, "100W");
    lv_obj_set_style_text_font(ui2_port4protocolpower, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container79 = lv_obj_create(ui2_Container68);
    lv_obj_remove_style_all(ui2_Container79);
    lv_obj_set_width(ui2_Container79, 5);
    lv_obj_set_height(ui2_Container79, 136);
    lv_obj_set_align(ui2_Container79, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container79, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container80 = lv_obj_create(ui2_Container68);
    lv_obj_remove_style_all(ui2_Container80);
    lv_obj_set_width(ui2_Container80, 180);
    lv_obj_set_height(ui2_Container80, 151);
    lv_obj_set_x(ui2_Container80, -89);
    lv_obj_set_y(ui2_Container80, 102);
    lv_obj_set_align(ui2_Container80, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container80, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Container80, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui2_Container80, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Container80, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Container80, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Container80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Container80, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel61 = lv_obj_create(ui2_Container80);
    lv_obj_set_width(ui2_Panel61, lv_pct(100));
    lv_obj_set_height(ui2_Panel61, lv_pct(24));
    lv_obj_set_x(ui2_Panel61, -78);
    lv_obj_set_y(ui2_Panel61, 72);
    lv_obj_set_align(ui2_Panel61, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel61, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel61, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel61, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel61, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel61, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel61, lv_color_hex(0xED3296), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label127 = lv_label_create(ui2_Panel61);
    lv_obj_set_width(ui2_Label127, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label127, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label127, -116);
    lv_obj_set_y(ui2_Label127, 71);
    lv_obj_set_align(ui2_Label127, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label127, "WIRE ROD");
    lv_obj_set_style_text_font(ui2_Label127, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container81 = lv_obj_create(ui2_Container80);
    lv_obj_remove_style_all(ui2_Container81);
    lv_obj_set_width(ui2_Container81, lv_pct(75));
    lv_obj_set_height(ui2_Container81, lv_pct(20));
    lv_obj_set_x(ui2_Container81, 82);
    lv_obj_set_y(ui2_Container81, 89);
    lv_obj_set_align(ui2_Container81, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container81, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container81, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container81, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label128 = lv_label_create(ui2_Container81);
    lv_obj_set_width(ui2_Label128, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label128, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label128, 50);
    lv_obj_set_y(ui2_Label128, 92);
    lv_obj_set_align(ui2_Label128, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label128, "制造商：");
    lv_obj_set_style_text_font(ui2_Label128, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4manufactuervid = lv_label_create(ui2_Container81);
    lv_obj_set_width(ui2_port4manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4manufactuervid, 110);
    lv_obj_set_y(ui2_port4manufactuervid, 89);
    lv_obj_set_align(ui2_port4manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4manufactuervid, "小米");
    lv_obj_set_style_text_font(ui2_port4manufactuervid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container82 = lv_obj_create(ui2_Container80);
    lv_obj_remove_style_all(ui2_Container82);
    lv_obj_set_width(ui2_Container82, lv_pct(75));
    lv_obj_set_height(ui2_Container82, lv_pct(17));
    lv_obj_set_x(ui2_Container82, 82);
    lv_obj_set_y(ui2_Container82, 89);
    lv_obj_set_align(ui2_Container82, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container82, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container82, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container82, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label130 = lv_label_create(ui2_Container82);
    lv_obj_set_width(ui2_Label130, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label130, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label130, 50);
    lv_obj_set_y(ui2_Label130, 92);
    lv_obj_set_align(ui2_Label130, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label130, "线缆厂商：");
    lv_obj_set_style_text_font(ui2_Label130, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4cablevid = lv_label_create(ui2_Container82);
    lv_obj_set_width(ui2_port4cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4cablevid, 110);
    lv_obj_set_y(ui2_port4cablevid, 89);
    lv_obj_set_align(ui2_port4cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4cablevid, "酷态科");
    lv_obj_set_style_text_font(ui2_port4cablevid, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container83 = lv_obj_create(ui2_Container80);
    lv_obj_remove_style_all(ui2_Container83);
    lv_obj_set_width(ui2_Container83, lv_pct(75));
    lv_obj_set_height(ui2_Container83, lv_pct(17));
    lv_obj_set_x(ui2_Container83, 82);
    lv_obj_set_y(ui2_Container83, 89);
    lv_obj_set_align(ui2_Container83, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container83, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container83, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container83, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label132 = lv_label_create(ui2_Container83);
    lv_obj_set_width(ui2_Label132, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label132, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label132, 50);
    lv_obj_set_y(ui2_Label132, 92);
    lv_obj_set_align(ui2_Label132, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label132, "最大电压：");
    lv_obj_set_style_text_font(ui2_Label132, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4maxvbusvoltage = lv_label_create(ui2_Container83);
    lv_obj_set_width(ui2_port4maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4maxvbusvoltage, 110);
    lv_obj_set_y(ui2_port4maxvbusvoltage, 89);
    lv_obj_set_align(ui2_port4maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4maxvbusvoltage, "20V");
    lv_obj_set_style_text_font(ui2_port4maxvbusvoltage, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container84 = lv_obj_create(ui2_Container80);
    lv_obj_remove_style_all(ui2_Container84);
    lv_obj_set_width(ui2_Container84, lv_pct(75));
    lv_obj_set_height(ui2_Container84, lv_pct(17));
    lv_obj_set_x(ui2_Container84, 82);
    lv_obj_set_y(ui2_Container84, 89);
    lv_obj_set_align(ui2_Container84, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container84, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container84, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container84, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Label134 = lv_label_create(ui2_Container84);
    lv_obj_set_width(ui2_Label134, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label134, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label134, 50);
    lv_obj_set_y(ui2_Label134, 92);
    lv_obj_set_align(ui2_Label134, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label134, "最大电流：");
    lv_obj_set_style_text_font(ui2_Label134, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4maxvbuscurrent = lv_label_create(ui2_Container84);
    lv_obj_set_width(ui2_port4maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4maxvbuscurrent, 110);
    lv_obj_set_y(ui2_port4maxvbuscurrent, 89);
    lv_obj_set_align(ui2_port4maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4maxvbuscurrent, "5A");
    lv_obj_set_style_text_font(ui2_port4maxvbuscurrent, &ui2_font_ShuHei14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui2_port4SCREEN, ui2_event_port4SCREEN, LV_EVENT_ALL, NULL);

}

void ui2_port4SCREEN_screen_destroy(void)
{
    if(ui2_port4SCREEN) lv_obj_del(ui2_port4SCREEN);

    // NULL screen variables
    ui2_port4SCREEN = NULL;
    ui2_Container68 = NULL;
    ui2_Panel52 = NULL;
    ui2_Label110 = NULL;
    ui2_Container69 = NULL;
    ui2_Panel53 = NULL;
    ui2_Panel54 = NULL;
    ui2_Label111 = NULL;
    ui2_port4voltage1 = NULL;
    ui2_Container70 = NULL;
    ui2_Panel55 = NULL;
    ui2_Panel56 = NULL;
    ui2_Label113 = NULL;
    ui2_port4current1 = NULL;
    ui2_Container71 = NULL;
    ui2_Panel57 = NULL;
    ui2_Panel58 = NULL;
    ui2_Label115 = NULL;
    ui2_port4powerlabel1 = NULL;
    ui2_Container72 = NULL;
    ui2_Panel59 = NULL;
    ui2_Label117 = NULL;
    ui2_Container73 = NULL;
    ui2_port4powerlabel = NULL;
    ui2_Container74 = NULL;
    ui2_port4state = NULL;
    ui2_Container75 = NULL;
    ui2_Panel60 = NULL;
    ui2_Label120 = NULL;
    ui2_Container76 = NULL;
    ui2_Label121 = NULL;
    ui2_port4protocol = NULL;
    ui2_Container77 = NULL;
    ui2_Label123 = NULL;
    ui2_port4revision = NULL;
    ui2_Container78 = NULL;
    ui2_Label125 = NULL;
    ui2_port4protocolpower = NULL;
    ui2_Container79 = NULL;
    ui2_Container80 = NULL;
    ui2_Panel61 = NULL;
    ui2_Label127 = NULL;
    ui2_Container81 = NULL;
    ui2_Label128 = NULL;
    ui2_port4manufactuervid = NULL;
    ui2_Container82 = NULL;
    ui2_Label130 = NULL;
    ui2_port4cablevid = NULL;
    ui2_Container83 = NULL;
    ui2_Label132 = NULL;
    ui2_port4maxvbusvoltage = NULL;
    ui2_Container84 = NULL;
    ui2_Label134 = NULL;
    ui2_port4maxvbuscurrent = NULL;

}

void ui2_port4SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
