// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui2_PORT1SCREEN_H
#define ui2_PORT1SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui2_port1SCREEN
extern void ui2_port1SCREEN_screen_init(void);
extern void ui2_port1SCREEN_screen_destroy(void);
extern void ui2_port1SCREEN_screen_relocalize(void);
extern void ui2_event_port1SCREEN(lv_event_t * e);
extern lv_obj_t * ui2_port1SCREEN;
extern lv_obj_t * ui2_Container16;
extern lv_obj_t * ui2_Panel22;
extern lv_obj_t * ui2_Label32;
extern lv_obj_t * ui2_Container19;
extern lv_obj_t * ui2_Panel26;
extern lv_obj_t * ui2_Panel23;
extern lv_obj_t * ui2_Label33;
extern lv_obj_t * ui2_port1voltage1;
extern lv_obj_t * ui2_Container24;
extern lv_obj_t * ui2_Panel27;
extern lv_obj_t * ui2_Panel24;
extern lv_obj_t * ui2_Label34;
extern lv_obj_t * ui2_port1current1;
extern lv_obj_t * ui2_Container22;
extern lv_obj_t * ui2_Panel28;
extern lv_obj_t * ui2_Panel25;
extern lv_obj_t * ui2_Label35;
extern lv_obj_t * ui2_port1powerlabel;
extern lv_obj_t * ui2_Container21;
extern lv_obj_t * ui2_Panel31;
extern lv_obj_t * ui2_Label41;
extern lv_obj_t * ui2_Container32;
extern lv_obj_t * ui2_port1active;
extern lv_obj_t * ui2_Container33;
extern lv_obj_t * ui2_port1state;
extern lv_obj_t * ui2_Container18;
extern lv_obj_t * ui2_Panel29;
extern lv_obj_t * ui2_Label39;
extern lv_obj_t * ui2_Container25;
extern lv_obj_t * ui2_Label46;
extern lv_obj_t * ui2_port1protocol;
extern lv_obj_t * ui2_Container26;
extern lv_obj_t * ui2_Label47;
extern lv_obj_t * ui2_port1revision;
extern lv_obj_t * ui2_Container27;
extern lv_obj_t * ui2_Label48;
extern lv_obj_t * ui2_port1protocolpower;
extern lv_obj_t * ui2_Container23;
extern lv_obj_t * ui2_Container20;
extern lv_obj_t * ui2_Panel30;
extern lv_obj_t * ui2_Label40;
extern lv_obj_t * ui2_Container28;
extern lv_obj_t * ui2_Label44;
extern lv_obj_t * ui2_port1manufactuervid;
extern lv_obj_t * ui2_Container29;
extern lv_obj_t * ui2_Label58;
extern lv_obj_t * ui2_port1cablevid;
extern lv_obj_t * ui2_Container30;
extern lv_obj_t * ui2_Label60;
extern lv_obj_t * ui2_port1maxvbusvoltage;
extern lv_obj_t * ui2_Container31;
extern lv_obj_t * ui2_Label62;
extern lv_obj_t * ui2_port1maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

