// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui2.h"

lv_obj_t * ui2_totalpowerSCREEN = NULL;
lv_obj_t * ui2_Container1 = NULL;
lv_obj_t * ui2_Container86 = NULL;
lv_obj_t * ui2_totalpowerlabel = NULL;
lv_obj_t * ui2_Panel6 = NULL;
lv_obj_t * ui2_Panel1 = NULL;
lv_obj_t * ui2_Label6 = NULL;
lv_obj_t * ui2_Panel10 = NULL;
lv_obj_t * ui2_port1power = NULL;
lv_obj_t * ui2_Container8 = NULL;
lv_obj_t * ui2_Panel11 = NULL;
lv_obj_t * ui2_Label13 = NULL;
lv_obj_t * ui2_port1voltage = NULL;
lv_obj_t * ui2_Container9 = NULL;
lv_obj_t * ui2_Panel12 = NULL;
lv_obj_t * ui2_Label14 = NULL;
lv_obj_t * ui2_port1current = NULL;
lv_obj_t * ui2_Panel7 = NULL;
lv_obj_t * ui2_Panel3 = NULL;
lv_obj_t * ui2_Label8 = NULL;
lv_obj_t * ui2_Panel15 = NULL;
lv_obj_t * ui2_port2power = NULL;
lv_obj_t * ui2_Container10 = NULL;
lv_obj_t * ui2_Panel13 = NULL;
lv_obj_t * ui2_Label17 = NULL;
lv_obj_t * ui2_port2voltage = NULL;
lv_obj_t * ui2_Container11 = NULL;
lv_obj_t * ui2_Panel14 = NULL;
lv_obj_t * ui2_Label19 = NULL;
lv_obj_t * ui2_port2current = NULL;
lv_obj_t * ui2_Panel5 = NULL;
lv_obj_t * ui2_Panel2 = NULL;
lv_obj_t * ui2_Label7 = NULL;
lv_obj_t * ui2_Panel16 = NULL;
lv_obj_t * ui2_port3power = NULL;
lv_obj_t * ui2_Container12 = NULL;
lv_obj_t * ui2_Panel18 = NULL;
lv_obj_t * ui2_Label24 = NULL;
lv_obj_t * ui2_port3voltage = NULL;
lv_obj_t * ui2_Container13 = NULL;
lv_obj_t * ui2_Panel19 = NULL;
lv_obj_t * ui2_Label26 = NULL;
lv_obj_t * ui2_port3current = NULL;
lv_obj_t * ui2_Panel8 = NULL;
lv_obj_t * ui2_Panel4 = NULL;
lv_obj_t * ui2_Label9 = NULL;
lv_obj_t * ui2_Panel17 = NULL;
lv_obj_t * ui2_port4power = NULL;
lv_obj_t * ui2_Container14 = NULL;
lv_obj_t * ui2_Panel20 = NULL;
lv_obj_t * ui2_Label28 = NULL;
lv_obj_t * ui2_port4voltage = NULL;
lv_obj_t * ui2_Container15 = NULL;
lv_obj_t * ui2_Panel21 = NULL;
lv_obj_t * ui2_Label30 = NULL;
lv_obj_t * ui2_port4current = NULL;
lv_obj_t * ui2_Container17 = NULL;
// event funtions
void ui2_event_totalpowerSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_standbySCREEN, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui2_standbySCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui2_screen_change(&ui2_port1SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui2_port1SCREEN_screen_init);
    }
}

void ui2_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui2_screen_change(&ui2_port1SCREEN, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui2_port1SCREEN_screen_init);
    }
}

void ui2_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui2_screen_change(&ui2_port2SCREEN, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui2_port2SCREEN_screen_init);
    }
}

void ui2_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui2_screen_change(&ui2_port3SCREEN, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui2_port3SCREEN_screen_init);
    }
}

void ui2_event_Panel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui2_screen_change(&ui2_port4SCREEN, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui2_port4SCREEN_screen_init);
    }
}

// build funtions

void ui2_totalpowerSCREEN_screen_init(void)
{
    ui2_totalpowerSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_totalpowerSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Container1 = lv_obj_create(ui2_totalpowerSCREEN);
    lv_obj_remove_style_all(ui2_Container1);
    lv_obj_set_width(ui2_Container1, lv_pct(100));
    lv_obj_set_height(ui2_Container1, lv_pct(100));
    lv_obj_set_align(ui2_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui2_Container1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Container1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container86 = lv_obj_create(ui2_Container1);
    lv_obj_remove_style_all(ui2_Container86);
    lv_obj_set_width(ui2_Container86, lv_pct(100));
    lv_obj_set_height(ui2_Container86, lv_pct(30));
    lv_obj_set_align(ui2_Container86, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container86, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Container86, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container86, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_totalpowerlabel = lv_label_create(ui2_Container86);
    lv_obj_set_width(ui2_totalpowerlabel, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui2_totalpowerlabel, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui2_totalpowerlabel, -2);
    lv_obj_set_y(ui2_totalpowerlabel, -135);
    lv_obj_set_align(ui2_totalpowerlabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_totalpowerlabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_totalpowerlabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui2_totalpowerlabel, "160W");
    lv_obj_set_style_text_color(ui2_totalpowerlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_totalpowerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_totalpowerlabel, &ui2_font_ShuHei72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel6 = lv_obj_create(ui2_Container1);
    lv_obj_set_width(ui2_Panel6, 368);
    lv_obj_set_height(ui2_Panel6, lv_pct(17));
    lv_obj_set_x(ui2_Panel6, -6);
    lv_obj_set_y(ui2_Panel6, -97);
    lv_obj_set_align(ui2_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel6, lv_color_hex(0xE9AE0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel1 = lv_obj_create(ui2_Panel6);
    lv_obj_set_width(ui2_Panel1, 50);
    lv_obj_set_height(ui2_Panel1, 50);
    lv_obj_set_x(ui2_Panel1, -123);
    lv_obj_set_y(ui2_Panel1, -20);
    lv_obj_set_align(ui2_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel1, lv_color_hex(0xE9AE0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label6 = lv_label_create(ui2_Panel1);
    lv_obj_set_width(ui2_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label6, -148);
    lv_obj_set_y(ui2_Label6, -31);
    lv_obj_set_align(ui2_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label6, "C1");
    lv_obj_set_style_text_color(ui2_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label6, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel10 = lv_obj_create(ui2_Panel6);
    lv_obj_set_width(ui2_Panel10, 116);
    lv_obj_set_height(ui2_Panel10, 46);
    lv_obj_set_x(ui2_Panel10, -30);
    lv_obj_set_y(ui2_Panel10, -20);
    lv_obj_set_align(ui2_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port1power = lv_label_create(ui2_Panel10);
    lv_obj_set_width(ui2_port1power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1power, -31);
    lv_obj_set_y(ui2_port1power, -19);
    lv_obj_set_align(ui2_port1power, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1power, "140.0W");
    lv_obj_set_style_text_color(ui2_port1power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port1power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port1power, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container8 = lv_obj_create(ui2_Panel6);
    lv_obj_remove_style_all(ui2_Container8);
    lv_obj_set_width(ui2_Container8, 159);
    lv_obj_set_height(ui2_Container8, 50);
    lv_obj_set_x(ui2_Container8, -55);
    lv_obj_set_y(ui2_Container8, -83);
    lv_obj_set_align(ui2_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container8, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui2_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel11 = lv_obj_create(ui2_Container8);
    lv_obj_set_width(ui2_Panel11, lv_pct(84));
    lv_obj_set_height(ui2_Panel11, lv_pct(38));
    lv_obj_set_x(ui2_Panel11, 95);
    lv_obj_set_y(ui2_Panel11, -33);
    lv_obj_set_align(ui2_Panel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label13 = lv_label_create(ui2_Panel11);
    lv_obj_set_width(ui2_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label13, 62);
    lv_obj_set_y(ui2_Label13, -34);
    lv_obj_set_align(ui2_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label13, "vbus:");

    ui2_port1voltage = lv_label_create(ui2_Panel11);
    lv_obj_set_width(ui2_port1voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1voltage, 115);
    lv_obj_set_y(ui2_port1voltage, -34);
    lv_obj_set_align(ui2_port1voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1voltage, "27.654V");

    ui2_Container9 = lv_obj_create(ui2_Container8);
    lv_obj_remove_style_all(ui2_Container9);
    lv_obj_set_width(ui2_Container9, lv_pct(75));
    lv_obj_set_height(ui2_Container9, lv_pct(10));
    lv_obj_set_x(ui2_Container9, 93);
    lv_obj_set_y(ui2_Container9, -49);
    lv_obj_set_align(ui2_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel12 = lv_obj_create(ui2_Container8);
    lv_obj_set_width(ui2_Panel12, lv_pct(84));
    lv_obj_set_height(ui2_Panel12, lv_pct(38));
    lv_obj_set_x(ui2_Panel12, 95);
    lv_obj_set_y(ui2_Panel12, -9);
    lv_obj_set_align(ui2_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label14 = lv_label_create(ui2_Panel12);
    lv_obj_set_width(ui2_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label14, 54);
    lv_obj_set_y(ui2_Label14, -12);
    lv_obj_set_align(ui2_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label14, "ibus:");

    ui2_port1current = lv_label_create(ui2_Panel12);
    lv_obj_set_width(ui2_port1current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port1current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port1current, 113);
    lv_obj_set_y(ui2_port1current, -10);
    lv_obj_set_align(ui2_port1current, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port1current, "1.254A");

    ui2_Panel7 = lv_obj_create(ui2_Container1);
    lv_obj_set_width(ui2_Panel7, 368);
    lv_obj_set_height(ui2_Panel7, lv_pct(17));
    lv_obj_set_x(ui2_Panel7, -10);
    lv_obj_set_y(ui2_Panel7, -37);
    lv_obj_set_align(ui2_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel7, lv_color_hex(0xED1420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel3 = lv_obj_create(ui2_Panel7);
    lv_obj_set_width(ui2_Panel3, 50);
    lv_obj_set_height(ui2_Panel3, 50);
    lv_obj_set_x(ui2_Panel3, -116);
    lv_obj_set_y(ui2_Panel3, 115);
    lv_obj_set_align(ui2_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel3, lv_color_hex(0xED1420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel3, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label8 = lv_label_create(ui2_Panel3);
    lv_obj_set_width(ui2_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label8, -148);
    lv_obj_set_y(ui2_Label8, -31);
    lv_obj_set_align(ui2_Label8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Label8, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Label8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui2_Label8, "C2");
    lv_obj_set_style_text_color(ui2_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label8, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel15 = lv_obj_create(ui2_Panel7);
    lv_obj_set_width(ui2_Panel15, 116);
    lv_obj_set_height(ui2_Panel15, 46);
    lv_obj_set_x(ui2_Panel15, -30);
    lv_obj_set_y(ui2_Panel15, -20);
    lv_obj_set_align(ui2_Panel15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel15, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port2power = lv_label_create(ui2_Panel15);
    lv_obj_set_width(ui2_port2power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2power, -31);
    lv_obj_set_y(ui2_port2power, -19);
    lv_obj_set_align(ui2_port2power, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2power, "140.0W");
    lv_obj_set_style_text_color(ui2_port2power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port2power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port2power, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container10 = lv_obj_create(ui2_Panel7);
    lv_obj_remove_style_all(ui2_Container10);
    lv_obj_set_width(ui2_Container10, 159);
    lv_obj_set_height(ui2_Container10, 50);
    lv_obj_set_x(ui2_Container10, -55);
    lv_obj_set_y(ui2_Container10, -83);
    lv_obj_set_align(ui2_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container10, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui2_Container10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel13 = lv_obj_create(ui2_Container10);
    lv_obj_set_width(ui2_Panel13, lv_pct(84));
    lv_obj_set_height(ui2_Panel13, lv_pct(38));
    lv_obj_set_x(ui2_Panel13, 95);
    lv_obj_set_y(ui2_Panel13, -33);
    lv_obj_set_align(ui2_Panel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label17 = lv_label_create(ui2_Panel13);
    lv_obj_set_width(ui2_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label17, 62);
    lv_obj_set_y(ui2_Label17, -34);
    lv_obj_set_align(ui2_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label17, "vbus:");

    ui2_port2voltage = lv_label_create(ui2_Panel13);
    lv_obj_set_width(ui2_port2voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2voltage, 115);
    lv_obj_set_y(ui2_port2voltage, -34);
    lv_obj_set_align(ui2_port2voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2voltage, "27.654V");

    ui2_Container11 = lv_obj_create(ui2_Container10);
    lv_obj_remove_style_all(ui2_Container11);
    lv_obj_set_width(ui2_Container11, lv_pct(75));
    lv_obj_set_height(ui2_Container11, lv_pct(10));
    lv_obj_set_x(ui2_Container11, 93);
    lv_obj_set_y(ui2_Container11, -49);
    lv_obj_set_align(ui2_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel14 = lv_obj_create(ui2_Container10);
    lv_obj_set_width(ui2_Panel14, lv_pct(84));
    lv_obj_set_height(ui2_Panel14, lv_pct(38));
    lv_obj_set_x(ui2_Panel14, 95);
    lv_obj_set_y(ui2_Panel14, -9);
    lv_obj_set_align(ui2_Panel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label19 = lv_label_create(ui2_Panel14);
    lv_obj_set_width(ui2_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label19, 54);
    lv_obj_set_y(ui2_Label19, -12);
    lv_obj_set_align(ui2_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label19, "ibus:");

    ui2_port2current = lv_label_create(ui2_Panel14);
    lv_obj_set_width(ui2_port2current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port2current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port2current, 113);
    lv_obj_set_y(ui2_port2current, -10);
    lv_obj_set_align(ui2_port2current, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port2current, "1.254A");

    ui2_Panel5 = lv_obj_create(ui2_Container1);
    lv_obj_set_width(ui2_Panel5, 368);
    lv_obj_set_height(ui2_Panel5, lv_pct(17));
    lv_obj_set_x(ui2_Panel5, 113);
    lv_obj_set_y(ui2_Panel5, -23);
    lv_obj_set_align(ui2_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel5, lv_color_hex(0x733CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel2 = lv_obj_create(ui2_Panel5);
    lv_obj_set_width(ui2_Panel2, 50);
    lv_obj_set_height(ui2_Panel2, 50);
    lv_obj_set_x(ui2_Panel2, -124);
    lv_obj_set_y(ui2_Panel2, 189);
    lv_obj_set_align(ui2_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel2, lv_color_hex(0x733CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel2, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label7 = lv_label_create(ui2_Panel2);
    lv_obj_set_width(ui2_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label7, -148);
    lv_obj_set_y(ui2_Label7, -31);
    lv_obj_set_align(ui2_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label7, "C3");
    lv_obj_set_style_text_color(ui2_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label7, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel16 = lv_obj_create(ui2_Panel5);
    lv_obj_set_width(ui2_Panel16, 116);
    lv_obj_set_height(ui2_Panel16, 46);
    lv_obj_set_x(ui2_Panel16, -30);
    lv_obj_set_y(ui2_Panel16, -20);
    lv_obj_set_align(ui2_Panel16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel16, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port3power = lv_label_create(ui2_Panel16);
    lv_obj_set_width(ui2_port3power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3power, -31);
    lv_obj_set_y(ui2_port3power, -19);
    lv_obj_set_align(ui2_port3power, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3power, "140.0W");
    lv_obj_set_style_text_color(ui2_port3power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port3power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port3power, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container12 = lv_obj_create(ui2_Panel5);
    lv_obj_remove_style_all(ui2_Container12);
    lv_obj_set_width(ui2_Container12, 159);
    lv_obj_set_height(ui2_Container12, 50);
    lv_obj_set_x(ui2_Container12, -55);
    lv_obj_set_y(ui2_Container12, -83);
    lv_obj_set_align(ui2_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container12, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui2_Container12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel18 = lv_obj_create(ui2_Container12);
    lv_obj_set_width(ui2_Panel18, lv_pct(84));
    lv_obj_set_height(ui2_Panel18, lv_pct(38));
    lv_obj_set_x(ui2_Panel18, 95);
    lv_obj_set_y(ui2_Panel18, -33);
    lv_obj_set_align(ui2_Panel18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel18, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel18, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label24 = lv_label_create(ui2_Panel18);
    lv_obj_set_width(ui2_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label24, 62);
    lv_obj_set_y(ui2_Label24, -34);
    lv_obj_set_align(ui2_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label24, "vbus:");

    ui2_port3voltage = lv_label_create(ui2_Panel18);
    lv_obj_set_width(ui2_port3voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3voltage, 115);
    lv_obj_set_y(ui2_port3voltage, -34);
    lv_obj_set_align(ui2_port3voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3voltage, "27.654V");

    ui2_Container13 = lv_obj_create(ui2_Container12);
    lv_obj_remove_style_all(ui2_Container13);
    lv_obj_set_width(ui2_Container13, lv_pct(75));
    lv_obj_set_height(ui2_Container13, lv_pct(10));
    lv_obj_set_x(ui2_Container13, 93);
    lv_obj_set_y(ui2_Container13, -49);
    lv_obj_set_align(ui2_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel19 = lv_obj_create(ui2_Container12);
    lv_obj_set_width(ui2_Panel19, lv_pct(84));
    lv_obj_set_height(ui2_Panel19, lv_pct(38));
    lv_obj_set_x(ui2_Panel19, 95);
    lv_obj_set_y(ui2_Panel19, -9);
    lv_obj_set_align(ui2_Panel19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel19, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label26 = lv_label_create(ui2_Panel19);
    lv_obj_set_width(ui2_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label26, 54);
    lv_obj_set_y(ui2_Label26, -12);
    lv_obj_set_align(ui2_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label26, "ibus:");

    ui2_port3current = lv_label_create(ui2_Panel19);
    lv_obj_set_width(ui2_port3current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port3current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port3current, 113);
    lv_obj_set_y(ui2_port3current, -10);
    lv_obj_set_align(ui2_port3current, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port3current, "1.254A");

    ui2_Panel8 = lv_obj_create(ui2_Container1);
    lv_obj_set_width(ui2_Panel8, 368);
    lv_obj_set_height(ui2_Panel8, lv_pct(17));
    lv_obj_set_x(ui2_Panel8, -94);
    lv_obj_set_y(ui2_Panel8, -44);
    lv_obj_set_align(ui2_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui2_Panel8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Panel8, lv_color_hex(0x4B640D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel4 = lv_obj_create(ui2_Panel8);
    lv_obj_set_width(ui2_Panel4, 50);
    lv_obj_set_height(ui2_Panel4, 50);
    lv_obj_set_x(ui2_Panel4, -115);
    lv_obj_set_y(ui2_Panel4, 44);
    lv_obj_set_align(ui2_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui2_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel4, lv_color_hex(0x4B640D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel4, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui2_Panel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui2_Panel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui2_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label9 = lv_label_create(ui2_Panel4);
    lv_obj_set_width(ui2_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label9, -148);
    lv_obj_set_y(ui2_Label9, -31);
    lv_obj_set_align(ui2_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label9, "C4");
    lv_obj_set_style_text_color(ui2_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Label9, &ui2_font_ShuHei30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Panel17 = lv_obj_create(ui2_Panel8);
    lv_obj_set_width(ui2_Panel17, 116);
    lv_obj_set_height(ui2_Panel17, 46);
    lv_obj_set_x(ui2_Panel17, -30);
    lv_obj_set_y(ui2_Panel17, -20);
    lv_obj_set_align(ui2_Panel17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel17, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel17, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_port4power = lv_label_create(ui2_Panel17);
    lv_obj_set_width(ui2_port4power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4power, -31);
    lv_obj_set_y(ui2_port4power, -19);
    lv_obj_set_align(ui2_port4power, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4power, "140.0W");
    lv_obj_set_style_text_color(ui2_port4power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_port4power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_port4power, &ui2_font_ShuHei26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Container14 = lv_obj_create(ui2_Panel8);
    lv_obj_remove_style_all(ui2_Container14);
    lv_obj_set_width(ui2_Container14, 159);
    lv_obj_set_height(ui2_Container14, 50);
    lv_obj_set_x(ui2_Container14, -55);
    lv_obj_set_y(ui2_Container14, -83);
    lv_obj_set_align(ui2_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Container14, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui2_Container14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel20 = lv_obj_create(ui2_Container14);
    lv_obj_set_width(ui2_Panel20, lv_pct(84));
    lv_obj_set_height(ui2_Panel20, lv_pct(38));
    lv_obj_set_x(ui2_Panel20, 95);
    lv_obj_set_y(ui2_Panel20, -33);
    lv_obj_set_align(ui2_Panel20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label28 = lv_label_create(ui2_Panel20);
    lv_obj_set_width(ui2_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label28, 62);
    lv_obj_set_y(ui2_Label28, -34);
    lv_obj_set_align(ui2_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label28, "vbus:");

    ui2_port4voltage = lv_label_create(ui2_Panel20);
    lv_obj_set_width(ui2_port4voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4voltage, 115);
    lv_obj_set_y(ui2_port4voltage, -34);
    lv_obj_set_align(ui2_port4voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4voltage, "27.654V");

    ui2_Container15 = lv_obj_create(ui2_Container14);
    lv_obj_remove_style_all(ui2_Container15);
    lv_obj_set_width(ui2_Container15, lv_pct(75));
    lv_obj_set_height(ui2_Container15, lv_pct(10));
    lv_obj_set_x(ui2_Container15, 93);
    lv_obj_set_y(ui2_Container15, -49);
    lv_obj_set_align(ui2_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui2_Panel21 = lv_obj_create(ui2_Container14);
    lv_obj_set_width(ui2_Panel21, lv_pct(84));
    lv_obj_set_height(ui2_Panel21, lv_pct(38));
    lv_obj_set_x(ui2_Panel21, 95);
    lv_obj_set_y(ui2_Panel21, -9);
    lv_obj_set_align(ui2_Panel21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui2_Panel21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui2_Panel21, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui2_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui2_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui2_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label30 = lv_label_create(ui2_Panel21);
    lv_obj_set_width(ui2_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label30, 54);
    lv_obj_set_y(ui2_Label30, -12);
    lv_obj_set_align(ui2_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_Label30, "ibus:");

    ui2_port4current = lv_label_create(ui2_Panel21);
    lv_obj_set_width(ui2_port4current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_port4current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_port4current, 113);
    lv_obj_set_y(ui2_port4current, -10);
    lv_obj_set_align(ui2_port4current, LV_ALIGN_CENTER);
    lv_label_set_text(ui2_port4current, "1.254A");

    ui2_Container17 = lv_obj_create(ui2_Container1);
    lv_obj_remove_style_all(ui2_Container17);
    lv_obj_set_width(ui2_Container17, lv_pct(100));
    lv_obj_set_height(ui2_Container17, lv_pct(0));
    lv_obj_set_align(ui2_Container17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui2_Panel1, ui2_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui2_Panel3, ui2_event_Panel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui2_Panel2, ui2_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui2_Panel4, ui2_event_Panel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui2_totalpowerSCREEN, ui2_event_totalpowerSCREEN, LV_EVENT_ALL, NULL);

}

void ui2_totalpowerSCREEN_screen_destroy(void)
{
    if(ui2_totalpowerSCREEN) lv_obj_del(ui2_totalpowerSCREEN);

    // NULL screen variables
    ui2_totalpowerSCREEN = NULL;
    ui2_Container1 = NULL;
    ui2_Panel6 = NULL;
    ui2_Panel1 = NULL;
    ui2_Label6 = NULL;
    ui2_Panel10 = NULL;
    ui2_port1power = NULL;
    ui2_Container8 = NULL;
    ui2_Panel11 = NULL;
    ui2_Label13 = NULL;
    ui2_port1voltage = NULL;
    ui2_Container9 = NULL;
    ui2_Panel12 = NULL;
    ui2_Label14 = NULL;
    ui2_port1current = NULL;
    ui2_Panel7 = NULL;
    ui2_Panel3 = NULL;
    ui2_Label8 = NULL;
    ui2_Panel15 = NULL;
    ui2_port2power = NULL;
    ui2_Container10 = NULL;
    ui2_Panel13 = NULL;
    ui2_Label17 = NULL;
    ui2_port2voltage = NULL;
    ui2_Container11 = NULL;
    ui2_Panel14 = NULL;
    ui2_Label19 = NULL;
    ui2_port2current = NULL;
    ui2_Panel5 = NULL;
    ui2_Panel2 = NULL;
    ui2_Label7 = NULL;
    ui2_Panel16 = NULL;
    ui2_port3power = NULL;
    ui2_Container12 = NULL;
    ui2_Panel18 = NULL;
    ui2_Label24 = NULL;
    ui2_port3voltage = NULL;
    ui2_Container13 = NULL;
    ui2_Panel19 = NULL;
    ui2_Label26 = NULL;
    ui2_port3current = NULL;
    ui2_Panel8 = NULL;
    ui2_Panel4 = NULL;
    ui2_Label9 = NULL;
    ui2_Panel17 = NULL;
    ui2_port4power = NULL;
    ui2_Container14 = NULL;
    ui2_Panel20 = NULL;
    ui2_Label28 = NULL;
    ui2_port4voltage = NULL;
    ui2_Container15 = NULL;
    ui2_Panel21 = NULL;
    ui2_Label30 = NULL;
    ui2_port4current = NULL;
    ui2_Container17 = NULL;
    ui2_totalpowerlabel = NULL;

}

void ui2_totalpowerSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
