// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui2_TOTALPOWERSCREEN_H
#define ui2_TOTALPOWERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui2_totalpowerSCREEN
extern void ui2_totalpowerSCREEN_screen_init(void);
extern void ui2_totalpowerSCREEN_screen_destroy(void);
extern void ui2_totalpowerSCREEN_screen_relocalize(void);
extern void ui2_event_totalpowerSCREEN(lv_event_t * e);
extern lv_obj_t * ui2_totalpowerSCREEN;
extern lv_obj_t * ui2_Container1;
extern lv_obj_t * ui2_Panel6;
extern void ui2_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui2_Panel1;
extern lv_obj_t * ui2_Label6;
extern lv_obj_t * ui2_Panel10;
extern lv_obj_t * ui2_port1power;
extern lv_obj_t * ui2_Container8;
extern lv_obj_t * ui2_Panel11;
extern lv_obj_t * ui2_Label13;
extern lv_obj_t * ui2_port1voltage;
extern lv_obj_t * ui2_Container9;
extern lv_obj_t * ui2_Panel12;
extern lv_obj_t * ui2_Label14;
extern lv_obj_t * ui2_port1current;
extern lv_obj_t * ui2_Panel7;
extern void ui2_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui2_Panel3;
extern lv_obj_t * ui2_Label8;
extern lv_obj_t * ui2_Panel15;
extern lv_obj_t * ui2_port2power;
extern lv_obj_t * ui2_Container10;
extern lv_obj_t * ui2_Panel13;
extern lv_obj_t * ui2_Label17;
extern lv_obj_t * ui2_port2voltage;
extern lv_obj_t * ui2_Container11;
extern lv_obj_t * ui2_Panel14;
extern lv_obj_t * ui2_Label19;
extern lv_obj_t * ui2_port2current;
extern lv_obj_t * ui2_Panel5;
extern void ui2_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui2_Panel2;
extern lv_obj_t * ui2_Label7;
extern lv_obj_t * ui2_Panel16;
extern lv_obj_t * ui2_port3power;
extern lv_obj_t * ui2_Container12;
extern lv_obj_t * ui2_Panel18;
extern lv_obj_t * ui2_Label24;
extern lv_obj_t * ui2_port3voltage;
extern lv_obj_t * ui2_Container13;
extern lv_obj_t * ui2_Panel19;
extern lv_obj_t * ui2_Label26;
extern lv_obj_t * ui2_port3current;
extern lv_obj_t * ui2_Panel8;
extern void ui2_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui2_Panel4;
extern lv_obj_t * ui2_Label9;
extern lv_obj_t * ui2_Panel17;
extern lv_obj_t * ui2_port4power;
extern lv_obj_t * ui2_Container14;
extern lv_obj_t * ui2_Panel20;
extern lv_obj_t * ui2_Label28;
extern lv_obj_t * ui2_port4voltage;
extern lv_obj_t * ui2_Container15;
extern lv_obj_t * ui2_Panel21;
extern lv_obj_t * ui2_Label30;
extern lv_obj_t * ui2_port4current;
extern lv_obj_t * ui2_Container17;
extern lv_obj_t * ui2_totalpowerlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

