// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui2_STANDBYSCREEN_H
#define ui2_STANDBYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui2_standbySCREEN
extern void ui2_standbySCREEN_screen_init(void);
extern void ui2_standbySCREEN_screen_destroy(void);
extern void ui2_standbySCREEN_screen_relocalize(void);
extern void ui2_event_standbySCREEN(lv_event_t * e);
extern lv_obj_t * ui2_standbySCREEN;
extern lv_obj_t * ui2_Container2;
extern lv_obj_t * ui2_Container3;
extern lv_obj_t * ui2_timeLabel;
extern lv_obj_t * ui2_Container4;
extern lv_obj_t * ui2_dataLabel;
extern lv_obj_t * ui2_Container5;
extern lv_obj_t * ui2_temperatureLabel;
extern lv_obj_t * ui2_Label10;
extern lv_obj_t * ui2_weatherLabel;
extern lv_obj_t * ui2_Container6;
extern lv_obj_t * ui2_weekLabel;
extern lv_obj_t * ui2_Container7;
extern lv_obj_t * ui2_Panel9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

