// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PORT2SCREEN22_H
#define UI_PORT2SCREEN22_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_port2SCREEN22
extern void ui_port2SCREEN22_screen_init(void);
extern void ui_port2SCREEN22_screen_destroy(void);
extern void ui_port2SCREEN22_screen_relocalize(void);
extern void ui_event_port2SCREEN22(lv_event_t * e);
extern lv_obj_t * ui_port2SCREEN22;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_Container44;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_port2state;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_port2protocol;
extern lv_obj_t * ui_Container47;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_port2manufactuervid;
extern lv_obj_t * ui_Container48;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_port2cablevid;
extern lv_obj_t * ui_Container49;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_port2maxvbusvoltage;
extern lv_obj_t * ui_Container50;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_port2maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

