// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PROT3SCREEN_H
#define UI_PROT3SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_prot3SCREEN
extern void ui_prot3SCREEN_screen_init(void);
extern void ui_prot3SCREEN_screen_destroy(void);
extern void ui_prot3SCREEN_screen_relocalize(void);
extern void ui_event_prot3SCREEN(lv_event_t * e);
extern lv_obj_t * ui_prot3SCREEN;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_port1voltage2;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_port1current2;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_port1powerlabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

