// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_prot2SCREEN = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_port2powerpagelabel = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_port2voltage = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_port2current = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_port2powerlabel = NULL;
// event funtions
void ui_event_prot2SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot3SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot3SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot1SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_prot1SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_port2SCREEN22, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_port2SCREEN22_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_totalpowerSCREEN_screen_init);
    }
}

// build funtions

void ui_prot2SCREEN_screen_init(void)
{
    ui_prot2SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_prot2SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container17 = lv_obj_create(ui_prot2SCREEN);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, lv_pct(100));
    lv_obj_set_height(ui_Container17, lv_pct(100));
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container17, &ui_img_919862230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 246);
    lv_obj_set_height(ui_Container18, 22);
    lv_obj_set_x(ui_Container18, -30);
    lv_obj_set_y(ui_Container18, -174);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port2powerpagelabel = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_port2powerpagelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2powerpagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2powerpagelabel, -5);
    lv_obj_set_y(ui_port2powerpagelabel, -193);
    lv_obj_set_align(ui_port2powerpagelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2powerpagelabel, "C2端口");
    lv_obj_set_style_text_color(ui_port2powerpagelabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2powerpagelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2powerpagelabel, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 246);
    lv_obj_set_height(ui_Container19, 15);
    lv_obj_set_x(ui_Container19, -30);
    lv_obj_set_y(ui_Container19, -174);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container20 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 260);
    lv_obj_set_height(ui_Container20, 45);
    lv_obj_set_x(ui_Container20, -152);
    lv_obj_set_y(ui_Container20, -127);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -86);
    lv_obj_set_y(ui_Label6, -125);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "电压：");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2voltage = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_port2voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2voltage, 33);
    lv_obj_set_y(ui_port2voltage, -126);
    lv_obj_set_align(ui_port2voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2voltage, "27.896V");
    lv_obj_set_style_text_color(ui_port2voltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2voltage, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 260);
    lv_obj_set_height(ui_Container21, 45);
    lv_obj_set_x(ui_Container21, -100);
    lv_obj_set_y(ui_Container21, -131);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -88);
    lv_obj_set_y(ui_Label7, -68);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "电流：");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2current = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_port2current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2current, 26);
    lv_obj_set_y(ui_port2current, -71);
    lv_obj_set_align(ui_port2current, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port2current, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_port2current, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_port2current, "3.597A");
    lv_obj_set_style_text_color(ui_port2current, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2current, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 260);
    lv_obj_set_height(ui_Container22, 45);
    lv_obj_set_x(ui_Container22, -116);
    lv_obj_set_y(ui_Container22, -170);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -91);
    lv_obj_set_y(ui_Label8, -21);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "功率：");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2powerlabel = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_port2powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2powerlabel, 41);
    lv_obj_set_y(ui_port2powerlabel, -17);
    lv_obj_set_align(ui_port2powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2powerlabel, "37.592W");
    lv_obj_set_style_text_color(ui_port2powerlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2powerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2powerlabel, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_prot2SCREEN, ui_event_prot2SCREEN, LV_EVENT_ALL, NULL);

}

void ui_prot2SCREEN_screen_destroy(void)
{
    if(ui_prot2SCREEN) lv_obj_del(ui_prot2SCREEN);

    // NULL screen variables
    ui_prot2SCREEN = NULL;
    ui_Container17 = NULL;
    ui_Container18 = NULL;
    ui_port2powerpagelabel = NULL;
    ui_Container19 = NULL;
    ui_Container20 = NULL;
    ui_Label6 = NULL;
    ui_port2voltage = NULL;
    ui_Container21 = NULL;
    ui_Label7 = NULL;
    ui_port2current = NULL;
    ui_Container22 = NULL;
    ui_Label8 = NULL;
    ui_port2powerlabel = NULL;

}

void ui_prot2SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
