// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PROT1SCREEN_H
#define UI_PROT1SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_prot1SCREEN
extern void ui_prot1SCREEN_screen_init(void);
extern void ui_prot1SCREEN_screen_destroy(void);
extern void ui_prot1SCREEN_screen_relocalize(void);
extern void ui_event_prot1SCREEN(lv_event_t * e);
extern lv_obj_t * ui_prot1SCREEN;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_port1powerpagelabel;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_port1voltage;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_port1current;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_port1powerlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

