// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_port3SCREEN32 = NULL;
lv_obj_t * ui_Container51 = NULL;
lv_obj_t * ui_Container52 = NULL;
lv_obj_t * ui_Container53 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_port1state2 = NULL;
lv_obj_t * ui_Container54 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_port1protocol2 = NULL;
lv_obj_t * ui_Container55 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Container56 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Container57 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Container58 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_Label56 = NULL;
// event funtions
void ui_event_port3SCREEN32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot3SCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_prot3SCREEN_screen_init);
    }
}

// build funtions

void ui_port3SCREEN32_screen_init(void)
{
    ui_port3SCREEN32 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_port3SCREEN32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container51 = lv_obj_create(ui_port3SCREEN32);
    lv_obj_remove_style_all(ui_Container51);
    lv_obj_set_width(ui_Container51, 368);
    lv_obj_set_height(ui_Container51, 448);
    lv_obj_set_align(ui_Container51, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container51, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container51, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container51, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container51, &ui_img_934861631, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container52 = lv_obj_create(ui_Container51);
    lv_obj_remove_style_all(ui_Container52);
    lv_obj_set_width(ui_Container52, 309);
    lv_obj_set_height(ui_Container52, 23);
    lv_obj_set_x(ui_Container52, -100);
    lv_obj_set_y(ui_Container52, -217);
    lv_obj_set_align(ui_Container52, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container52, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container53 = lv_obj_create(ui_Container51);
    lv_obj_remove_style_all(ui_Container53);
    lv_obj_set_width(ui_Container53, 340);
    lv_obj_set_height(ui_Container53, 30);
    lv_obj_set_x(ui_Container53, 11);
    lv_obj_set_y(ui_Container53, -105);
    lv_obj_set_align(ui_Container53, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container53, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container53, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container53, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label47 = lv_label_create(ui_Container53);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -82);
    lv_obj_set_y(ui_Label47, -146);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "状态：");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1state2 = lv_label_create(ui_Container53);
    lv_obj_set_width(ui_port1state2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1state2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1state2, 38);
    lv_obj_set_y(ui_port1state2, -149);
    lv_obj_set_align(ui_port1state2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1state2, "未连接");
    lv_obj_set_style_text_color(ui_port1state2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1state2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1state2, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container54 = lv_obj_create(ui_Container53);
    lv_obj_remove_style_all(ui_Container54);
    lv_obj_set_width(ui_Container54, 30);
    lv_obj_set_height(ui_Container54, 17);
    lv_obj_set_x(ui_Container54, -82);
    lv_obj_set_y(ui_Container54, -138);
    lv_obj_set_align(ui_Container54, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container54, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label48 = lv_label_create(ui_Container53);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -87);
    lv_obj_set_y(ui_Label48, -93);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "协议：");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1protocol2 = lv_label_create(ui_Container53);
    lv_obj_set_width(ui_port1protocol2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1protocol2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1protocol2, 27);
    lv_obj_set_y(ui_port1protocol2, -94);
    lv_obj_set_align(ui_port1protocol2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1protocol2, "未知");
    lv_obj_set_style_text_color(ui_port1protocol2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1protocol2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1protocol2, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container55 = lv_obj_create(ui_Container51);
    lv_obj_remove_style_all(ui_Container55);
    lv_obj_set_width(ui_Container55, 340);
    lv_obj_set_height(ui_Container55, 30);
    lv_obj_set_x(ui_Container55, -75);
    lv_obj_set_y(ui_Container55, -112);
    lv_obj_set_align(ui_Container55, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container55, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container55, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container55, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label49 = lv_label_create(ui_Container55);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -76);
    lv_obj_set_y(ui_Label49, -109);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "制造商：");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Container55);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, 26);
    lv_obj_set_y(ui_Label50, -122);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "未知");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container56 = lv_obj_create(ui_Container51);
    lv_obj_remove_style_all(ui_Container56);
    lv_obj_set_width(ui_Container56, 340);
    lv_obj_set_height(ui_Container56, 30);
    lv_obj_set_x(ui_Container56, -82);
    lv_obj_set_y(ui_Container56, -127);
    lv_obj_set_align(ui_Container56, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container56, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container56, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container56, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label51 = lv_label_create(ui_Container56);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -73);
    lv_obj_set_y(ui_Label51, -69);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "线缆厂商：");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Container56);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 93);
    lv_obj_set_y(ui_Label52, -78);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "未知");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container57 = lv_obj_create(ui_Container51);
    lv_obj_remove_style_all(ui_Container57);
    lv_obj_set_width(ui_Container57, 340);
    lv_obj_set_height(ui_Container57, 30);
    lv_obj_set_x(ui_Container57, -113);
    lv_obj_set_y(ui_Container57, -67);
    lv_obj_set_align(ui_Container57, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container57, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container57, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container57, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label53 = lv_label_create(ui_Container57);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -127);
    lv_obj_set_y(ui_Label53, -87);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "最大电压：");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Container57);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -38);
    lv_obj_set_y(ui_Label54, -85);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "--");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container58 = lv_obj_create(ui_Container57);
    lv_obj_remove_style_all(ui_Container58);
    lv_obj_set_width(ui_Container58, 18);
    lv_obj_set_height(ui_Container58, 9);
    lv_obj_set_x(ui_Container58, -50);
    lv_obj_set_y(ui_Container58, -101);
    lv_obj_set_align(ui_Container58, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container58, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label55 = lv_label_create(ui_Container57);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 77);
    lv_obj_set_y(ui_Label55, -85);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "最大电流：");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Container57);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 85);
    lv_obj_set_y(ui_Label56, -93);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "--");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_port3SCREEN32, ui_event_port3SCREEN32, LV_EVENT_ALL, NULL);

}

void ui_port3SCREEN32_screen_destroy(void)
{
    if(ui_port3SCREEN32) lv_obj_del(ui_port3SCREEN32);

    // NULL screen variables
    ui_port3SCREEN32 = NULL;
    ui_Container51 = NULL;
    ui_Container52 = NULL;
    ui_Container53 = NULL;
    ui_Label47 = NULL;
    ui_port1state2 = NULL;
    ui_Container54 = NULL;
    ui_Label48 = NULL;
    ui_port1protocol2 = NULL;
    ui_Container55 = NULL;
    ui_Label49 = NULL;
    ui_Label50 = NULL;
    ui_Container56 = NULL;
    ui_Label51 = NULL;
    ui_Label52 = NULL;
    ui_Container57 = NULL;
    ui_Label53 = NULL;
    ui_Label54 = NULL;
    ui_Container58 = NULL;
    ui_Label55 = NULL;
    ui_Label56 = NULL;

}

void ui_port3SCREEN32_screen_relocalize(void)
{
    // label widgets on screen

}
