// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PORT1SCREEN12_H
#define UI_PORT1SCREEN12_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_port1SCREEN12
extern void ui_port1SCREEN12_screen_init(void);
extern void ui_port1SCREEN12_screen_destroy(void);
extern void ui_port1SCREEN12_screen_relocalize(void);
extern void ui_event_port1SCREEN12(lv_event_t * e);
extern lv_obj_t * ui_port1SCREEN12;
extern lv_obj_t * ui_Container35;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_port1state;
extern lv_obj_t * ui_Container38;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_port1protocol;
extern lv_obj_t * ui_Container37;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_port1manufactuervid;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_port1cablevid;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_port1maxvbusvoltage;
extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_port1maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

