// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PORT4SCREEN42_H
#define UI_PORT4SCREEN42_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_port4SCREEN42
extern void ui_port4SCREEN42_screen_init(void);
extern void ui_port4SCREEN42_screen_destroy(void);
extern void ui_port4SCREEN42_screen_relocalize(void);
extern void ui_event_port4SCREEN42(lv_event_t * e);
extern lv_obj_t * ui_port4SCREEN42;
extern lv_obj_t * ui_Container59;
extern lv_obj_t * ui_Container60;
extern lv_obj_t * ui_Container61;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_port4state;
extern lv_obj_t * ui_Container62;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_port4protocol;
extern lv_obj_t * ui_Container63;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_port4manufactuervid;
extern lv_obj_t * ui_Container64;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_port4cablevid;
extern lv_obj_t * ui_Container65;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_port4maxvbusvoltage;
extern lv_obj_t * ui_Container66;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_port4maxvbuscurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

