// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_prot1SCREEN = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_port1powerpagelabel = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_port1voltage = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_port1current = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_port1powerlabel = NULL;
// event funtions
void ui_event_prot1SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot2SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot2SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_totalpowerSCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_port1SCREEN12, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_port1SCREEN12_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_totalpowerSCREEN_screen_init);
    }
}

// build funtions

void ui_prot1SCREEN_screen_init(void)
{
    ui_prot1SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_prot1SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_prot1SCREEN);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container6, &ui_img_919862230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 246);
    lv_obj_set_height(ui_Container15, 22);
    lv_obj_set_x(ui_Container15, -30);
    lv_obj_set_y(ui_Container15, -174);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port1powerpagelabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_port1powerpagelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1powerpagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1powerpagelabel, -5);
    lv_obj_set_y(ui_port1powerpagelabel, -193);
    lv_obj_set_align(ui_port1powerpagelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1powerpagelabel, "C1端口");
    lv_obj_set_style_text_color(ui_port1powerpagelabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1powerpagelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1powerpagelabel, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 246);
    lv_obj_set_height(ui_Container16, 15);
    lv_obj_set_x(ui_Container16, -30);
    lv_obj_set_y(ui_Container16, -174);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 260);
    lv_obj_set_height(ui_Container7, 45);
    lv_obj_set_x(ui_Container7, -152);
    lv_obj_set_y(ui_Container7, -127);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -86);
    lv_obj_set_y(ui_Label14, -125);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "电压：");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1voltage = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_port1voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1voltage, 33);
    lv_obj_set_y(ui_port1voltage, -126);
    lv_obj_set_align(ui_port1voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1voltage, "19.684V");
    lv_obj_set_style_text_color(ui_port1voltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1voltage, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 260);
    lv_obj_set_height(ui_Container13, 45);
    lv_obj_set_x(ui_Container13, -100);
    lv_obj_set_y(ui_Container13, -131);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -88);
    lv_obj_set_y(ui_Label15, -68);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "电流：");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1current = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_port1current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1current, 26);
    lv_obj_set_y(ui_port1current, -71);
    lv_obj_set_align(ui_port1current, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port1current, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_port1current, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_port1current, "3.154A");
    lv_obj_set_style_text_color(ui_port1current, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1current, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 260);
    lv_obj_set_height(ui_Container14, 45);
    lv_obj_set_x(ui_Container14, -116);
    lv_obj_set_y(ui_Container14, -170);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -91);
    lv_obj_set_y(ui_Label16, -21);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "功率：");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1powerlabel = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_port1powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1powerlabel, 41);
    lv_obj_set_y(ui_port1powerlabel, -17);
    lv_obj_set_align(ui_port1powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1powerlabel, "60.147W");
    lv_obj_set_style_text_color(ui_port1powerlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1powerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1powerlabel, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_prot1SCREEN, ui_event_prot1SCREEN, LV_EVENT_ALL, NULL);

}

void ui_prot1SCREEN_screen_destroy(void)
{
    if(ui_prot1SCREEN) lv_obj_del(ui_prot1SCREEN);

    // NULL screen variables
    ui_prot1SCREEN = NULL;
    ui_Container6 = NULL;
    ui_Container15 = NULL;
    ui_port1powerpagelabel = NULL;
    ui_Container16 = NULL;
    ui_Container7 = NULL;
    ui_Label14 = NULL;
    ui_port1voltage = NULL;
    ui_Container13 = NULL;
    ui_Label15 = NULL;
    ui_port1current = NULL;
    ui_Container14 = NULL;
    ui_Label16 = NULL;
    ui_port1powerlabel = NULL;

}

void ui_prot1SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
