// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_prot3SCREEN = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_port3powerpagelabel = NULL;
lv_obj_t * ui_Container25 = NULL;
lv_obj_t * ui_Container26 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_port3voltage = NULL;
lv_obj_t * ui_Container27 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_port3current = NULL;
lv_obj_t * ui_Container28 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_port3powerlabel = NULL;
// event funtions
void ui_event_prot3SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot4SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot4SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot2SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_prot2SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_port3SCREEN32, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_port3SCREEN32_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_totalpowerSCREEN_screen_init);
    }
}

// build funtions

void ui_prot3SCREEN_screen_init(void)
{
    ui_prot3SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_prot3SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container23 = lv_obj_create(ui_prot3SCREEN);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, lv_pct(100));
    lv_obj_set_height(ui_Container23, lv_pct(100));
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container23, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container23, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container23, &ui_img_919862230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container24 = lv_obj_create(ui_Container23);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 246);
    lv_obj_set_height(ui_Container24, 22);
    lv_obj_set_x(ui_Container24, -30);
    lv_obj_set_y(ui_Container24, -174);
    lv_obj_set_align(ui_Container24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port3powerpagelabel = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_port3powerpagelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port3powerpagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port3powerpagelabel, -5);
    lv_obj_set_y(ui_port3powerpagelabel, -193);
    lv_obj_set_align(ui_port3powerpagelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port3powerpagelabel, "C3端口");
    lv_obj_set_style_text_color(ui_port3powerpagelabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port3powerpagelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port3powerpagelabel, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container25 = lv_obj_create(ui_Container23);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 246);
    lv_obj_set_height(ui_Container25, 15);
    lv_obj_set_x(ui_Container25, -30);
    lv_obj_set_y(ui_Container25, -174);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container26 = lv_obj_create(ui_Container23);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, 260);
    lv_obj_set_height(ui_Container26, 45);
    lv_obj_set_x(ui_Container26, -152);
    lv_obj_set_y(ui_Container26, -127);
    lv_obj_set_align(ui_Container26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container26, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -86);
    lv_obj_set_y(ui_Label11, -125);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "电压：");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port3voltage = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_port3voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port3voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port3voltage, 33);
    lv_obj_set_y(ui_port3voltage, -126);
    lv_obj_set_align(ui_port3voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port3voltage, "0.000V");
    lv_obj_set_style_text_color(ui_port3voltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port3voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port3voltage, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container27 = lv_obj_create(ui_Container23);
    lv_obj_remove_style_all(ui_Container27);
    lv_obj_set_width(ui_Container27, 260);
    lv_obj_set_height(ui_Container27, 45);
    lv_obj_set_x(ui_Container27, -100);
    lv_obj_set_y(ui_Container27, -131);
    lv_obj_set_align(ui_Container27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container27, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Container27);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -88);
    lv_obj_set_y(ui_Label12, -68);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "电流：");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port3current = lv_label_create(ui_Container27);
    lv_obj_set_width(ui_port3current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port3current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port3current, 26);
    lv_obj_set_y(ui_port3current, -71);
    lv_obj_set_align(ui_port3current, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port3current, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_port3current, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_port3current, "0.000A");
    lv_obj_set_style_text_color(ui_port3current, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port3current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port3current, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container28 = lv_obj_create(ui_Container23);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 260);
    lv_obj_set_height(ui_Container28, 45);
    lv_obj_set_x(ui_Container28, -116);
    lv_obj_set_y(ui_Container28, -170);
    lv_obj_set_align(ui_Container28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container28, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -91);
    lv_obj_set_y(ui_Label13, -21);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "功率：");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port3powerlabel = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_port3powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port3powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port3powerlabel, 41);
    lv_obj_set_y(ui_port3powerlabel, -17);
    lv_obj_set_align(ui_port3powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port3powerlabel, "0.000W");
    lv_obj_set_style_text_color(ui_port3powerlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port3powerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port3powerlabel, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_prot3SCREEN, ui_event_prot3SCREEN, LV_EVENT_ALL, NULL);

}

void ui_prot3SCREEN_screen_destroy(void)
{
    if(ui_prot3SCREEN) lv_obj_del(ui_prot3SCREEN);

    // NULL screen variables
    ui_prot3SCREEN = NULL;
    ui_Container23 = NULL;
    ui_Container24 = NULL;
    ui_port3powerpagelabel = NULL;
    ui_Container25 = NULL;
    ui_Container26 = NULL;
    ui_Label11 = NULL;
    ui_port3voltage = NULL;
    ui_Container27 = NULL;
    ui_Label12 = NULL;
    ui_port3current = NULL;
    ui_Container28 = NULL;
    ui_Label13 = NULL;
    ui_port3powerlabel = NULL;

}

void ui_prot3SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
