// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_port4SCREEN42 = NULL;
lv_obj_t * ui_Container59 = NULL;
lv_obj_t * ui_Container60 = NULL;
lv_obj_t * ui_Container61 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_port4state = NULL;
lv_obj_t * ui_Container62 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_port4protocol = NULL;
lv_obj_t * ui_Container63 = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_port4manufactuervid = NULL;
lv_obj_t * ui_Container64 = NULL;
lv_obj_t * ui_Label61 = NULL;
lv_obj_t * ui_port4cablevid = NULL;
lv_obj_t * ui_Container65 = NULL;
lv_obj_t * ui_Label63 = NULL;
lv_obj_t * ui_port4maxvbusvoltage = NULL;
lv_obj_t * ui_Container66 = NULL;
lv_obj_t * ui_Label65 = NULL;
lv_obj_t * ui_port4maxvbuscurrent = NULL;
// event funtions
void ui_event_port4SCREEN42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot4SCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_prot4SCREEN_screen_init);
    }
}

// build funtions

void ui_port4SCREEN42_screen_init(void)
{
    ui_port4SCREEN42 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_port4SCREEN42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container59 = lv_obj_create(ui_port4SCREEN42);
    lv_obj_remove_style_all(ui_Container59);
    lv_obj_set_width(ui_Container59, lv_pct(100));
    lv_obj_set_height(ui_Container59, lv_pct(100));
    lv_obj_set_align(ui_Container59, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container59, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container59, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container59, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container59, &ui_img_934861631, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container60 = lv_obj_create(ui_Container59);
    lv_obj_remove_style_all(ui_Container60);
    lv_obj_set_width(ui_Container60, 309);
    lv_obj_set_height(ui_Container60, 18);
    lv_obj_set_x(ui_Container60, -100);
    lv_obj_set_y(ui_Container60, -217);
    lv_obj_set_align(ui_Container60, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container60, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container61 = lv_obj_create(ui_Container59);
    lv_obj_remove_style_all(ui_Container61);
    lv_obj_set_width(ui_Container61, 340);
    lv_obj_set_height(ui_Container61, 30);
    lv_obj_set_x(ui_Container61, 11);
    lv_obj_set_y(ui_Container61, -105);
    lv_obj_set_align(ui_Container61, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container61, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container61, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container61, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label57 = lv_label_create(ui_Container61);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, -82);
    lv_obj_set_y(ui_Label57, -146);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "状态：");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4state = lv_label_create(ui_Container61);
    lv_obj_set_width(ui_port4state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4state, 38);
    lv_obj_set_y(ui_port4state, -149);
    lv_obj_set_align(ui_port4state, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4state, "已连接");
    lv_obj_set_style_text_color(ui_port4state, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4state, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4state, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container62 = lv_obj_create(ui_Container61);
    lv_obj_remove_style_all(ui_Container62);
    lv_obj_set_width(ui_Container62, 30);
    lv_obj_set_height(ui_Container62, 17);
    lv_obj_set_x(ui_Container62, -82);
    lv_obj_set_y(ui_Container62, -138);
    lv_obj_set_align(ui_Container62, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container62, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label58 = lv_label_create(ui_Container61);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, -87);
    lv_obj_set_y(ui_Label58, -93);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "协议：");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4protocol = lv_label_create(ui_Container61);
    lv_obj_set_width(ui_port4protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4protocol, 27);
    lv_obj_set_y(ui_port4protocol, -94);
    lv_obj_set_align(ui_port4protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4protocol, "PD3.1");
    lv_obj_set_style_text_color(ui_port4protocol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4protocol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4protocol, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container63 = lv_obj_create(ui_Container59);
    lv_obj_remove_style_all(ui_Container63);
    lv_obj_set_width(ui_Container63, 340);
    lv_obj_set_height(ui_Container63, 30);
    lv_obj_set_x(ui_Container63, -75);
    lv_obj_set_y(ui_Container63, -112);
    lv_obj_set_align(ui_Container63, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container63, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container63, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container63, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label59 = lv_label_create(ui_Container63);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, -76);
    lv_obj_set_y(ui_Label59, -109);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "制造商：");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4manufactuervid = lv_label_create(ui_Container63);
    lv_obj_set_width(ui_port4manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4manufactuervid, 26);
    lv_obj_set_y(ui_port4manufactuervid, -122);
    lv_obj_set_align(ui_port4manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4manufactuervid, "VIVO");
    lv_obj_set_style_text_color(ui_port4manufactuervid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4manufactuervid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4manufactuervid, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container64 = lv_obj_create(ui_Container59);
    lv_obj_remove_style_all(ui_Container64);
    lv_obj_set_width(ui_Container64, 340);
    lv_obj_set_height(ui_Container64, 30);
    lv_obj_set_x(ui_Container64, -82);
    lv_obj_set_y(ui_Container64, -127);
    lv_obj_set_align(ui_Container64, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container64, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container64, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container64, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label61 = lv_label_create(ui_Container64);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -73);
    lv_obj_set_y(ui_Label61, -69);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "线缆厂商：");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4cablevid = lv_label_create(ui_Container64);
    lv_obj_set_width(ui_port4cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4cablevid, 93);
    lv_obj_set_y(ui_port4cablevid, -78);
    lv_obj_set_align(ui_port4cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4cablevid, "制糖工厂");
    lv_obj_set_style_text_color(ui_port4cablevid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4cablevid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4cablevid, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container65 = lv_obj_create(ui_Container59);
    lv_obj_remove_style_all(ui_Container65);
    lv_obj_set_width(ui_Container65, 340);
    lv_obj_set_height(ui_Container65, 30);
    lv_obj_set_x(ui_Container65, -113);
    lv_obj_set_y(ui_Container65, -67);
    lv_obj_set_align(ui_Container65, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container65, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container65, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container65, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label63 = lv_label_create(ui_Container65);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, -127);
    lv_obj_set_y(ui_Label63, -87);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "最大电压：");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4maxvbusvoltage = lv_label_create(ui_Container65);
    lv_obj_set_width(ui_port4maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4maxvbusvoltage, -38);
    lv_obj_set_y(ui_port4maxvbusvoltage, -85);
    lv_obj_set_align(ui_port4maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4maxvbusvoltage, "20V");
    lv_obj_set_style_text_color(ui_port4maxvbusvoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4maxvbusvoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4maxvbusvoltage, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container66 = lv_obj_create(ui_Container65);
    lv_obj_remove_style_all(ui_Container66);
    lv_obj_set_width(ui_Container66, 18);
    lv_obj_set_height(ui_Container66, 9);
    lv_obj_set_x(ui_Container66, -50);
    lv_obj_set_y(ui_Container66, -101);
    lv_obj_set_align(ui_Container66, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container66, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label65 = lv_label_create(ui_Container65);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 77);
    lv_obj_set_y(ui_Label65, -85);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "最大电流：");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4maxvbuscurrent = lv_label_create(ui_Container65);
    lv_obj_set_width(ui_port4maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4maxvbuscurrent, 85);
    lv_obj_set_y(ui_port4maxvbuscurrent, -93);
    lv_obj_set_align(ui_port4maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4maxvbuscurrent, "5A");
    lv_obj_set_style_text_color(ui_port4maxvbuscurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4maxvbuscurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4maxvbuscurrent, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_port4SCREEN42, ui_event_port4SCREEN42, LV_EVENT_ALL, NULL);

}

void ui_port4SCREEN42_screen_destroy(void)
{
    if(ui_port4SCREEN42) lv_obj_del(ui_port4SCREEN42);

    // NULL screen variables
    ui_port4SCREEN42 = NULL;
    ui_Container59 = NULL;
    ui_Container60 = NULL;
    ui_Container61 = NULL;
    ui_Label57 = NULL;
    ui_port4state = NULL;
    ui_Container62 = NULL;
    ui_Label58 = NULL;
    ui_port4protocol = NULL;
    ui_Container63 = NULL;
    ui_Label59 = NULL;
    ui_port4manufactuervid = NULL;
    ui_Container64 = NULL;
    ui_Label61 = NULL;
    ui_port4cablevid = NULL;
    ui_Container65 = NULL;
    ui_Label63 = NULL;
    ui_port4maxvbusvoltage = NULL;
    ui_Container66 = NULL;
    ui_Label65 = NULL;
    ui_port4maxvbuscurrent = NULL;

}

void ui_port4SCREEN42_screen_relocalize(void)
{
    // label widgets on screen

}
