// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PROT4SCREEN_H
#define UI_PROT4SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_prot4SCREEN
extern void ui_prot4SCREEN_screen_init(void);
extern void ui_prot4SCREEN_screen_destroy(void);
extern void ui_prot4SCREEN_screen_relocalize(void);
extern void ui_event_prot4SCREEN(lv_event_t * e);
extern lv_obj_t * ui_prot4SCREEN;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_Container30;
extern lv_obj_t * ui_port4powerpagelabel;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Container32;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_port4voltage;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_port4current;
extern lv_obj_t * ui_Container34;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_port4powerlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

