// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PROT2SCREEN_H
#define UI_PROT2SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_prot2SCREEN
extern void ui_prot2SCREEN_screen_init(void);
extern void ui_prot2SCREEN_screen_destroy(void);
extern void ui_prot2SCREEN_screen_relocalize(void);
extern void ui_event_prot2SCREEN(lv_event_t * e);
extern lv_obj_t * ui_prot2SCREEN;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_port2powerpagelabel;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_port2voltage;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_port2current;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_port2powerlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

