// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_port2SCREEN22 = NULL;
lv_obj_t * ui_Container43 = NULL;
lv_obj_t * ui_Container44 = NULL;
lv_obj_t * ui_Container45 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_port2state = NULL;
lv_obj_t * ui_Container46 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_port2protocol = NULL;
lv_obj_t * ui_Container47 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_port2manufactuervid = NULL;
lv_obj_t * ui_Container48 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_port2cablevid = NULL;
lv_obj_t * ui_Container49 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_port2maxvbusvoltage = NULL;
lv_obj_t * ui_Container50 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_port2maxvbuscurrent = NULL;
// event funtions
void ui_event_port2SCREEN22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot2SCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_prot2SCREEN_screen_init);
    }
}

// build funtions

void ui_port2SCREEN22_screen_init(void)
{
    ui_port2SCREEN22 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_port2SCREEN22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container43 = lv_obj_create(ui_port2SCREEN22);
    lv_obj_remove_style_all(ui_Container43);
    lv_obj_set_width(ui_Container43, lv_pct(100));
    lv_obj_set_height(ui_Container43, lv_pct(100));
    lv_obj_set_align(ui_Container43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container43, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container43, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container43, &ui_img_934861631, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container44 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container44);
    lv_obj_set_width(ui_Container44, 309);
    lv_obj_set_height(ui_Container44, 18);
    lv_obj_set_x(ui_Container44, -100);
    lv_obj_set_y(ui_Container44, -217);
    lv_obj_set_align(ui_Container44, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container45 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container45);
    lv_obj_set_width(ui_Container45, 340);
    lv_obj_set_height(ui_Container45, 30);
    lv_obj_set_x(ui_Container45, 11);
    lv_obj_set_y(ui_Container45, -105);
    lv_obj_set_align(ui_Container45, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container45, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container45, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container45, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -82);
    lv_obj_set_y(ui_Label29, -146);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "状态：");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2state = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_port2state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2state, 38);
    lv_obj_set_y(ui_port2state, -149);
    lv_obj_set_align(ui_port2state, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2state, "已连接");
    lv_obj_set_style_text_color(ui_port2state, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2state, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2state, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container46 = lv_obj_create(ui_Container45);
    lv_obj_remove_style_all(ui_Container46);
    lv_obj_set_width(ui_Container46, 30);
    lv_obj_set_height(ui_Container46, 17);
    lv_obj_set_x(ui_Container46, -82);
    lv_obj_set_y(ui_Container46, -138);
    lv_obj_set_align(ui_Container46, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -87);
    lv_obj_set_y(ui_Label30, -93);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "协议：");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2protocol = lv_label_create(ui_Container45);
    lv_obj_set_width(ui_port2protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2protocol, 27);
    lv_obj_set_y(ui_port2protocol, -94);
    lv_obj_set_align(ui_port2protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2protocol, "PD3.1");
    lv_obj_set_style_text_color(ui_port2protocol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2protocol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2protocol, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container47 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container47);
    lv_obj_set_width(ui_Container47, 340);
    lv_obj_set_height(ui_Container47, 30);
    lv_obj_set_x(ui_Container47, -75);
    lv_obj_set_y(ui_Container47, -112);
    lv_obj_set_align(ui_Container47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container47, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container47, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container47, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Container47);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -76);
    lv_obj_set_y(ui_Label31, -109);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "制造商：");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2manufactuervid = lv_label_create(ui_Container47);
    lv_obj_set_width(ui_port2manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2manufactuervid, 26);
    lv_obj_set_y(ui_port2manufactuervid, -122);
    lv_obj_set_align(ui_port2manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2manufactuervid, "华为");
    lv_obj_set_style_text_color(ui_port2manufactuervid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2manufactuervid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2manufactuervid, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container48 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container48);
    lv_obj_set_width(ui_Container48, 340);
    lv_obj_set_height(ui_Container48, 30);
    lv_obj_set_x(ui_Container48, -82);
    lv_obj_set_y(ui_Container48, -127);
    lv_obj_set_align(ui_Container48, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container48, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container48, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container48, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Container48);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -73);
    lv_obj_set_y(ui_Label33, -69);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "线缆厂商：");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2cablevid = lv_label_create(ui_Container48);
    lv_obj_set_width(ui_port2cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2cablevid, 93);
    lv_obj_set_y(ui_port2cablevid, -78);
    lv_obj_set_align(ui_port2cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2cablevid, "华为");
    lv_obj_set_style_text_color(ui_port2cablevid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2cablevid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2cablevid, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container49 = lv_obj_create(ui_Container43);
    lv_obj_remove_style_all(ui_Container49);
    lv_obj_set_width(ui_Container49, 340);
    lv_obj_set_height(ui_Container49, 30);
    lv_obj_set_x(ui_Container49, -113);
    lv_obj_set_y(ui_Container49, -67);
    lv_obj_set_align(ui_Container49, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container49, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container49, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container49, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -127);
    lv_obj_set_y(ui_Label35, -87);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "最大电压：");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2maxvbusvoltage = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_port2maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2maxvbusvoltage, -38);
    lv_obj_set_y(ui_port2maxvbusvoltage, -85);
    lv_obj_set_align(ui_port2maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2maxvbusvoltage, "28V");
    lv_obj_set_style_text_color(ui_port2maxvbusvoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2maxvbusvoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2maxvbusvoltage, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container50 = lv_obj_create(ui_Container49);
    lv_obj_remove_style_all(ui_Container50);
    lv_obj_set_width(ui_Container50, 18);
    lv_obj_set_height(ui_Container50, 9);
    lv_obj_set_x(ui_Container50, -50);
    lv_obj_set_y(ui_Container50, -101);
    lv_obj_set_align(ui_Container50, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container50, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 77);
    lv_obj_set_y(ui_Label37, -85);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "最大电流：");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2maxvbuscurrent = lv_label_create(ui_Container49);
    lv_obj_set_width(ui_port2maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2maxvbuscurrent, 85);
    lv_obj_set_y(ui_port2maxvbuscurrent, -93);
    lv_obj_set_align(ui_port2maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2maxvbuscurrent, "5A");
    lv_obj_set_style_text_color(ui_port2maxvbuscurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2maxvbuscurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2maxvbuscurrent, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_port2SCREEN22, ui_event_port2SCREEN22, LV_EVENT_ALL, NULL);

}

void ui_port2SCREEN22_screen_destroy(void)
{
    if(ui_port2SCREEN22) lv_obj_del(ui_port2SCREEN22);

    // NULL screen variables
    ui_port2SCREEN22 = NULL;
    ui_Container43 = NULL;
    ui_Container44 = NULL;
    ui_Container45 = NULL;
    ui_Label29 = NULL;
    ui_port2state = NULL;
    ui_Container46 = NULL;
    ui_Label30 = NULL;
    ui_port2protocol = NULL;
    ui_Container47 = NULL;
    ui_Label31 = NULL;
    ui_port2manufactuervid = NULL;
    ui_Container48 = NULL;
    ui_Label33 = NULL;
    ui_port2cablevid = NULL;
    ui_Container49 = NULL;
    ui_Label35 = NULL;
    ui_port2maxvbusvoltage = NULL;
    ui_Container50 = NULL;
    ui_Label37 = NULL;
    ui_port2maxvbuscurrent = NULL;

}

void ui_port2SCREEN22_screen_relocalize(void)
{
    // label widgets on screen

}
