// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_prot4SCREEN = NULL;
lv_obj_t * ui_Container29 = NULL;
lv_obj_t * ui_Container30 = NULL;
lv_obj_t * ui_port4powerpagelabel = NULL;
lv_obj_t * ui_Container31 = NULL;
lv_obj_t * ui_Container32 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_port4voltage = NULL;
lv_obj_t * ui_Container33 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_port4current = NULL;
lv_obj_t * ui_Container34 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_port4powerlabel = NULL;
// event funtions
void ui_event_prot4SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot3SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_prot3SCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_port4SCREEN42, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_port4SCREEN42_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_totalpowerSCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_totalpowerSCREEN_screen_init);
    }
}

// build funtions

void ui_prot4SCREEN_screen_init(void)
{
    ui_prot4SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_prot4SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container29 = lv_obj_create(ui_prot4SCREEN);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_width(ui_Container29, lv_pct(100));
    lv_obj_set_height(ui_Container29, lv_pct(100));
    lv_obj_set_align(ui_Container29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container29, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container29, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container29, &ui_img_919862230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container30 = lv_obj_create(ui_Container29);
    lv_obj_remove_style_all(ui_Container30);
    lv_obj_set_width(ui_Container30, 246);
    lv_obj_set_height(ui_Container30, 22);
    lv_obj_set_x(ui_Container30, -30);
    lv_obj_set_y(ui_Container30, -174);
    lv_obj_set_align(ui_Container30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port4powerpagelabel = lv_label_create(ui_Container29);
    lv_obj_set_width(ui_port4powerpagelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4powerpagelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4powerpagelabel, -5);
    lv_obj_set_y(ui_port4powerpagelabel, -193);
    lv_obj_set_align(ui_port4powerpagelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4powerpagelabel, "C4端口");
    lv_obj_set_style_text_color(ui_port4powerpagelabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4powerpagelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4powerpagelabel, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container31 = lv_obj_create(ui_Container29);
    lv_obj_remove_style_all(ui_Container31);
    lv_obj_set_width(ui_Container31, 246);
    lv_obj_set_height(ui_Container31, 15);
    lv_obj_set_x(ui_Container31, -30);
    lv_obj_set_y(ui_Container31, -174);
    lv_obj_set_align(ui_Container31, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container32 = lv_obj_create(ui_Container29);
    lv_obj_remove_style_all(ui_Container32);
    lv_obj_set_width(ui_Container32, 260);
    lv_obj_set_height(ui_Container32, 45);
    lv_obj_set_x(ui_Container32, -152);
    lv_obj_set_y(ui_Container32, -127);
    lv_obj_set_align(ui_Container32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container32, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container32, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Container32);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -86);
    lv_obj_set_y(ui_Label18, -125);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "电压：");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4voltage = lv_label_create(ui_Container32);
    lv_obj_set_width(ui_port4voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4voltage, 33);
    lv_obj_set_y(ui_port4voltage, -126);
    lv_obj_set_align(ui_port4voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4voltage, "19.874V");
    lv_obj_set_style_text_color(ui_port4voltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4voltage, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container33 = lv_obj_create(ui_Container29);
    lv_obj_remove_style_all(ui_Container33);
    lv_obj_set_width(ui_Container33, 260);
    lv_obj_set_height(ui_Container33, 45);
    lv_obj_set_x(ui_Container33, -100);
    lv_obj_set_y(ui_Container33, -131);
    lv_obj_set_align(ui_Container33, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container33, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container33, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Container33);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -88);
    lv_obj_set_y(ui_Label19, -68);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "电流：");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4current = lv_label_create(ui_Container33);
    lv_obj_set_width(ui_port4current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4current, 26);
    lv_obj_set_y(ui_port4current, -71);
    lv_obj_set_align(ui_port4current, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port4current, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_port4current, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_port4current, "3.597A");
    lv_obj_set_style_text_color(ui_port4current, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4current, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container34 = lv_obj_create(ui_Container29);
    lv_obj_remove_style_all(ui_Container34);
    lv_obj_set_width(ui_Container34, 260);
    lv_obj_set_height(ui_Container34, 45);
    lv_obj_set_x(ui_Container34, -116);
    lv_obj_set_y(ui_Container34, -170);
    lv_obj_set_align(ui_Container34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container34, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container34, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -91);
    lv_obj_set_y(ui_Label20, -21);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "功率：");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_DaoLit36zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4powerlabel = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_port4powerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4powerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4powerlabel, 41);
    lv_obj_set_y(ui_port4powerlabel, -17);
    lv_obj_set_align(ui_port4powerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port4powerlabel, "37.592W");
    lv_obj_set_style_text_color(ui_port4powerlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4powerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4powerlabel, &ui_font_DaoLiti36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_prot4SCREEN, ui_event_prot4SCREEN, LV_EVENT_ALL, NULL);

}

void ui_prot4SCREEN_screen_destroy(void)
{
    if(ui_prot4SCREEN) lv_obj_del(ui_prot4SCREEN);

    // NULL screen variables
    ui_prot4SCREEN = NULL;
    ui_Container29 = NULL;
    ui_Container30 = NULL;
    ui_port4powerpagelabel = NULL;
    ui_Container31 = NULL;
    ui_Container32 = NULL;
    ui_Label18 = NULL;
    ui_port4voltage = NULL;
    ui_Container33 = NULL;
    ui_Label19 = NULL;
    ui_port4current = NULL;
    ui_Container34 = NULL;
    ui_Label20 = NULL;
    ui_port4powerlabel = NULL;

}

void ui_prot4SCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
