// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_port1SCREEN12 = NULL;
lv_obj_t * ui_Container35 = NULL;
lv_obj_t * ui_Container40 = NULL;
lv_obj_t * ui_Container36 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_port1state = NULL;
lv_obj_t * ui_Container38 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_port1protocol = NULL;
lv_obj_t * ui_Container37 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_port1manufactuervid = NULL;
lv_obj_t * ui_Container39 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_port1cablevid = NULL;
lv_obj_t * ui_Container41 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_port1maxvbusvoltage = NULL;
lv_obj_t * ui_Container42 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_port1maxvbuscurrent = NULL;
// event funtions
void ui_event_port1SCREEN12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot1SCREEN, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_prot1SCREEN_screen_init);
    }
}

// build funtions

void ui_port1SCREEN12_screen_init(void)
{
    ui_port1SCREEN12 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_port1SCREEN12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container35 = lv_obj_create(ui_port1SCREEN12);
    lv_obj_remove_style_all(ui_Container35);
    lv_obj_set_width(ui_Container35, lv_pct(100));
    lv_obj_set_height(ui_Container35, lv_pct(100));
    lv_obj_set_align(ui_Container35, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container35, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container35, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container35, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container35, &ui_img_934861631, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container40 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container40);
    lv_obj_set_width(ui_Container40, 309);
    lv_obj_set_height(ui_Container40, 18);
    lv_obj_set_x(ui_Container40, -100);
    lv_obj_set_y(ui_Container40, -217);
    lv_obj_set_align(ui_Container40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container36 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container36);
    lv_obj_set_width(ui_Container36, 340);
    lv_obj_set_height(ui_Container36, 30);
    lv_obj_set_x(ui_Container36, 11);
    lv_obj_set_y(ui_Container36, -105);
    lv_obj_set_align(ui_Container36, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container36, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container36, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -82);
    lv_obj_set_y(ui_Label39, -146);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "状态：");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1state = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_port1state, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1state, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1state, 38);
    lv_obj_set_y(ui_port1state, -149);
    lv_obj_set_align(ui_port1state, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1state, "已连接");
    lv_obj_set_style_text_color(ui_port1state, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1state, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1state, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container38 = lv_obj_create(ui_Container36);
    lv_obj_remove_style_all(ui_Container38);
    lv_obj_set_width(ui_Container38, 30);
    lv_obj_set_height(ui_Container38, 17);
    lv_obj_set_x(ui_Container38, -82);
    lv_obj_set_y(ui_Container38, -138);
    lv_obj_set_align(ui_Container38, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -87);
    lv_obj_set_y(ui_Label38, -93);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "协议：");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1protocol = lv_label_create(ui_Container36);
    lv_obj_set_width(ui_port1protocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1protocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1protocol, 27);
    lv_obj_set_y(ui_port1protocol, -94);
    lv_obj_set_align(ui_port1protocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1protocol, "PD3.1");
    lv_obj_set_style_text_color(ui_port1protocol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1protocol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1protocol, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container37 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container37);
    lv_obj_set_width(ui_Container37, 340);
    lv_obj_set_height(ui_Container37, 30);
    lv_obj_set_x(ui_Container37, -75);
    lv_obj_set_y(ui_Container37, -112);
    lv_obj_set_align(ui_Container37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container37, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container37, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Container37);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -76);
    lv_obj_set_y(ui_Label21, -109);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "制造商：");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1manufactuervid = lv_label_create(ui_Container37);
    lv_obj_set_width(ui_port1manufactuervid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1manufactuervid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1manufactuervid, 26);
    lv_obj_set_y(ui_port1manufactuervid, -122);
    lv_obj_set_align(ui_port1manufactuervid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1manufactuervid, "酷态科");
    lv_obj_set_style_text_color(ui_port1manufactuervid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1manufactuervid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1manufactuervid, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container39 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container39);
    lv_obj_set_width(ui_Container39, 340);
    lv_obj_set_height(ui_Container39, 30);
    lv_obj_set_x(ui_Container39, -82);
    lv_obj_set_y(ui_Container39, -127);
    lv_obj_set_align(ui_Container39, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container39, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Container39);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -73);
    lv_obj_set_y(ui_Label22, -69);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "线缆厂商：");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1cablevid = lv_label_create(ui_Container39);
    lv_obj_set_width(ui_port1cablevid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1cablevid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1cablevid, 93);
    lv_obj_set_y(ui_port1cablevid, -78);
    lv_obj_set_align(ui_port1cablevid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1cablevid, "制糖工厂");
    lv_obj_set_style_text_color(ui_port1cablevid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1cablevid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1cablevid, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container41 = lv_obj_create(ui_Container35);
    lv_obj_remove_style_all(ui_Container41);
    lv_obj_set_width(ui_Container41, 340);
    lv_obj_set_height(ui_Container41, 30);
    lv_obj_set_x(ui_Container41, -113);
    lv_obj_set_y(ui_Container41, -67);
    lv_obj_set_align(ui_Container41, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container41, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container41, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -127);
    lv_obj_set_y(ui_Label25, -87);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "最大电压：");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1maxvbusvoltage = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_port1maxvbusvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1maxvbusvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1maxvbusvoltage, -38);
    lv_obj_set_y(ui_port1maxvbusvoltage, -85);
    lv_obj_set_align(ui_port1maxvbusvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1maxvbusvoltage, "20V");
    lv_obj_set_style_text_color(ui_port1maxvbusvoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1maxvbusvoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1maxvbusvoltage, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container42 = lv_obj_create(ui_Container41);
    lv_obj_remove_style_all(ui_Container42);
    lv_obj_set_width(ui_Container42, 18);
    lv_obj_set_height(ui_Container42, 9);
    lv_obj_set_x(ui_Container42, -50);
    lv_obj_set_y(ui_Container42, -101);
    lv_obj_set_align(ui_Container42, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 77);
    lv_obj_set_y(ui_Label27, -85);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "最大电流：");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1maxvbuscurrent = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_port1maxvbuscurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1maxvbuscurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1maxvbuscurrent, 85);
    lv_obj_set_y(ui_port1maxvbuscurrent, -93);
    lv_obj_set_align(ui_port1maxvbuscurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1maxvbuscurrent, "3A");
    lv_obj_set_style_text_color(ui_port1maxvbuscurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1maxvbuscurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1maxvbuscurrent, &ui_font_daoli24zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_port1SCREEN12, ui_event_port1SCREEN12, LV_EVENT_ALL, NULL);

}

void ui_port1SCREEN12_screen_destroy(void)
{
    if(ui_port1SCREEN12) lv_obj_del(ui_port1SCREEN12);

    // NULL screen variables
    ui_port1SCREEN12 = NULL;
    ui_Container35 = NULL;
    ui_Container40 = NULL;
    ui_Container36 = NULL;
    ui_Label39 = NULL;
    ui_port1state = NULL;
    ui_Container38 = NULL;
    ui_Label38 = NULL;
    ui_port1protocol = NULL;
    ui_Container37 = NULL;
    ui_Label21 = NULL;
    ui_port1manufactuervid = NULL;
    ui_Container39 = NULL;
    ui_Label22 = NULL;
    ui_port1cablevid = NULL;
    ui_Container41 = NULL;
    ui_Label25 = NULL;
    ui_port1maxvbusvoltage = NULL;
    ui_Container42 = NULL;
    ui_Label27 = NULL;
    ui_port1maxvbuscurrent = NULL;

}

void ui_port1SCREEN12_screen_relocalize(void)
{
    // label widgets on screen

}
