// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PORT3SCREEN32_H
#define UI_PORT3SCREEN32_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_port3SCREEN32
extern void ui_port3SCREEN32_screen_init(void);
extern void ui_port3SCREEN32_screen_destroy(void);
extern void ui_port3SCREEN32_screen_relocalize(void);
extern void ui_event_port3SCREEN32(lv_event_t * e);
extern lv_obj_t * ui_port3SCREEN32;
extern lv_obj_t * ui_Container51;
extern lv_obj_t * ui_Container52;
extern lv_obj_t * ui_Container53;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_port1state2;
extern lv_obj_t * ui_Container54;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_port1protocol2;
extern lv_obj_t * ui_Container55;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Container56;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Container57;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Container58;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label56;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

