// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STANDBYSCREEN_H
#define UI_STANDBYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_standbySCREEN
extern void ui_standbySCREEN_screen_init(void);
extern void ui_standbySCREEN_screen_destroy(void);
extern void ui_standbySCREEN_screen_relocalize(void);
extern void ui_event_standbySCREEN(lv_event_t * e);
extern lv_obj_t * ui_standbySCREEN;
extern lv_obj_t * ui_standbywallpaper;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_dataweekContainer;
extern lv_obj_t * ui_dataLabel;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_weekLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

