// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_totalpowerSCREEN = NULL;
lv_obj_t * ui_totalwallpaper = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_totalpowerlabel = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_port1t2Cantainer = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_port1power = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_port2power = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_port1powerbar = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_port2powerbar = NULL;
lv_obj_t * ui_port3t4Cantainer = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_port3power = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_port4power = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_port3powerbar = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_port4powerbar = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
// event funtions
void ui_event_totalpowerSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_standbySCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_standbySCREEN_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_prot1SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot1SCREEN_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_prot1SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot1SCREEN_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_prot2SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot2SCREEN_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_prot3SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot3SCREEN_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_prot4SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_prot4SCREEN_screen_init);
    }
}

// build funtions

void ui_totalpowerSCREEN_screen_init(void)
{
    ui_totalpowerSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_totalpowerSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_totalwallpaper = lv_obj_create(ui_totalpowerSCREEN);
    lv_obj_remove_style_all(ui_totalwallpaper);
    lv_obj_set_width(ui_totalwallpaper, 368);
    lv_obj_set_height(ui_totalwallpaper, 448);
    lv_obj_set_align(ui_totalwallpaper, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_totalwallpaper, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_totalwallpaper, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_totalwallpaper, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_totalwallpaper, &ui_img_411710101, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_totalwallpaper);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 219);
    lv_obj_set_height(ui_Container10, 24);
    lv_obj_set_x(ui_Container10, -100);
    lv_obj_set_y(ui_Container10, -163);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_totalpowerlabel = lv_label_create(ui_totalwallpaper);
    lv_obj_set_width(ui_totalpowerlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalpowerlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalpowerlabel, 9);
    lv_obj_set_y(ui_totalpowerlabel, -161);
    lv_obj_set_align(ui_totalpowerlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalpowerlabel, "163W");
    lv_obj_set_style_text_color(ui_totalpowerlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_totalpowerlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_totalpowerlabel, &ui_font_DaoLiti72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_totalwallpaper);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 229);
    lv_obj_set_height(ui_Container11, 3);
    lv_obj_set_x(ui_Container11, -27);
    lv_obj_set_y(ui_Container11, -136);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port1t2Cantainer = lv_obj_create(ui_totalwallpaper);
    lv_obj_remove_style_all(ui_port1t2Cantainer);
    lv_obj_set_width(ui_port1t2Cantainer, 320);
    lv_obj_set_height(ui_port1t2Cantainer, 40);
    lv_obj_set_x(ui_port1t2Cantainer, 56);
    lv_obj_set_y(ui_port1t2Cantainer, -67);
    lv_obj_set_align(ui_port1t2Cantainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port1t2Cantainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_port1t2Cantainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_port1t2Cantainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_port1t2Cantainer);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -157);
    lv_obj_set_y(ui_Label1, -109);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "C1: ");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port1power = lv_label_create(ui_port1t2Cantainer);
    lv_obj_set_width(ui_port1power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port1power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port1power, -97);
    lv_obj_set_y(ui_port1power, -76);
    lv_obj_set_align(ui_port1power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port1power, "24.59W");
    lv_obj_set_style_text_color(ui_port1power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port1power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port1power, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_port1t2Cantainer);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 58);
    lv_obj_set_height(ui_Container8, 37);
    lv_obj_set_x(ui_Container8, -10);
    lv_obj_set_y(ui_Container8, -64);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_port1t2Cantainer);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -157);
    lv_obj_set_y(ui_Label2, -109);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "C2: ");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port2power = lv_label_create(ui_port1t2Cantainer);
    lv_obj_set_width(ui_port2power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port2power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port2power, 108);
    lv_obj_set_y(ui_port2power, -73);
    lv_obj_set_align(ui_port2power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port2power, "100.0W");
    lv_obj_set_style_text_color(ui_port2power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port2power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port2power, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_totalwallpaper);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 320);
    lv_obj_set_height(ui_Container12, 26);
    lv_obj_set_x(ui_Container12, 14);
    lv_obj_set_y(ui_Container12, -71);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image12, &ui_img_334752297);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image12, 89);
    lv_obj_set_y(ui_Image12, 39);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port1powerbar = lv_bar_create(ui_Image12);
    lv_bar_set_value(ui_port1powerbar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_port1powerbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_port1powerbar, 117);
    lv_obj_set_height(ui_port1powerbar, 17);
    lv_obj_set_x(ui_port1powerbar, -1);
    lv_obj_set_y(ui_port1powerbar, 0);
    lv_obj_set_align(ui_port1powerbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_port1powerbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port1powerbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_port1powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_port1powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port1powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_port1powerbar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_port1powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_port1powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Container12);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 60);
    lv_obj_set_height(ui_Container1, 23);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Container12);
    lv_img_set_src(ui_Image13, &ui_img_334752297);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image13, 89);
    lv_obj_set_y(ui_Image13, 39);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port2powerbar = lv_bar_create(ui_Image13);
    lv_bar_set_value(ui_port2powerbar, 33, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_port2powerbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_port2powerbar, 117);
    lv_obj_set_height(ui_port2powerbar, 17);
    lv_obj_set_x(ui_port2powerbar, -1);
    lv_obj_set_y(ui_port2powerbar, 0);
    lv_obj_set_align(ui_port2powerbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_port2powerbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port2powerbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_port2powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_port2powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port2powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_port2powerbar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_port2powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_port2powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_port3t4Cantainer = lv_obj_create(ui_totalwallpaper);
    lv_obj_remove_style_all(ui_port3t4Cantainer);
    lv_obj_set_width(ui_port3t4Cantainer, 320);
    lv_obj_set_height(ui_port3t4Cantainer, 40);
    lv_obj_set_x(ui_port3t4Cantainer, -49);
    lv_obj_set_y(ui_port3t4Cantainer, -68);
    lv_obj_set_align(ui_port3t4Cantainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port3t4Cantainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_port3t4Cantainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_port3t4Cantainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_port3t4Cantainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -157);
    lv_obj_set_y(ui_Label3, -109);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "C3: ");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port3power = lv_label_create(ui_port3t4Cantainer);
    lv_obj_set_width(ui_port3power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port3power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port3power, -99);
    lv_obj_set_y(ui_port3power, 3);
    lv_obj_set_align(ui_port3power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_port3power, "16.31W");
    lv_obj_set_style_text_color(ui_port3power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port3power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port3power, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_port3t4Cantainer);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 58);
    lv_obj_set_height(ui_Container9, 41);
    lv_obj_set_x(ui_Container9, -4);
    lv_obj_set_y(ui_Container9, -128);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_port3t4Cantainer);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -157);
    lv_obj_set_y(ui_Label4, -109);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "C4: ");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x0F5D08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_port4power = lv_label_create(ui_port3t4Cantainer);
    lv_obj_set_width(ui_port4power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_port4power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_port4power, 103);
    lv_obj_set_y(ui_port4power, 1);
    lv_obj_set_align(ui_port4power, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_port4power, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_port4power, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_port4power, "5.243W");
    lv_obj_set_style_text_color(ui_port4power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_port4power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_port4power, &ui_font_daoli26zhong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_totalwallpaper);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 26);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image11, &ui_img_334752297);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image11, 89);
    lv_obj_set_y(ui_Image11, 39);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port3powerbar = lv_bar_create(ui_Image11);
    lv_bar_set_value(ui_port3powerbar, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_port3powerbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_port3powerbar, 117);
    lv_obj_set_height(ui_port3powerbar, 17);
    lv_obj_set_x(ui_port3powerbar, -1);
    lv_obj_set_y(ui_port3powerbar, 0);
    lv_obj_set_align(ui_port3powerbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_port3powerbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port3powerbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_port3powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_port3powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port3powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_port3powerbar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_port3powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_port3powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 60);
    lv_obj_set_height(ui_Container5, 23);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image10, &ui_img_334752297);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 116
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image10, 89);
    lv_obj_set_y(ui_Image10, 39);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_port4powerbar = lv_bar_create(ui_Image10);
    lv_bar_set_value(ui_port4powerbar, 86, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_port4powerbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_port4powerbar, 117);
    lv_obj_set_height(ui_port4powerbar, 17);
    lv_obj_set_x(ui_port4powerbar, -1);
    lv_obj_set_y(ui_port4powerbar, 0);
    lv_obj_set_align(ui_port4powerbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_port4powerbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port4powerbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_port4powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_port4powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_port4powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_port4powerbar, &ui_img_888914300, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_port4powerbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_port4powerbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_totalpowerSCREEN);
    lv_obj_set_width(ui_Button1, 120);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -95);
    lv_obj_set_y(ui_Button1, -94);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_totalpowerSCREEN);
    lv_obj_set_width(ui_Button2, 120);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 88);
    lv_obj_set_y(ui_Button2, -95);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_totalpowerSCREEN);
    lv_obj_set_width(ui_Button3, 120);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -91);
    lv_obj_set_y(ui_Button3, -26);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_totalpowerSCREEN);
    lv_obj_set_width(ui_Button4, 120);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 89);
    lv_obj_set_y(ui_Button4, -26);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_totalpowerSCREEN, ui_event_totalpowerSCREEN, LV_EVENT_ALL, NULL);

}

void ui_totalpowerSCREEN_screen_destroy(void)
{
    if(ui_totalpowerSCREEN) lv_obj_del(ui_totalpowerSCREEN);

    // NULL screen variables
    ui_totalpowerSCREEN = NULL;
    ui_totalwallpaper = NULL;
    ui_Container10 = NULL;
    ui_totalpowerlabel = NULL;
    ui_Container11 = NULL;
    ui_port1t2Cantainer = NULL;
    ui_Label1 = NULL;
    ui_port1power = NULL;
    ui_Container8 = NULL;
    ui_Label2 = NULL;
    ui_port2power = NULL;
    ui_Container12 = NULL;
    ui_Image12 = NULL;
    ui_port1powerbar = NULL;
    ui_Container1 = NULL;
    ui_Image13 = NULL;
    ui_port2powerbar = NULL;
    ui_port3t4Cantainer = NULL;
    ui_Label3 = NULL;
    ui_port3power = NULL;
    ui_Container9 = NULL;
    ui_Label4 = NULL;
    ui_port4power = NULL;
    ui_Container2 = NULL;
    ui_Image11 = NULL;
    ui_port3powerbar = NULL;
    ui_Container5 = NULL;
    ui_Image10 = NULL;
    ui_port4powerbar = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Button3 = NULL;
    ui_Button4 = NULL;

}

void ui_totalpowerSCREEN_screen_relocalize(void)
{
    // label widgets on screen

}
