// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TOTALPOWERSCREEN_H
#define UI_TOTALPOWERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_totalpowerSCREEN
extern void ui_totalpowerSCREEN_screen_init(void);
extern void ui_totalpowerSCREEN_screen_destroy(void);
extern void ui_totalpowerSCREEN_screen_relocalize(void);
extern void ui_event_totalpowerSCREEN(lv_event_t * e);
extern lv_obj_t * ui_totalpowerSCREEN;
extern lv_obj_t * ui_totalwallpaper;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_totalpowerlabel;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_port1t2Cantainer;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_port1power;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_port2power;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_port1powerbar;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_port2powerbar;
extern lv_obj_t * ui_port3t4Cantainer;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_port3power;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_port4power;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_port3powerbar;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_port4powerbar;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

